### ISSUE TITLE
Fix statistical.test_median

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#10037]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5638037172"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5638037172"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5633061884/job/15261581589"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5638037172"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5638037172"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by ankit-prasadx** [comment]
Is this issue fixed?
