### ISSUE TITLE
Fix sorting.test_numpy_lexsort

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#10298]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6308956401/job/17127969443"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6308956401/job/17127969443"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6308956401/job/17127969443"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6308956401/job/17127969443"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6308956401/job/17127969443"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by saaagarsingh** [comment]
Hey @ivy-leaves can I look into the issues and start working on some of the sub tasks. If it is not being assigned to anyone do let me know.

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
