### ISSUE TITLE
add scikit-learn frontend function to ivy       https://scikit-learn.org/stable/modules/classes.html   

### ISSUE THREAD

**Issue by ndurumo254** [unifyai/ivy#10382]
_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [ ] BaseEstimator
- [ ] BiclusterMixin
- [ ] ClassifierMixin
- [ ] DensityMixin
- [ ] RegressorMixin
- [ ] TransformerMixin
- [ ] clone
- [ ] is_classifier
- [ ] is_regressor
- [ ] config_context
- [ ] get_config
- [ ] set_config
- [ ] show_versions
- [ ] CalibratedClassifierCV
- [ ] calibration_curve
- [ ] AffinityPropagation
- [ ] AgglomerativeClustering
- [ ] Birch
- [ ] DBSCAN
- [ ] FeatureAgglomeration
- [ ] KMeans
- [ ] BisectingKMeans
- [ ] MiniBatchKMeans
- [ ] MeanShift
- [ ] OPTICS
- [ ] SpectralClustering
- [ ] SpectralBiclustering
- [ ] SpectralCoclustering
- [ ] affinity_propagation
- [ ] cluster_optics_dbscan
- [ ] cluster_optics_xi
- [ ] compute_optics_graph
- [ ] dbscan
- [ ] estimate_bandwidth
- [ ] k_means
- [ ] kmeans_plusplus
- [ ] mean_shift
- [ ] spectral_clustering
- [ ] ward_tree
- [ ] EmpiricalCovariance
- [ ] EllipticEnvelope
- [ ] GraphicalLasso
- [ ] GraphicalLassoCV
- [ ] LedoitWolf
- [ ] MinCovDet
- [ ] OAS
- [ ] GraphicalLassoCV
- [ ] empirical_covariance
- [ ] graphical_lasso
- [ ] ledoit_wolf
- [ ] oas
- [ ] shrunk_covariance
- [ ] CCA
- [ ] PLSCanonical
- [ ] PLSRegression
- [ ] PLSSVD

**Comment by ndurumo254** [comment]
#10401

**Comment by ipriyam26** [comment]
@AnnaTz can i work on these, if so will the directly be going in the master or do they need another branch?

**Comment by AnnaTz** [comment]
@aditya-hari you will be in charge of expanding our frontend support, right? Could you please guide this issue? For organizational reasons I think it would be best to break this ToDo list into several functionality groups, such as base classes, clustering, composite estimators etc. as is done in the official API https://scikit-learn.org/stable/modules/classes.html.

**Comment by shantanavKapse** [comment]
Hello! I want to contribute to this task. Can someone please guide me to do so? @aditya-hari @AnnaTz

**Comment by amoungui** [comment]
- [ ] #27121
