### ISSUE TITLE
Fix array.test_array_function

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#10450]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5637895962"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by sdanishka** [comment]
Merge branch 'unifyai:master' into master

Merge branch 'unifyai:master' into master

Merge branch 'unifyai:master' into master

Revert "Add real function to Numpy frontend"

Merge branch 'unifyai:master' into master
