### ISSUE TITLE
[Bug]: `vector_norm` numpy backend implementation returns wrong result for some norms

### ISSUE THREAD

**Issue by nikifaets** [unifyai/ivy#10480]
### Bug Explanation

When the `norm` argument is `inf` or `-inf`, `ivy.functional.backends.numpy.linalg.vector_norm` is returning different results from `numpy.linalg.norm`.

### Steps to Reproduce Bug

Code to reproduce:
```
>>> import ivy
>>> import numpy as np
>>> x = ivy.array([[1., 2., 3.], [2., -1., 0.]])
>>> ivy.functional.backends.numpy.linalg.vector_norm(x, axis = 0, ord = float("inf"))
array([1., 1., 1.], dtype=float32)
>>> np.linalg.norm(x, axis = 0, ord = float("inf"))
array([2., 2., 3.], dtype=float32)
```

### Environment

Manjaro Linux, python virtual environment with the package versions from `requirements.txt`.

### Ivy Version

v1.1.9

### Backend

- [X] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [X] JAX

### Device

CPU: AMD Ryzen 5

**Comment by nikifaets** [comment]
Thank for the feedback @suvadityamuk. I updated my original comment to make it a complete example. Just tested it and reproduced the bug.

**Comment by suvadityamuk** [comment]
Hi, @nikifaets 

I have successfully reproduced the bug, thank you for making the changes.

Upon preliminary investigation, it seems there is some arbitrary code that is running on the specific use-case you have presented, within Ivy for the specific `np.linalg.norm` function, which should ideally not be the case. Allow me some more time to investigate. Thank you for your patience!

**Comment by nikifaets** [comment]
Update: The same bug was present with the jax backend, so the PR includes changes there as well. Torch and TF backends work fine.
