### ISSUE TITLE
Conv2D

### ISSUE THREAD

**Issue by kaushal07wick** [unifyai/ivy#10505]

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would like to continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues

**Comment by kaushal07wick** [comment]
Conv2D #10505 #11224

**Comment by kaushal07wick** [comment]
some problem with the previous pr, kindly refer to the new pr ASAP Conv2D #10505 #11812

**Comment by kaushal07wick** [comment]
and @AryanSharma9917 it shoes a error like this 
```
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py:155: in <module>
    dtype_and_x=helpers.dtype_and_shape(
E   AttributeError: module 'ivy_tests.test_ivy.helpers' has no attribute 'dtype_and_shape'
```

when i run the tests

**Comment by kaushal07wick** [comment]
Conv2D #10505 #11991, new pr please take a look at this.

**Comment by kaushal07wick** [comment]
Hey @jkeane508 , I have been working on this problem for quite a while now, I am working on the explicit_padding support.
Why are using the @AryanSharma9917 PR.
Hey @AryanSharma9917 , I have already told you that I am working on this issue, why are u still working on this.

My PR is almost complete. Kindly review the PR.
