### ISSUE TITLE
ivy.einsum

### ISSUE THREAD

**Issue by Ahmed-Khaled22** [unifyai/ivy#10577]
I created an issue yesterday to start working on einsum function frontend, but it doesn't have a backend function, which would make the frontend much simpler. I can start working on the backend function, and when it's merged, ill work on the frontend. Please advise on what to do next.

**Comment by hirwa-nshuti** [comment]
Hey @Ahmed-Khaled22 
This function already exists on the functional API
https://github.com/unifyai/ivy/blob/52f4479f0e2f58ccded46bff9e2140f08b02aa41/ivy/functional/ivy/statistical.py#L1155

**Comment by Ahmed-Khaled22** [comment]
Thank you for the clarification. I was searching in ivy/functional/backends/numpy/linear_algebra.py this is why i couldn't find it.

**Comment by hirwa-nshuti** [comment]
This function is implemented under the statistical submodule that's why you couldn't find it in the linear_algebra submodule😊
Going to close this item as completed.
Thanks🙂
