### ISSUE TITLE
[Bug]: Runtime error in docstring tests

### ISSUE THREAD

**Issue by nikifaets** [unifyai/ivy#10620]
### Bug Explanation

Docstring tests are failing with runtime error.

Example pipeline: https://github.com/unifyai/ivy/actions/runs/4206388280/jobs/7299804850

### Steps to Reproduce Bug

Run the dosctring tests.
E.g. `python3 -m pytest ivy_tests/test_docstrings.py`

### Environment

Linux, Dev Container

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by nikifaets** [comment]
After some digging, I think I may have found the root cause. The line where the test break is 75: 

`if fn_name not in ivy.backend.backend_handler.ivy_original_dict:`. 

Before #10327, this line used to be: 

`if fn_name not in ivy.backend_handler.ivy_original_dict:`

There is a global string variable called `backend` which is shadowing the `backend` module, hence the error:
```
>       if fn_name not in ivy.backend.backend_handler.ivy_original_dict:
E       AttributeError: 'str' object has no attribute 'backend_handler'
```

**Comment by CatB1t** [comment]
Hello @nikifaets, thanks for reporting this and looking into it more. Pushed a fix for it: https://github.com/unifyai/ivy/commit/e6d69456ba5e39a15d5ae8b5fa717fea09e766d4.

**Comment by nikifaets** [comment]
Hi @CatB1t, thanks for addressing this issue, as well as #10622. 

Just curious, is implementing unit tests for handling such failures somewhere on the roadmap? Big PRs such as #10327 introduce a lot of changes and may cause many regressions unless thoroughly tested.

**Comment by CatB1t** [comment]
Hello @nikifaets, yes definitely! a thorough tests will be added to ensure it's working properly. although It may be hard to detect issues related to environment like the one in #10622 unless reported by users.
