### ISSUE TITLE
eagerpy comparison?

### ISSUE THREAD

**Issue by SamuelMarks** [unifyai/ivy#1063]
Have you seen this project? - https://github.com/jonasrauber/eagerpy

Has some overlap with your concept so thought to bring it up (in case you hadn't heard of it). Might be worth replying with a comparison?

Thanks

**Comment by jkeane508** [comment]
Hi,

Eagerpy does allow for users to write framework agnostic code but it does not allow for code conversions like Ivy 🚀

The recommended way of using it is passing a native array from any framework to it, applying transformations and receiving a native array from it, which enables easy switching between networks. Whereas Ivy enables automatic code conversions between frameworks with only a few lines of code. 💪

I hope this provides a distinction between the two projects!

Thanks :)
