### ISSUE TITLE
Add Elementwise Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10652]
Add [Elementwise Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) to Paddle backend
_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_
# Bitwise

- [x] #10938
- [x] #10831
- [x] #10939
- [x] #10940
- [x] #11017
- [x] bitwise_left_shift

# Logical

- [x] #10941
- [x] #10942
- [x] #10943
- [x] #10944

# Trignometric and Hyperbolic

- [x] #10768
- [x] #10778
- [x] #10776 
- [x] #10773
- [x] #11000
- [x] #10946
- [x] #10802
- [x] #10804
- [x] #10947
- [x] #10827
- [x] #10749
- [x] #10793
- [x] #10801
- [x] #10783
- [x] #10826

# Conditions
- [x] #10948
- [x] #10949
- [x] #10950
- [x] #10951
- [x] #10952
- [x] #10953
- [x] #10954
- [x] #10955
- [x] #10956
- [x] #10957
- [x] #10958
- [x] #10959

# Others
- [x] expm1
- [x] #10813
- [x] #10927
- [x] #10928
- [x] #10960
- [x] #10961
- [x] #10962
- [x] #10963
- [x] #10964
- [x] #10965
- [x] #10966
- [x] #10967
- [x] #10968
- [x] #10969
- [x] #10929
- [x] #10970
- [x] #10926
- [x] #12106
- [x] #10988
- [x] #10972
- [x] #10933
- [x] #10973
- [x] #10974
- [x] #10975
- [x] #10976
- [x] #10977
- [x] #10978

# Experimental

- [x] lcm
- [x] fmod
- [x] fmax
- [x] fmin
- [x] sinc
- [x] trapz
- [x] #12509
- [x] #13289
- [x] #13406
- [x] #11389
- [x] #11108
- [x] #11106
- [x] #11109
- [x] #11107
- [x] #11607
- [x] #12751
- [x] #13407
- [x] #11110
- [x] #13813
- [x] #11624
- [x] #11608
- [x] fix
- [x] nextafter
- [x] #13408
- [x] gradient
- [x] xlogy

##

**Comment by 5a7man** [comment]
#10749

**Comment by 5a7man** [comment]
#10768

**Comment by soma2000-lang** [comment]
cos #10773

**Comment by soma2000-lang** [comment]
cosh #10776

**Comment by soma2000-lang** [comment]
asinh #10778

**Comment by soma2000-lang** [comment]
sinh #10783

**Comment by aparna2071** [comment]
- [ ] #10793

**Comment by 5a7man** [comment]
#10801

**Comment by 5a7man** [comment]
#10802

**Comment by 5a7man** [comment]
#10804

**Comment by soma2000-lang** [comment]
add #10813

**Comment by 5a7man** [comment]
#10826

**Comment by 5a7man** [comment]
#10926

**Comment by 5a7man** [comment]
#10927

**Comment by 5a7man** [comment]
#10928

**Comment by 5a7man** [comment]
#10929

**Comment by 5a7man** [comment]
#10931

**Comment by aaryanmittal154** [comment]
#10933

**Comment by ZiadAmerr** [comment]
- [] #10938

**Comment by ZiadAmerr** [comment]
- [] #10940

**Comment by ZiadAmerr** [comment]
- [] #10941

**Comment by ZiadAmerr** [comment]
- [] #10942

**Comment by ZiadAmerr** [comment]
- [] #10943

**Comment by ZiadAmerr** [comment]
- [] #10944

**Comment by ZiadAmerr** [comment]
- [] #10946

**Comment by ZiadAmerr** [comment]
- [] #10947

**Comment by ZiadAmerr** [comment]
- [] #10947

**Comment by ZiadAmerr** [comment]
- [] #10948

**Comment by ZiadAmerr** [comment]
- [] #10949

**Comment by ZiadAmerr** [comment]
- [] #10950

**Comment by ZiadAmerr** [comment]
- [] #10951

**Comment by ZiadAmerr** [comment]
- [] #10952

**Comment by ZiadAmerr** [comment]
- [] #10953

**Comment by ZiadAmerr** [comment]
- [] #10954

**Comment by ZiadAmerr** [comment]
- [] #10955

**Comment by ZiadAmerr** [comment]
- [] #10956

**Comment by ZiadAmerr** [comment]
- [] #10957

**Comment by ZiadAmerr** [comment]
- [] #10958

**Comment by ZiadAmerr** [comment]
- [] #10959

**Comment by ZiadAmerr** [comment]
- [] #10960

**Comment by ZiadAmerr** [comment]
- [] #10961

**Comment by ZiadAmerr** [comment]
- [] #10963

**Comment by ZiadAmerr** [comment]
- [] #10964

**Comment by ZiadAmerr** [comment]
- [] #10965

**Comment by ZiadAmerr** [comment]
- [] #10966

**Comment by ZiadAmerr** [comment]
- [] #10967

**Comment by ZiadAmerr** [comment]
- [] #10968

**Comment by ZiadAmerr** [comment]
- [] #10969

**Comment by ZiadAmerr** [comment]
- [] #1097

**Comment by ZiadAmerr** [comment]
- [] #10971

**Comment by ZiadAmerr** [comment]
- [] #10973

**Comment by ZiadAmerr** [comment]
- [] #10974

**Comment by ZiadAmerr** [comment]
- [] #10975

**Comment by ZiadAmerr** [comment]
- [] #10977

**Comment by ZiadAmerr** [comment]
- [] #10978

**Comment by PrajwalKoirala** [comment]
log #10988

**Comment by xingyu-long** [comment]
#11000

**Comment by vandit98** [comment]
bitwise_right_shift #11017

**Comment by vandit98** [comment]
fmax #11068

**Comment by vandit98** [comment]
#11106

**Comment by vandit98** [comment]
#11107

**Comment by vandit98** [comment]
#11108

**Comment by vandit98** [comment]
#11109

**Comment by vandit98** [comment]
#11110

**Comment by vandit98** [comment]
#11111

**Comment by vandit98** [comment]
#11363

**Comment by jatinS-dev** [comment]
#11389

**Comment by jatinS-dev** [comment]
#11488

**Comment by jatinS-dev** [comment]
#11590

**Comment by vandit98** [comment]
#11607

**Comment by vandit98** [comment]
#11608

**Comment by vandit98** [comment]
#11621

**Comment by Tejal-19** [comment]
#11622

**Comment by vandit98** [comment]
#11624

**Comment by vandit98** [comment]
#11625

**Comment by Tejal-19** [comment]
- [ ] #11797

**Comment by ojask12** [comment]
- [ ] #11907

**Comment by DevilRuler1** [comment]
#12106

**Comment by ojask12** [comment]
- [ ] #12115

**Comment by ojask12** [comment]
- [ ] #12116

**Comment by ojask12** [comment]
- [ ] #12117

**Comment by ojask12** [comment]
- [ ] #12118

**Comment by ojask12** [comment]
- [ ] #12119

**Comment by ipriyam26** [comment]
- [ ] #12509

**Comment by umer200** [comment]
- [ ] #12751

**Comment by umer200** [comment]
- [ ] #13188

**Comment by vandit98** [comment]
nan_to_num #11111

**Comment by vandit98** [comment]
copysign #13406

**Comment by vandit98** [comment]
logaddexp2 #13407

**Comment by Tristan1649** [comment]
#13813

**Comment by umer200** [comment]
- [ ] #14301

**Comment by rogn02** [comment]
- [ ] #13813 

Is this open to work on?

**Comment by rogn02** [comment]
- [ ] #14301
