### ISSUE TITLE
Add General Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10694]
Add [General Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) to Paddle backend

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] is_native_array
- [x] array_equal
- [x] get_item
- [x] to_numpy
- [x] to_scalar
- [x] to_list
- [x] #12592
- [x] gather_nd
- [x] get_num_dims
- [x] inplace_arrays_supported
- [x] #12211
- [x] #12212
- [x] inplace_update
- [x] #12213
- [x] multiprocessing
- [x] scatter_flat
- [x] scatter_nd
- [x] shape
- [x] vmap

## Experimental

- [x] isin

**Comment by soma2000-lang** [comment]
inplace_increment #10817

**Comment by ipriyam26** [comment]
- [ ] #11125

**Comment by soma2000-lang** [comment]
inplace increment #11355

**Comment by Husienvora** [comment]
- [ ] #11738

**Comment by Filip-Philip** [comment]
#11893

**Comment by vtsamit** [comment]
#12211

**Comment by vtsamit** [comment]
#12212

**Comment by vtsamit** [comment]
#12213

**Comment by czirabence** [comment]
- [ ] #12592

**Comment by trantuantdt** [comment]
- [ ]  #14180
