### ISSUE TITLE
Add Gradient Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10695]
Add [Gradient Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index\_en.html) to Paddle backend

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [x] variable
- [x] is\_variable
- [x] variable\_data
- [x] execute\_with\_gradients
- [x] value\_and\_grad
- [x] stop\_gradients
- [x] jac
- [x] grad

## Experimental

- [x] #26119

**Comment by Moshood-Wale** [comment]
#26119
