### ISSUE TITLE
Add Random Processes Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10699]
Add [Random Processes Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index\_en.html) to Paddle backend

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [x] random\_uniform
- [x] random\_normal
- [x] #17424
- [x] #12139
- [x] seed
- [x] shuffle

## Experimental

- [x] #16208
- [x] #19083
- [x] gamma
- [x] poisson
- [x] #19078

> The main file paths where these functions are likely to be added are: 
> - `ivy/functional/backends/paddle/random.py`
> - `ivy/functional/backends/paddle/experimental/random.py`

**Comment by apurvakbh** [comment]
@MahmoudAshraf97 I will be working on these issues. If possible please do not assign these tasks to anyone else. 
cc: @djl11 (Assignment of Apurva Bhatt)
Thank you

**Comment by apurvakbh** [comment]
#11742

**Comment by apurvakbh** [comment]
-[] #11756

**Comment by MahmoudAshraf97** [comment]
@apurvakbh please open an issue on the single task that you are working on, do not assign yourself more than one task

**Comment by hackslashX** [comment]
- [ ]  #12139

**Comment by asadimtiazmalik** [comment]
- [ ] #12348

**Comment by apurvakbh** [comment]
#12356 shuffle

**Comment by hackslashX** [comment]
- [] #12570

**Comment by umer200** [comment]
-[ ] #12749

**Comment by asadimtiazmalik** [comment]
- [ ] #13604

**Comment by umer200** [comment]
- [ ] #13705

**Comment by nandu-k01** [comment]
- [ ] #13707

**Comment by hossamEldeinMohmed** [comment]
poisson

**Comment by ugorjiizu** [comment]
I would like to work on the random normal function
P.S there is no PaddlePaddle branch

**Comment by rogn02** [comment]
- [ ] #12570

**Comment by jdc98** [comment]
- gamma #14828

**Comment by asparius** [comment]
- [ ] #15361

**Comment by jyjoshi** [comment]
- [ ] #16208

**Comment by mohame54** [comment]
#17424

**Comment by MuhammadNizamani** [comment]
@MahmoudAshraf97  shuffle function is added please mark it done.

**Comment by mohame54** [comment]
#19078

**Comment by mohame54** [comment]
#19083

**Comment by gabryellesoares** [comment]
- [ ] #19079

**Comment by gabryellesoares** [comment]
- [ ] #19079

**Comment by jyjoshi** [comment]
- [ ] #19290
