### ISSUE TITLE
Add Statistical Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10704]
Add [Statistical Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index\_en.html) to Paddle backend

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [x] #10760
- [x] #10807
- [x] #10852
- [x] #10868
- [x] #10873
- [x] #10874
- [x] #10875
- [x] #13078
- [x] cumsum
- [x] einsum

## Experimental

- [x] median
- [x] #10923
- [x] #10932
- [x] #23384
- [x] #14694
- [x] #11058

> The main file paths where these functions are likely to be added are: 
> - `ivy/functional/backends/paddle/statistical.py`
> - `ivy/functional/backends/paddle/experimental/statistical.py`

**Comment by mosesdaudu001** [comment]
#10760

**Comment by KevinUnadkat** [comment]
#10807

**Comment by paritoshtripathi935** [comment]
- [ ] #10852

**Comment by KevinUnadkat** [comment]
#10868

**Comment by KevinUnadkat** [comment]
#10874

**Comment by KevinUnadkat** [comment]
#10875

**Comment by ShauryaPanwar** [comment]
- [] #10877

**Comment by KevinUnadkat** [comment]
> * [] [<std> #10877](https://github.com/unifyai/ivy/issues/10877)

hy @ShauryaPanwar 
  im already work on the std function can utake something else to work on

**Comment by KevinUnadkat** [comment]
#10878

**Comment by KevinUnadkat** [comment]
#10879

**Comment by KevinUnadkat** [comment]
#10880

**Comment by ShauryaPanwar** [comment]
#10881

**Comment by paritoshtripathi935** [comment]
#10923

**Comment by mosesdaudu001** [comment]
#10932

**Comment by KevinUnadkat** [comment]
#11010

**Comment by KevinUnadkat** [comment]
#11014

**Comment by Ishaan-Chandak** [comment]
[ ] #11058

**Comment by mehular0ra** [comment]
Can I take median, nanmean, quantile?

**Comment by mosesdaudu001** [comment]
yes you can handle quantile, I have been struggling with it for a while now. It will be good to see how someone else handles it.

**Comment by mehular0ra** [comment]
Thanks @mosesdaudu001. @MahmoudAshraf97 can it be assigned to me?

**Comment by MahmoudAshraf97** [comment]
@mehular0ra , sure you can continue working from here #11188

**Comment by Tristan1649** [comment]
hi @MahmoudAshraf97 can i take this one?

**Comment by ShashJan94** [comment]
einsum #12015
quantile #12014
nanmean #12013 
unravel_index ##12016

**Comment by Ishaan-Chandak** [comment]
@ShashJan94 I am already working on unravel_index

**Comment by Tristan1649** [comment]
updated

**Comment by harshxtanwar** [comment]
#12341

**Comment by avinashyadav0027** [comment]
- [ ]  #12608

**Comment by Tristan1649** [comment]
#12842

**Comment by Tristan1649** [comment]
#11855

**Comment by Tristan1649** [comment]
#10

**Comment by matiasandov** [comment]
#13270

**Comment by Tristan1649** [comment]
#13246

**Comment by marshad35** [comment]
-[  ] #13568

**Comment by trantuantdt** [comment]
-[ ] #13817

**Comment by trantuantdt** [comment]
- [ ] #13817

**Comment by rogn02** [comment]
- [ ] #13246

**Comment by chinonsoonodi** [comment]
- [ ] #13831

**Comment by mobley-trent** [comment]
-[ ] #13856

**Comment by mobley-trent** [comment]
- [  ] #13860

**Comment by Dev-Khant** [comment]
#14694

**Comment by jyjoshi** [comment]
- [ ] #16023

**Comment by Kibet-g** [comment]
import paddle

# Custom statistical function: Mean Absolute Deviation (MAD)
def mad(x):
    mean = paddle.mean(x)
    deviation = paddle.abs(x - mean)
    mad = paddle.mean(deviation)
    return mad

# Custom statistical function: Z-score
def z_score(x):
    mean = paddle.mean(x)
    std_dev = paddle.std(x)
    z = (x - mean) / std_dev
    return z

# Example usage
data = paddle.to_tensor([1.0, 2.0, 3.0, 4.0, 5.0])
result_mad = mad(data)
result_z_score = z_score(data)

print("Mean Absolute Deviation (MAD):", result_mad.numpy())
print("Z-score:", result_z_score.numpy())

**Comment by UnwillingCrab85** [comment]
#17510

**Comment by dhruvgrover1251** [comment]
- [ ] #19008

**Comment by vishwas31** [comment]
#19529

**Comment by tejeshbhalla** [comment]
#21009

**Comment by rogn02** [comment]
- [ ] #21009

**Comment by Reptilefury** [comment]
- [  ] median

**Comment by Reptilefury** [comment]
- [ ] median#10922

**Comment by Reptilefury** [comment]
- [ ] #10922

**Comment by researchstarter** [comment]
corrcoef #23384

**Comment by MaxRiabytsia** [comment]
- [ ] #23437

**Comment by SherjeelAhmed** [comment]
#23511

**Comment by AjayDyavathi** [comment]
corrcoef #23384

**Comment by Moshood-Wale** [comment]
#26066
