### ISSUE TITLE
Add Sparse Array Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10703]
Add [Sparse Array Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index\_en.html) to Paddle backend

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

## Experimental

- [x] is\_native\_sparse\_array
- [ ] native\_sparse\_array
- [ ] native\_sparse\_array\_to\_indices\_values\_and\_shape

**Comment by Ados1** [comment]
is_native_sparse_array

**Comment by Ados1** [comment]
#10832

**Comment by Ishaan-Chandak** [comment]
hiii @MahmoudAshraf97 I am interested to work on this issue

**Comment by MahmoudAshraf97** [comment]
Hi @Ishaan-Chandak , feel free to pick an unassigned task an d work on it

**Comment by Ishaan-Chandak** [comment]
Hi @MahmoudAshraf97 can you please provide me with some resources so that I get to know a little more about native_sparse_arrays

**Comment by MahmoudAshraf97** [comment]
Hi @Ishaan-Chandak, I don't know other source other than the official docs unfortunately
