### ISSUE TITLE
Add Utility Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10705]
Add [Utility Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) to Paddle backend
Please fork from the [`PaddlePaddle branch`](/unifyai/ivy/tree/PaddlePaddle) instead of `master`

- [x] #10737
- [x] #10747

**Comment by KevinUnadkat** [comment]
#10737

**Comment by KevinUnadkat** [comment]
#10747
