### ISSUE TITLE
Add Set Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10701]
Add [Set Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) to Paddle backend
Please fork from the [`PaddlePaddle branch`](/unifyai/ivy/tree/PaddlePaddle) instead of `master`

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #10924
- [x] #11528
- [x] #11593
- [x] #11714

**Comment by Maria-98-ui** [comment]
#10924

**Comment by AdvancedUno** [comment]
- [ ] #11528

**Comment by geetptl** [comment]
Can I take up unique_values? @MahmoudAshraf97

**Comment by geetptl** [comment]
- [ ] #11714
