### ISSUE TITLE
Add Searching Functions to Paddle Backend

### ISSUE THREAD

**Issue by MahmoudAshraf97** [unifyai/ivy#10700]
Add [Searching Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) to Paddle backend
Please fork from the [`PaddlePaddle branch`](/unifyai/ivy/tree/PaddlePaddle) instead of `master`

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #11901
- [x] #11902
- [x] nonzero
- [x] #11904
- [x] argwhere

**Comment by aaryanmittal154** [comment]
#11019

**Comment by aaryanmittal154** [comment]
#11021

**Comment by aaryanmittal154** [comment]
#11022

**Comment by aaryanmittal154** [comment]
#11023

**Comment by aaryanmittal154** [comment]
#11024
