### ISSUE TITLE
nested_map < Function Reformatting >

### ISSUE THREAD

**Issue by kalcho100** [unifyai/ivy#10710]

**Comment by ArpanDhot** [comment]
Commit ID: 20e4d12e3389a8a7daaff79eb2391a8b2a200aa7

This commit updates the `nested_map` method in two significant ways:

1. Lambda functions in the method are replaced with defined functions. The three lambda functions used to define the check functions for `tuple`, `list`, and `dict` types have been replaced with explicitly defined functions. This change is intended to increase code readability and maintainability.

2. The method's docstring has been expanded with usage examples. The added example demonstrates how to use the `nested_map` function on a nested list with a simple function to square each element. This addition enhances the method's usability by providing a clear, concrete example of its functionality.

These changes aim to improve the readability, maintainability, and usability of the `nested_map` method. Please run tests to ensure the function's behaviour remains as expected after these modifications.

**Comment by halbeeb** [comment]
I would be working on @nested_map #10710

**Comment by sampathr0007** [comment]
i Want to contribute the code for nested_map #10710  and want to make a Pull request

**Comment by pedrosaaaa** [comment]
21809
