### ISSUE TITLE
ivy.lerp

### ISSUE THREAD

**Issue by aparna2071** [unifyai/ivy#10762]
**Why should this be implemented?**
- I am currently working on #10683 which requires lerp function to be implemented but it is missing in ivy. Also, it requires a mix of several arithmetic operations like element-wise multiplication, addition & subtraction. Therefore, to simplify the function so that we don't need to compute so many arithmetic operations, I'm raising this issue on the suggestion of @fspyridakos.

**Links to native framework implementations**

- [PyTorch](https://pytorch.org/docs/stable/generated/torch.lerp.html)

**Comment by AnnaTz** [comment]
Alright, I added `lerp` under Elementwise functions here https://github.com/unifyai/ivy/issues/3856
