### ISSUE TITLE
ivy.matrix_exp

### ISSUE THREAD

**Issue by danny-1k** [unifyai/ivy#10795]
**Why should this be implemented?**
I am currently working on #10326 and I am required to implement the `matrix_exp` function for all backends (including Ivy).
There seems to be a `matrix_exp` implementation in the `ivy` backend but this references element-wise exp.
I am raising this issue for the expansion of the Ivy functional API specifically the separation of  `ivy.exp` from `ivy.matrix_exp`.

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.linalg.expm.html)
- [PyTorch](https://pytorch.org/docs/1.11/generated/torch.linalg.matrix_exp.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/expm)
- [NumPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.expm.html)

**Comment by Daniel4078** [comment]
The issue you are talking about is already closed as not planned, so I think it is not going to be implemented

**Comment by danny-1k** [comment]
@Daniel4078 It was a typo, the correct reference is #10326

**Comment by MahmoudAshraf97** [comment]
I see your point, I'll reference someone from the functional API team

**Comment by AnnaTz** [comment]
Hi @danny-1k. I think this functionality is worth adding to our experimental api. I see that both `exp` and `matrix_exp` in our experimental api call the same `exp` functions in their backends, which is redundant. If you'd like to work on this feel free to correct the existing `matrix_exp` function. Keep in mind though that you can't use scipy functions in jax's and numpy's backends.
