### ISSUE TITLE
vecdot

### ISSUE THREAD

**Issue by matiasandov** [unifyai/ivy#11044]
- [ ] #10691

**Comment by ashutosh887** [comment]
@matiasandov I would like to contribute to this Org.
Please assign me some issues to work upon

**Comment by matiasandov** [comment]
@ashutosh887 

Hello I am really not sure if one person should work at a time only, I am an applicant only. What about u?

**Comment by ashutosh887** [comment]
I'm also here to contribute @matiasandov as a part of GSOC

**Comment by matiasandov** [comment]
![image](https://user-images.githubusercontent.com/58478529/221375141-7cdaa9a5-dd6e-4021-ac67-1c3853a57095.png)
I am a little confused bc I don't understand if the method is finished already tho.

**Comment by matiasandov** [comment]
I guess this issue is already working
