### ISSUE TITLE
unifyai/ivy:latest docker image remote interpretor error

### ISSUE THREAD

**Issue by Ishticode** [unifyai/ivy#111]
I am conneted to the remote interpreter in unifyai/ivy:latest docker image but it gives an error (quoted at the end) upon trying to run any array api tests. This is in pycharm professional 2021.3.2, windows 10. Ive tried several things from the internet and the ivy discord server without any luck. 

Error running 'pytest for array_api_tests.test_linalg.test_matmul': Cannot run the remote Python interpreter: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown

**Comment by NIkhilbadveli** [comment]
Just add it like this. It will work.
![image](https://user-images.githubusercontent.com/24986098/153767173-f337c8cc-539d-4c64-a60b-4c1ae5cc69a7.png)

**Comment by Ishticode** [comment]
Thats how it was done.

**Comment by NIkhilbadveli** [comment]
I first tried with just "python" it was throwing "OCI runtime create failed" error. So, I tried with python3 and it worked. Even the tests are running now. Maybe try pulling the image again and see? I'm not sure.

**Comment by Ishticode** [comment]
Going to the interpreter settings for the given docker image and deleting --gpus all solved this problem.

![gpus](https://user-images.githubusercontent.com/53497039/154774562-976ff7c0-add6-4713-967d-e5fe0c5e8448.png)
