### ISSUE TITLE
integer

### ISSUE THREAD

**Issue by Sarvesh-Kesharwani** [unifyai/ivy#11170]
working on (#8431-> integer)

**Comment by Sarvesh-Kesharwani** [comment]
working on it

**Comment by Sarvesh-Kesharwani** [comment]
Hi @hirwa-nshuti
i checked https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.integer.html#jax.numpy.integer
but there is no function Integer to be implemented,
it is just a class and that also has only one method called isInteger,

so could you please guide me on what function exactly i need to implement?

**Comment by hirwa-nshuti** [comment]
Leave this one and pick another open task😊
