### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by sbansal1999** [unifyai/ivy#11220]
### Bug Explanation

Opening [this](https://lets-unify.ai/ivy/functional/ivy.html) link shows nothing in the content section.
![image](https://user-images.githubusercontent.com/35286603/221941514-5a1b8340-134f-41e6-92e3-d783eba8a071.png)

### Steps to Reproduce Bug

1. Open the Ivy Documentation. [Docs](https://lets-unify.ai/ivy/)
2. Click on *Functions* in *Site Navigation*
3.

### Environment

Microsoft Edge
Version 110.0.1587.57 (Official build) (64-bit)

### Ivy Version

-

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by fspyridakos** [comment]
Thanks for pointing out! @juliagsy could you take a look?

**Comment by juliagsy** [comment]
Hey! Thanks so much for pointing this out! This page is empty by default which resulted in the empty content, but it should be fixed now with a redirect to an available page! I'll close this for now, good spot! Thanks!
