### ISSUE TITLE
NVMLError_DriverNotLoaded: Driver not loaded

### ISSUE THREAD

**Issue by DiTo97** [unifyai/ivy#1150]
Why do I get the error in the title if I try to import Ivy on Google Colab with the standard runtime (CPU)? Any other runtime type (either GPU or TPU) works perfectly. If I am not mistaken, Ivy works on all kinds of devices, so I am not sure I get why it raises it.

I guess it has to do with missing NVIDIA drivers, but why would I have them installed on a CPU-only runtime?

### Steps to reproduce

Run the following code on Google Colab with the standard runtime:
```python
!pip install -U ivy-core==1.1.9

# pip imports
import ivy
```

**Comment by sreegandh804** [comment]
Hi there, try changing the hardware accelerator to GPU, which can be accessed by going to Runtime/Change Runtime type like I did in the screenshot and that should work.
![image](https://user-images.githubusercontent.com/56138447/169531733-5c5253ed-ed62-4a1d-81af-924e305cb7b2.png)

**Comment by DiTo97** [comment]
Probably the description was a bit misleading, but I filed the issue
specifically because I know that it works by switching to the GPU runtime.
What I wanted to understand is why it does not work with the CPU runtime,
considering that the library is built to work on CPU-only hardware as well.

In fact, I was curious about what Ivy does differently under the hood that
leads to this error, since I have never had any problems when running the
native frameworks it wraps with the CPU runtime.

**Comment by jkeane508** [comment]
Hi @DiTo97,

You are using an older version of Ivy. When importing Ivy if you specify version 1.1.10 or import Ivy with an unspecified version it should work without hardware acceleration 😀

**Comment by DiTo97** [comment]
Hi @jkeane508,

I can confirm that Ivy 1.1.10 works without hardware acceleration! 🚀

P.S.: You should probably update the first example in the README, because it is broken:
```python
import ivy


class MyModel(ivy.Module):
    def __init__(self):
        self.linear0 = ivy.Linear(3, 64)
        self.linear1 = ivy.Linear(64, 1)
        ivy.Module.__init__(self)

    def _forward(self, x):
        x = ivy.relu(self.linear0(x))
        return ivy.sigmoid(self.linear1(x))


ivy.set_backend('torch')  # change to any backend!
model = MyModel()
optimizer = ivy.Adam(1e-4)
x_in = ivy.array([1., 2., 3.])
target = ivy.array([0.])


def loss_fn(v):
    out = model(x_in, v=v)
    return ivy.mean((out - target)**2)


for step in range(100):
    loss, grads = ivy.execute_with_gradients(loss_fn, model.v)
    model.v = optimizer.step(model.v, grads)
    print('step {} loss {}'.format(step, ivy.to_numpy(loss).item()))

print('Finished training!')
```

In particular, `ivy.set_backend` has turned into `ivy.set_framework` and there is no trace of the `ivy.mean` method.
