### ISSUE TITLE
ivy.Array has no attribute 'size'

### ISSUE THREAD

**Issue by DiTo97** [unifyai/ivy#1152]
I am using your library to build a framework-agnostic monocular depth estimation model, but during testing I ran into the error in the title, as I was trying to get the flattened size of the weights of a specific Conv1D layer. 

The [ivy.Array docs](https://lets-unify.ai/ivy/design/ivy_as_a_framework/ivy_array.html) describe how most methods have been monkey patched with a wrapper that allows both ivy.Array and ivy.NativeArray to be accepted as valid I/O. Moreover, in the code snippet depicted there, it seems clear that ivy.Array has a 'data' property referencing the native array, while wrapping it with additional properties, such as 'size'. So, why is 'size' not a valid attribute? While debugging, I also noticed that not only does the 'data' property reference the native array, but the whole ivy.Array actually references that array (i.e., while using the PyTorch backend, if `w` is a torch.Tensor variable, then `w_` is a torch.Tensor as well, despite coming from `w_ = ivy.Array(w)`).

Is the monkey patch planned for a future release? I am using the latest Ivy 1.1.9 from PyPI.

**Comment by jkeane508** [comment]
Hi,

Ivy is constantly in development and the docs are being updated all the time. It is likely that the 1.1.9 version of Ivy is behind and does not include some features that are outlined in the current version of the docs. We are working super hard on our next release and hopefully it will resolve these issues! 🚀

We are super stoked to hear you are using Ivy to develop deep learning models! If you like you can share your project in the 
[Show and Tell](https://github.com/unifyai/ivy/discussions/categories/show-and-tell) of our GitHub Discussions 😀

Hopefully this answers your question!

**Comment by DiTo97** [comment]
No worries, I imagined there had been some latency between v1.1.9 and the docs.

I will surely consider sharing my models to the [Show and Tell](https://github.com/unifyai/ivy/discussions/categories/show-and-tell) section!

I will close the issue. Thanks for your effort, and cannot wait for the next realease of Ivy. 🤗
