### ISSUE TITLE
Fix array.test_array__deepcopy__

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#11737]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5372653830/jobs/9746259364"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5372653830/jobs/9746259364"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5372653830/jobs/9746259364"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5372653830/jobs/9746259364"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5372653830/jobs/9746259364"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by abdulasiraj** [comment]
Hi, 
It seems that no one working on this issue. If that the case, can you assign this to me? 

Thanks in advance!
