### ISSUE TITLE
tensorflow.image.resize

### ISSUE THREAD

**Issue by AnnaTz** [unifyai/ivy#11804]

**Comment by AryanSharma9917** [comment]
Hi @AnnaTz, for this do I need to create another file or work in 
ivy\functional\frontends\tensorflow\image ?

**Comment by AnnaTz** [comment]
Hi @AryanSharma9917, currently this function cannot be fully implemented due to some unsupported modes in `ivy.interpolate`. I'm currently working on adding those.

**Comment by AnnaTz** [comment]
completed in https://github.com/unifyai/ivy/commit/6659f803be1f6ab37a6df87f7f717faa55bc83cd
