### ISSUE TITLE
lu_factor_ex

### ISSUE THREAD

**Issue by gretagh93** [unifyai/ivy#11840]

**Comment by gretagh93** [comment]
Could I continue with this task? @AnnaTz

**Comment by AnnaTz** [comment]
> Could I continue with this task? @AnnaTz

Since no one has linked a new PR to this issue, I suppose you can.

**Comment by gretagh93** [comment]
Hi @AnnaTz,

lu_factor_ex is not included in the functional API. EVEN SO, Is it possible to create it in the PyTorch frontend? 
If not, what is the best course of action? Should I close this issue and open a new one?
Additionally, would you prefer that I tag you with an @ symbol when asking questions?

Thanks for all!

**Comment by AnnaTz** [comment]
@gretagh93 I think it is best to add the `check_errors` argument to our api's `lu_factor` function. In this case, the frontend will be easily implemented. I would suggest until then to work on another issue.
