### ISSUE TITLE
__matmul__

### ISSUE THREAD

**Issue by TudorAndrei** [unifyai/ivy#119]

**Comment by TudorAndrei** [comment]
@djl11 The PR closed, because I deleted my fork and started a new one because of the conflicts created by the array api submodule. I can implement the __matmul__ again, but how should I go about tests?

**Comment by djl11** [comment]
Unfortunately operator methods do not have dedicated unit tests in the Array API test suite, and so these issues are being closed. Please choose another method to work on. Apologies for the confusion.
