### ISSUE TITLE
Fix elementwise.test_isinf

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#11974]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5654382665/job/15317345125"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5654382665/job/15317345125"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5654382665/job/15317345125"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5654382665/job/15317345125"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5654382665/job/15317345125"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by srihar5ha** [comment]
Can i work on it?
