### ISSUE TITLE
[Bug]: module 'ivy' has no attribute 'set_backend' on Google Colab

### ISSUE THREAD

**Issue by eskayML** [unifyai/ivy#12336]
### Bug Explanation

First time contributor here , So I'm checking out the project by pasting the starter code on Colab , and this error pops up

```
 ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-c33e35f48654> in <module>
     11         return ivy.sigmoid(self.linear1(x))
     12 
---> 13 ivy.set_backend('torch')  # change to any backend!
     14 model = MyModel()
     15 optimizer = ivy.Adam(1e-4)

AttributeError: module 'ivy' has no attribute 'set_backend'
```

### Steps to Reproduce Bug

Running the Starter notebook in the documentation 

### Environment

Google Colab

### Ivy Version

1.1.10

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by shephinphilip** [comment]
@eskayML I like to solve the issue , Could you please tell me if this  issue was solved  or  not and could you please tell me exactly the file location because i  couldn't able to locate the colab in the project codebase

**Comment by eskayML** [comment]
Hello Philip , I think the issue I had is now currently fixed , since there happened to be a lot of changes in the repo since I raised this issue a few months ago. 

I think the code I used here was for creating an IvyNet Object
