### ISSUE TITLE
Fix linalg.test_eigvals

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#12493]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5634507705/job/15264498833"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by MckinstryJ** [comment]
- [ ] #12527
