### ISSUE TITLE
Fix ndarray.test_numpy_ndarray_astype

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#12530]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6419866811"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6419866811"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6419866811"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6419866811"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6419866811"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by ChakrabortyJoy** [comment]
`import numpy as np

from hypothesis import given, strategies as st

import ivy tests. test ivy.helpers as helpers import ivy, functional.backends.numpy as ivy_np

# concatenate

@given(

xs_n_input_dtypes_n_unique_idx=_arrays_idx_n_dtypes(), dtype_n_with_out=_dtype_n_with_out(),

as_variable-helpers.array_bools(),

num_positional_args=helpers.num_positional_args( fn_name="ivy.functional, frontends.numpy.concatenate"

),

native_array-helpers.array_bools(),
)

def test_numpy_concatenate(

xs_n_input_dtypes_n_unique_idx, dtype_n_with_out,

as_variable,

num_positional_args,

native_array,

fw,
):
    dtype,
    with out = dtype_n_with_out

    xs, input_dtypes, unique_idx = xs_n_input_dtypes_n_unique_idx

    [np.asarray(x, dtype=dt) for x, dt in zip(xs, input_dtypes)]
    helpers.test_frontend_function(

        input
    dtypes,

    as variable,

    with_out,

    num_positional_args,

    native_array,

    fw,

    "numpy",

    "concatenate",

    arrays = xS,

    axis - unique_idx,

    out=None,

    dtype=dtype,)`

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
