### ISSUE TITLE
Fix matrix_eigenvalues.test_numpy_eig

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#12760]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6373772593/job/17297775381"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6373772593/job/17297775381"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6373772593/job/17297775381"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6373772593/job/17297775381"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6373772593/job/17297775381"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by captain-peroxide** [comment]
#12765

**Comment by captain-peroxide** [comment]
- [ ] #12765
