### ISSUE TITLE
Inferring type hints

### ISSUE THREAD

**Issue by bhattbhuwan13** [unifyai/ivy#1294]
One of the major task in this project is writing the correct type annotations. I wanted to know which method you guys follow to find out the type hints? In the past, I have applied the following methods:  
- [Monkeytype](https://github.com/Instagram/MonkeyType) : It uses the data passed to a function parameter to infer its type.
- Unit Tests : For a repository containing unit tests, we can infer the data type by observing the variation of data in test cases.

If you use any other methods, please let me know.

**Comment by jkeane508** [comment]
Hi,

We don't use any specific methods to infer type hints, we write them manually🚀

I hope this answers your question
Thanks!

**Comment by bhattbhuwan13** [comment]
Got it. :)
