### ISSUE TITLE
Add "SOAP" to Ivy Experimental API 

### ISSUE THREAD

**Issue by krishna1111111** [unifyai/ivy#12992]
**Why should this be implemented?**
Simple object access protocol (SOAP) APIs are a type of web development tool that both humans and machines can read. This can ensure that the content they write is easy for machines to interpret and users to analyze.

**Links to native framework implementations**
- [Jax] - https://jax.readthedocs.io/en/latest/notebooks/quickstart.html
- [PyTorch] - https://pytorch.org/tutorials/recipes/android_native_app_with_custom_op.html
- [TensorFlow] - https://blog.tensorflow.org/2020/02/tensorflowjs-for-react-native-is-here.html
- [NumPy] - https://numpy.org/doc/stable/

**Comment by AnnaTz** [comment]
Hi @krishna1111111, Ivy API Experimental Suggestion issues are supposed to be used to suggest adding a _function_ to our API. I'd say that what you're suggesting is more like an extra layer of functionality. It's an interesting idea, but this is not the correct place to share it.

**Comment by krishna1111111** [comment]
Now ?

**Comment by krishna1111111** [comment]
now this is closed now what should i do

**Comment by AnnaTz** [comment]
You could share your proposal on our discord server. The suggestion issues are just to add functions to our api list, so nothing more to do here.
