### ISSUE TITLE
square

### ISSUE THREAD

**Issue by NIkhilbadveli** [unifyai/ivy#130]
Description: This issue tracks the progress on the QR decomposition API's as mentioned in the issue: https://github.com/unifyai/ivy/issues/63.
The API is being implemented for the following backends:

- [ ] tensorflow
- [ ] pytorch
- [ ] jax
- [ ] numpy
- [ ] mxnet

And the test code will be modified in the file _ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py_. The name of the function for reference: **test_square**

**Comment by 1Doomdie1** [comment]
Closing Issue due to interactivity.
