### ISSUE TITLE
Fix gradients.test_lamb_update

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#13154]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6159602589"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6159602589"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6103983853/job/16565311789"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6159602589"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6159602589"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by gulatisukaran** [comment]
Hey can i work on this ?
