### ISSUE TITLE
linalg.multi_dot

### ISSUE THREAD

**Issue by natek-1** [unifyai/ivy#13221]

**Comment by Aayush3014** [comment]
Hi, I am a beginner in open source and I would like to contribute to this repo by submitting the solution of this issue.
I want to contribute the code for the function for finding the determinant in NumPy frontend using the numpy.linalg module.
Can you please assign me this issue??

**Comment by Aayush3014** [comment]
@natek-1  Please assign me this issue and let me be the part of the open source community.

**Comment by natek-1** [comment]
Hey @Aayush3014,
this issue is about lining.multi_dot not about determinant. However, from looking at the fronted subtask, the one about determinants seem to be done.
