### ISSUE TITLE
Does ivy perform the same as the original framework？

### ISSUE THREAD

**Issue by cuiyc2000** [unifyai/ivy#1326]
If I ivy to run a stardand pytorch model， is it the same as the performance of pytorch？

**Comment by jkeane508** [comment]
Hi,

Currently there are no benchmarks for the performance of Ivy using different backends. However, during early experimentation, we observed runtime overhead in the order of ~1% when compared to the backends directly. 🚀

So when running your PyTorch model you should expect similar performance!

I hope this answers your question 😀
