### ISSUE TITLE
randn

### ISSUE THREAD

**Issue by AbdullahMakhdoom** [unifyai/ivy#13329]
Pytorch frontend for `torch.randn` function

**Comment by sahilempire** [comment]
Can you please tell me what exactly I have to do, to solve this issue? @AbdullahMakhdoom

**Comment by AbdullahMakhdoom** [comment]
Hi @sahilempire, I have already implemented this issue and sent a PR.
I you want to contribute, your best guide would be Ivy Docs Getting Started. https://lets-unify.ai/ivy/overview/contributing.html

**Comment by curiousHG** [comment]
@sahilempire This issue can be closed now?

**Comment by sahilempire** [comment]
@curiousHG yes, you can.
