### ISSUE TITLE
[Bug]: Incorrect hierarchy of tree in ivy docs website.

### ISSUE THREAD

**Issue by Sarvesh-Kesharwani** [unifyai/ivy#13366]
### Bug Explanation

- Upon selecting the deep dive section, two deep dive subcategories appear instead of just one.
![chrome_Sz8uKerY1k](https://user-images.githubusercontent.com/22115102/228505098-357e43a0-c9c2-4527-ad57-d70c7c5b84e4.png)

- Hierarchy of the tree is also incorrect, i.e., deep dive section is opening inside the contributing section
![chrome_0vBy3uYbRD](https://user-images.githubusercontent.com/22115102/228505739-2a1ae90d-7a2f-4b8d-90dd-dabefb1d9e4f.png)

### Steps to Reproduce Bug

- Visit https://lets-unify.ai/ivy/overview/deep_dive.html
- click on Deep Dive section of left 

### Environment

Chrome browser

### Ivy Version

None

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by Amartya-Jha** [comment]
Can this issue be assigned to me? Issue#13366

**Comment by fspyridakos** [comment]
@juliagsy @KareemMAX

**Comment by KareemMAX** [comment]
Hi @Sarvesh-Kesharwani,
Thanks for pointing that issue to us, currently we are making changes to our documentation system. We will fix it as soon as we can. 😄
