### ISSUE TITLE
collections Hashable error with Python3.10

### ISSUE THREAD

**Issue by askua** [unifyai/ivy#1341]
Python 3.7 hasn't this bug.

I got AttributeError: module 'collections' has no attribute 'Hashable'
python version 3.10.4

change the file:
Python310\Lib\site-packages\ivy\framework_handler.py
line 115:  collections.Hashable

line 115:  collections.abc.Hashable

reference:
https://github.com/SpenceKonde/AVR-Guidance/issues/9

**Comment by jkeane508** [comment]
Hi @askua 

It seems to be an issue with your Python package. I would recommend updating your Python version and seeing if that fixes things :)

**Comment by askua** [comment]
@jkeane508 
Ok, think you, my python version is from:
https://www.python.org/
I see the newest Python 3.10.5 on Windows 10, I will try.
