### ISSUE TITLE
logistic

### ISSUE THREAD

**Issue by rodlaf** [unifyai/ivy#13465]

**Comment by Amartya-Jha** [comment]
Can I be assigned Issue #13465 (logistic)

**Comment by rodlaf** [comment]
I opened this issue to be able to work on it myself, although I am unsure how to assign myself to it. If someone knows/can do this for me, I'd be very grateful.

**Comment by rodlaf** [comment]
> Can I be assigned Issue #13465 (logistic)

I opened this issue #13465 (logistic) to work on it myself and will be submitting a PR for it in the next few days.

**Comment by rodlaf** [comment]
I am closing this issue as there is no relevant ivy.logistic method that would work with this frontend method. I will work on another function
