### ISSUE TITLE
Fix rounding.test_numpy_floor

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#13501]
|   |   |
|---|---|
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6303990647/job/17114395113"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6303990647/job/17114395113"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6303990647/job/17114395113"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6303990647/job/17114395113"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6303990647/job/17114395113"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by rarisenpai** [comment]
Fix rounding.test_numpy_floor #13933
