### ISSUE TITLE
[Feature Request]: Formatter check should be added to ensure code quality and standards

### ISSUE THREAD

**Issue by AJOO7** [unifyai/ivy#13609]
Is your feature request related to a problem? Please describe.

I'm always frustrated when reading code with inconsistent formatting and style. It makes it difficult to understand and can lead to errors and bugs. I would like a solution to ensure consistent formatting and style in my codebase.

Describe the solution you'd like

I would like to use a code formatter to automatically format my code according to a consistent style and formatting rules. I have heard that the Black code formatter is a good choice for this, as it is fast, reliable, and easy to use.

Describe alternatives you've considered

I have considered manually formatting my code, but this is time-consuming and prone to errors. I have also considered using other code formatters, such as Flake8 and Pylint, but I have heard that Black is more powerful and easier to use.

Additional context

I would like to integrate the Black code formatter into my workflow using pre-commit hooks or editor plugins, so that my code is automatically detected. This will help ensure that my code is consistently formatted and styled, and will save me time and effort in the long run.

**Comment by Dsantra92** [comment]
We already have a black hook for pre-commit here: https://github.com/unifyai/ivy/blob/69954535cc1e33cf022e017ed9b0fbbe0a7d0981/.pre-commit-config.yaml#L4-L6
Just to be sure, is this the feature that you are talking about?

**Comment by AJOO7** [comment]
Yes, But we can have GitHub check just allocated to black formatter

**Comment by soma2000-lang** [comment]
@AJOO7  I don't think we need an additional Github check just for the black, because the pre-commit already takes care of that.
