### ISSUE TITLE
Fix from_shape_or_value.test_numpy_full

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#13973]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by abdulasiraj** [comment]
start working
