### ISSUE TITLE
Add Comparison ops to PyTorch Frontend

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#14]
Add [Comparison ops](https://pytorch.org/docs/stable/torch.html#comparison-ops) to PyTorch frontend:

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #3257
- [x] #3618
- [x] #3548
- [x] #3542
- [x] #3620
- [x] #3621
- [x] #3670
- [x] #3671
- [x] #3673
- [x] #3728
- [x] #3917
- [x] #3729
- [x] #3762
- [x] #3802
- [x] #3868
- [x] #3954
- [x] #5029
- [x] #3825
- [x] #3824
- [x] #3870
- [x] #3869
- [x] #5030
- [x] #3902
- [x] #3901
- [x] #3861
- [x] #3873
- [x] #3872
- [x] #3632
- [x] #5888
- [x] #3936

**Comment by hirwa-nshuti** [comment]
allclose #3257

**Comment by hirwa-nshuti** [comment]
- [ ] #3542

**Comment by hirwa-nshuti** [comment]
- [ ] #3548

**Comment by hirwa-nshuti** [comment]
- [ ] #3618

**Comment by hirwa-nshuti** [comment]
- [ ] #3620

**Comment by hirwa-nshuti** [comment]
- [ ] #3621

**Comment by Nightcrab** [comment]
- [ ] #3632

**Comment by hirwa-nshuti** [comment]
- [ ] #3670

**Comment by hirwa-nshuti** [comment]
- [ ] #3671

**Comment by hirwa-nshuti** [comment]
- [ ] #3673

**Comment by hirwa-nshuti** [comment]
- [ ] #3728

**Comment by hirwa-nshuti** [comment]
- [ ] #3729

**Comment by hirwa-nshuti** [comment]
- [ ] #3762

**Comment by hirwa-nshuti** [comment]
- [ ] #3802

**Comment by hirwa-nshuti** [comment]
- [ ] #3823

**Comment by hirwa-nshuti** [comment]
- [ ] #3824

**Comment by hirwa-nshuti** [comment]
- [ ] #3825

**Comment by Lapatou** [comment]
- [ ] #3861

**Comment by hirwa-nshuti** [comment]
- [ ] #3869

**Comment by hirwa-nshuti** [comment]
- [ ] #3870

**Comment by hirwa-nshuti** [comment]
- [ ] #3872

**Comment by hirwa-nshuti** [comment]
- [ ] #3873

**Comment by hirwa-nshuti** [comment]
- [ ] #3901

**Comment by mazy06000** [comment]
- [ ] maximum #3898

**Comment by simoneVU** [comment]
- [ ] #3917

**Comment by hirwa-nshuti** [comment]
- [ ] #3936

**Comment by hirwa-nshuti** [comment]
- [ ] #3954

**Comment by AnnaTz** [comment]
- [] #5029

**Comment by AnnaTz** [comment]
- [ ] #5030

**Comment by hirwa-nshuti** [comment]
- [ ] #5888
