### ISSUE TITLE
ivy.sets

### ISSUE THREAD

**Issue by rubada** [unifyai/ivy#14065]
**Why should this be implemented?**
An ivy function [ivy.sets](<https://github.com/unifyai/ivy/tree/master/ivy/functional/ivy>) is missing, which is necessary for Tensorflow.sets frontend functions, as shown below.

**Links to native framework implementations**
- [Tensorflow](<https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/tensorflow/sets.py>)

**Comment by AnnaTz** [comment]
Are you referring to the whole tf.sets module? The Suggestion issues are only for suggesting a specific function, not a whole group of functions.

**Comment by rubada** [comment]
Yes there is no ivy.sets for the all the fuctions, I'm new to this can you suggest what should I do for the whole group of functions?

Thank you

**Comment by AnnaTz** [comment]
No worries, I added union, intersection and difference to the [ToDo list](https://github.com/unifyai/ivy/issues/3856) of ivy functions to be added to our api. Feel free to work on this if you'd like.

**Comment by rubada** [comment]
Ok Thank you 😊👌
