### ISSUE TITLE
Fix math.test_tensorflow_zeta

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#14384]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6373163984/job/17296650217"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6373163984/job/17296650217"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6373163984/job/17296650217"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6373163984/job/17296650217"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6373163984/job/17296650217"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by AryanSharma21** [comment]
First run 

![torch_failed](https://user-images.githubusercontent.com/78106056/236751576-36305487-7324-4ead-b1cf-6c4eb76e8fe2.png)

Second run

![numpy_failed](https://user-images.githubusercontent.com/78106056/236752821-5352d83d-90d8-4a1f-b3be-165126c7645c.png)

Any suggestions about how to proceed would be great to start with

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
