### ISSUE TITLE
Fix arithmetic_operations.test_numpy_modf

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#14520]
|   |   |
|---|---|
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6370242270/job/17291167703"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6370242270/job/17291167703"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6370242270/job/17291167703"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6370242270/job/17291167703"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6370242270/job/17291167703"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by abdulasiraj** [comment]
start working
