### ISSUE TITLE
ivy.cummin

### ISSUE THREAD

**Issue by umairjavaid** [unifyai/ivy#14535]
I want to work on these functions. Kindly tell me how do I reserve the Ivy frontend, pytorch backend and jax backend implementation for this function. I have already reserved the pytorch frontend function for it here: https://github.com/unifyai/ivy/issues/14526

**Why should this be implemented?**
Because 2 of the native frameworks have it, and it's a complex function.

**Links to native framework implementations**
- [Jax]([https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cummin.html]
- [[PyTorch]()](https://pytorch.org/docs/stable/generated/torch.cummin.html?highlight=cummin#torch.cummin)

**Comment by umairjavaid** [comment]
if you add these to your todo lists, kindly share the links here so I can reserve them

**Comment by AnnaTz** [comment]
Hi @umairjavaid, we don't separate the backend implementations for the functions to be added to our api, we've got a single ToDo list, [here](https://github.com/unifyai/ivy/issues/3856). 
I have just added `cummin` under the statistical functions. Feel free to reserve it.
