### ISSUE TITLE
Fix indexing_like_operations.test_indices

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#14582]
|   |   |
|---|---|
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536031286" rel="noopener noreferrer" target="_blank"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536044068" rel="noopener noreferrer" target="_blank"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536031286" rel="noopener noreferrer" target="_blank"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536041487" rel="noopener noreferrer" target="_blank"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by abdulasiraj** [comment]
start working
