### ISSUE TITLE
Fix indexing_like_operations.test_numpy_unravel_index

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#14583]
|   |   |
|---|---|
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/4771148025/jobs/8482888921"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536043183"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536041298"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/4798143998/jobs/8536038847"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by abdulasiraj** [comment]
start working
