### ISSUE TITLE
[Bug]: conv2d throwing shape related errors

### ISSUE THREAD

**Issue by zhumakhan** [unifyai/ivy#14626]
### Bug Explanation

numpy backend conv2d functions is trowing *ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.*.

This happens when we try to pad given input image with given pad values, Currently *data_format* accepted by numpy is *NHWC*, thus its current padding is ```[(0,0), *pad_list, (0,0)]```,  *where pad_list* is the padding provided by user (e.g. for 2D is (x_pad, y_pad)), and (0,0) pads are for batch and channel axes.
As a fix changed ```[(0,0), *pad_list, (0,0)]``` to ```[(0,0), *[(_p,_p) for _p in pad_list], (0,0)]``` so that dimensions of elements along 0-axis are all same.

### Steps to Reproduce Bug

import ivy
import sys

import os
ivy.set_backend('numpy')

image = ivy.random_normal(shape=(1,3,16,16), dtype=ivy.float32, device='cpu')
inch,outch = 3,10
kernel_size = [3,3]
strides = [1,1]
paddings = [1,1]
dilations = [1,1]

kernels = ivy.random_normal(shape=kernel_size + [inch, outch], dtype=ivy.float32, device='cpu')
ivy.conv2d(image, kernels, strides, paddings, data_format = "NCHW", dilations=dilations)

### Environment

Ubuntu + docker

### Ivy Version

actively under development

### Backend

- [X] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

CPU

**Comment by 9118271153shivamgupta** [comment]
To reproduce the error, you can run the code snippet and check the resulting error message. Alternatively, you can modify the code to explicitly print out the error message, as follows:

import ivy
import sys
import numpy

import os
ivy.set_backend('numpy')

image = ivy.random_normal(shape=(1,3,16,16), dtype=ivy.float32, device='cpu')
inch,outch = 3,10
kernel_size = [3,3]
strides = [1,1]
paddings = [1,1]
dilations = [1,1]

kernels = ivy.random_normal(shape=kernel_size + [inch, outch], dtype=ivy.float32, device='cpu')

try:
    ivy.conv2d(image, kernels, strides, paddings, data_format = "NCHW", dilations=dilations)
except ValueError as e:
    print(e)


This will catch the ValueError and print out the error message.

To fix the issue, you can modify the paddings parameter to use the modified padding approach as described in my earlier response:

paddings = [1,1]
pad_tuple = [(0,0)] + [(_p,_p) for _p in paddings] + [(0,0)]
ivy.conv2d(image, kernels, strides, pad_tuple, data_format="NCHW", dilations=dilations)

**Comment by zhumakhan** [comment]
https://github.com/unifyai/ivy/pull/14627
