### ISSUE TITLE
Add `scipy.linalg` Linear Algebra Functions to SciPy Frontend

### ISSUE THREAD

**Issue by hmahmood24** [unifyai/ivy#14899]
Add [Linear Algebra Functions](https://docs.scipy.org/doc/scipy/reference/linalg.html) to SciPy Frontend

> Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

- [x] #14915
- [ ] solve
- [ ] solve\_banded
- [ ] solveh\_banded
- [ ] solve\_circulant
- [ ] solve\_triangular
- [ ] solve\_toeplitz
- [ ] matmul\_toeplitz
- [x] #15470
- [x] #14921
- [ ] lstsq
- [x] #14916
- [ ] pinvh
- [x] #14919
- [ ] khatri\_rao
- [x] #14917
- [x] #14918
- [ ] orthogonal\_procrustes
- [ ] matrix\_balance
- [ ] subspace\_angles
- [ ] bandwidth
- [ ] issymmetric
- [ ] ishermitian
- [ ] eig
- [ ] eigvals
- [ ] eigh
- [ ] eigvalsh
- [ ] eig\_banded
- [ ] eigvals\_banded
- [x] #14920
- [ ] eigvalsh\_tridiagonal
- [ ] lu
- [x] #20556
- [ ] lu\_solve
- [x] #14922
- [x] #14923
- [ ] diagsvd
- [ ] orth
- [ ] null\_space
- [ ] ldl
- [ ] cholesky
- [ ] cholesky\_banded
- [ ] cho\_factor
- [ ] cho\_solve
- [ ] cho\_solve\_banded
- [ ] polar
- [ ] qr
- [ ] qr\_multiply
- [ ] qr\_update
- [ ] qr\_delete
- [ ] qr\_insert
- [ ] rq
- [ ] qz
- [ ] ordqz
- [ ] schur
- [ ] rsf2csf
- [ ] hessenberg
- [ ] cdf2rdf
- [ ] cossin
- [ ] expm
- [x] #15494
- [ ] cosm
- [ ] sinm
- [ ] tanm
- [ ] coshm
- [ ] sinhm
- [ ] tanhm
- [ ] signm
- [ ] sqrtm
- [ ] funm
- [ ] expm\_frechet
- [ ] expm\_cond
- [ ] fractional\_matrix\_power
- [ ] solve\_sylvester
- [ ] solve\_continuous\_are
- [ ] solve\_discrete\_are
- [ ] solve\_continuous\_lyapunov
- [ ] solve\_discrete\_lyapunov
- [ ] clarkson\_woodruff\_transform
- [ ] block\_diag
- [ ] circulant
- [ ] companion
- [ ] convolution\_matrix
- [ ] dft
- [ ] fiedler
- [ ] fiedler\_companion
- [ ] hadamard
- [ ] hankel
- [ ] helmert
- [ ] hilbert
- [ ] invhilbert
- [ ] leslie
- [ ] pascal
- [ ] invpascal
- [ ] toeplitz
- [ ] tri

**Comment by paulaehab** [comment]
- [ ] #15470
