### ISSUE TITLE
Add `scipy.fft` Discrete Fourier Transforms Functions to SciPy Frontend

### ISSUE THREAD

**Issue by hmahmood24** [unifyai/ivy#14894]
Add [Discrete Fourier Transforms Functions](https://docs.scipy.org/doc/scipy/reference/fft.html#module-scipy.fft) to SciPy Frontend

> Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

- [x] #14911
- [x] #14912
- [x] #18002
- [ ] ifft2
- [ ] fftn
- [x] #20541
- [ ] rfft
- [ ] irfft
- [ ] rfft2
- [ ] irfft2
- [x] #20553
- [ ] irfftn
- [ ] hfft
- [ ] ihfft
- [ ] hfft2
- [ ] ihfft2
- [ ] hfftn
- [ ] ihfftn
- [x] #14913
- [x] #14914
- [ ] dctn
- [ ] idctn
- [ ] dst
- [ ] idst
- [ ] dstn
- [ ] idstn
- [ ] fht
- [ ] ifht
- [ ] fftshift
- [ ] ifftshift
- [ ] fftfreq
- [ ] rfftfreq

**Comment by mobley-trent** [comment]
- [ ] #18002
