### ISSUE TITLE
Fix ndarray.test_numpy_instance_deepcopy__

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#14929]
|   |   |
|---|---|
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5634798880"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by siddartha-10** [comment]
- [ ] #14929 

Hey Can you assign me this issue. Thank you.
