### ISSUE TITLE
Add Spectral Ops to PyTorch Frontend

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#15]
Add [Spectral Ops](https://pytorch.org/docs/stable/torch.html#spectral-ops) to PyTorch frontend:

- [ ] stft
- [ ] istft
- [ ] bartlett_window
- [ ] blackman_window
- [ ] hamming_window
- [ ] hann_window
- [ ] kaiser_window

**Comment by rrrajjjj** [comment]
stft #10503

**Comment by manavshah-boop** [comment]
- [ ] #15625

**Comment by ManoBharathi93** [comment]
#19487

**Comment by Juligee** [comment]
[ ] #21305

**Comment by Juligee** [comment]
[ ] #21309

**Comment by Enigmafiend** [comment]
- [ ] #21912

**Comment by Dharshannan** [comment]
stft #23482

**Comment by it-doesnt-matter** [comment]
- [ ] #23764

**Comment by it-doesnt-matter** [comment]
- [ ] #24252

**Comment by Muhammad-Hamza12** [comment]
#24983

**Comment by Ahmed-5** [comment]
- [ ] #26569

**Comment by Mickeyjey** [comment]
#26664

**Comment by gscerveira** [comment]
- [ ] #26711

**Comment by Mainakdeb** [comment]
https://github.com/unifyai/ivy/issues/26783

**Comment by AiSaurabhPatil** [comment]
- [ ] #26903
