### ISSUE TITLE
Add `paddle.tensor.attribute` Attribute Functions to Paddle Frontend

### ISSUE THREAD

**Issue by hmahmood24** [unifyai/ivy#15028]
Add [Attribute Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index\_en.html) to PaddlePaddle Frontend

> Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

- [x] #16142
- [x] #17094
- [x] #20197
- [x] #17169
- [x] #17163
- [x] #17164
- [x] #17095

**Comment by mobley-trent** [comment]
- [ ] #16142

**Comment by selvaraj-sembulingam** [comment]
#17094

**Comment by selvaraj-sembulingam** [comment]
#17095

**Comment by selvaraj-sembulingam** [comment]
#17163

**Comment by selvaraj-sembulingam** [comment]
#17164

**Comment by selvaraj-sembulingam** [comment]
#17168

**Comment by selvaraj-sembulingam** [comment]
#17169

**Comment by rajkumar-b** [comment]
- [ ] #19415

**Comment by rajkumar-b** [comment]
- [ ] #20197
