### ISSUE TITLE
Add `paddle.tensor.logic` Logical Functions to Paddle Frontend

### ISSUE THREAD

**Issue by hmahmood24** [unifyai/ivy#15036]
Add [Logical Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index\_en.html) to PaddlePaddle Frontend

> Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

- [x] #15415
- [x] #15416
- [x] #15417
- [x] #18953
- [x] #15419
- [x] #15418
- [x] #18214 
- [x] #16126
- [x] #15951
- [x] #16118
- [x] #16454
- [x] #20877
- [x] #16204
- [x] #16524
- [x] #15420
- [x] #16691
- [x] #16693
- [x] #15421
- [x] #16694

**Comment by KSANTHOSH200** [comment]
- [ ] #15784

**Comment by mobley-trent** [comment]
- [ ] #15951

**Comment by mobley-trent** [comment]
- [ ] #16118

**Comment by ahmadel1** [comment]
- [ ] #16126

**Comment by akshatvishu** [comment]
#16150

**Comment by iamwahid** [comment]
- [ ] #16204

**Comment by KevinUli** [comment]
- [ ] #16454

**Comment by DubeySandeep** [comment]
- [ ] #16515

**Comment by akshatvishu** [comment]
- [ ] #16524

**Comment by KevinUli** [comment]
- [ ] #16691

**Comment by KevinUli** [comment]
- [ ] #16693

**Comment by KevinUli** [comment]
- [ ] #16694

**Comment by samthakur587** [comment]
#18214

**Comment by AviralSingh-code** [comment]
#18953

**Comment by ogbanugot** [comment]
bitwise_not #19022

**Comment by Zamokuhle23** [comment]
#19791

**Comment by a0m0rajab** [comment]
- [ ] #19022

**Comment by a0m0rajab** [comment]
@hmahmood24 seems like all the functions here are closed and related to an issue, just wanted to make sure is this done? or is there any other issues/task to do?
