### ISSUE TITLE
Add Non-linear activation functions to `jax.lax` Frontend

### ISSUE THREAD

**Issue by Aarsh2001** [unifyai/ivy#1515]
Add [Non-linear activation](https://jax.readthedocs.io/en/latest/jax.nn.html) functions to JAX frontend:

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #2718 
- [x] #3126
- [x] #2963
- [x] #3030
- [x] #3130
- [x] #3136
- [x] swish
- [x] #3148
- [x] #2823 
- [x] #4260
- [x] #4261
- [x] #3720
- [x] #3469
- [x] #3536
- [x] #3477
- [x] #4919
- [x] #2936
- [x] #3149
- [x] #3015
- [x] #3146
- [x] #3539
- [x] #3178
- [x] #2899

**Comment by VikramxD** [comment]
- [ ] #2718

**Comment by VikramxD** [comment]
- [ ]  #2821

**Comment by VikramxD** [comment]
- [ ] #2823

**Comment by PatricYan** [comment]
- [ ] #2899.

**Comment by VikramxD** [comment]
- [ ] #2936

**Comment by VikramxD** [comment]
- [ ] #2963

**Comment by PatricYan** [comment]
> 



> * [ ]  [one_hot #2899](https://github.com/unifyai/ivy/issues/2899).

#2974

**Comment by PatricYan** [comment]
- [ ] #3015

**Comment by PatricYan** [comment]
- [ ] #3030

**Comment by Unevilicorn** [comment]
- [ ] #3126

**Comment by Unevilicorn** [comment]
- [ ] #3129

**Comment by Unevilicorn** [comment]
- [ ] #3130

**Comment by Unevilicorn** [comment]
- [ ] #3136

**Comment by sherry30** [comment]
- [ ] #3146

**Comment by sherry30** [comment]
- [ ] #3148

**Comment by sherry30** [comment]
- [ ] #3149

**Comment by NikoSokratous** [comment]
- [ ]  #3157

**Comment by NikoSokratous** [comment]
- [ ] #3159

**Comment by Unevilicorn** [comment]
- [ ] #3178

**Comment by VikramxD** [comment]
- [ ] #3235

**Comment by VikramxD** [comment]
@Aarsh2001 can you add elu function to this list ?

**Comment by Unevilicorn** [comment]
- [ ] #3469

**Comment by Unevilicorn** [comment]
- [ ] #3477

**Comment by Unevilicorn** [comment]
- [ ] #3536

**Comment by NikoSokratous** [comment]
- [ ] #3720

**Comment by kundakinte** [comment]
#4919

**Comment by saif-ashraf99** [comment]
#7384
