### ISSUE TITLE
Fix general_functions.test_tensorflow_eye

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#15328]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6374951013/job/17300174559"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by ConnectBhawna** [comment]
Hello @ivy-leaves 
Can you please assign me this issue. I would like to work on this.
Thanks

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
