### ISSUE TITLE
Add Universal functions for Numpy Frontend

### ISSUE THREAD

**Issue by Aarsh2001** [unifyai/ivy#1534]
Add [Universal functions](https://numpy.org/doc/stable/reference/ufuncs.html) for Numpy frontend:

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [ ] reduce
- [ ] accumulate
- [ ] reduceat
- [ ] outer
- [ ] at

**Comment by ddzhulaii** [comment]
accumulate #3897

**Comment by thevaliantthird** [comment]
- [ ] #6017

**Comment by robertsn808** [comment]
- [ ] #6500

**Comment by norman135** [comment]
- [ ] #7499

**Comment by dash96** [comment]
outer #7607
