### ISSUE TITLE
Fix jax_numpy_statistical.test_jax_numpy_median

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#15346]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5458225589/jobs/9933089162"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5458225589/jobs/9933089162"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5458225589/jobs/9933089162"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5458225589/jobs/9933089162"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5458225589/jobs/9933089162"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by ConnectBhawna** [comment]
Hii @ivy-leaves 
Can you please assign me this issue. I would like to work on this.
Thank you
