### ISSUE TITLE
Add Matrix methods for Numpy Frontend

### ISSUE THREAD

**Issue by Aarsh2001** [unifyai/ivy#1535]
Add [Matrix methods](https://numpy.org/doc/stable/reference/arrays.classes.html) for Numpy frontend:

- [ ] all 
- [ ] #2738 
- [x] #4308
- [x] #3261
- [x] #3425
- [ ] argsort
- [ ] astype
- [ ] choose
- [ ] clip
- [ ] compress
- [ ] conj
- [ ] conjugate
- [ ] copy
- [ ] cumprod
- [ ] cumsum
- [ ] diagonal
- [ ] fill
- [ ] flatten
- [ ] getA
- [ ] getA1
- [ ] getH
- [ ] getl
- [ ] getT
- [ ] getfield
- [ ] item
- [ ] itemset
- [ ] max 
- [ ] mean
- [ ] min
- [ ] newbyteorder
- [ ] nonzero
- [ ] partition
- [ ] prod
- [ ] ptp
- [ ] put
- [ ] ravel
- [ ] repeat
- [ ] reshape
- [ ] resize
- [ ] round
- [ ] searchsorted
- [ ] setfield
- [ ] sort
- [ ] squeeze
- [ ] std
- [x] #3562 
- [ ] swpaaxes
- [ ] take
- [ ] trace
- [ ] transpose
- [ ] var
- [ ] view

**Comment by daunsid** [comment]
#1654

**Comment by Mohammad-Talaat7** [comment]
#2534

**Comment by V-G-spec** [comment]
#2717

**Comment by aimaneharrak** [comment]
#2738

**Comment by anas0001** [comment]
#3012

**Comment by gunesevitan** [comment]
#3051

**Comment by Saivarunt** [comment]
[https://github.com/unifyai/ivy/issues/3238]#3238

**Comment by Saivarunt** [comment]
[issues/3238]

**Comment by Saivarunt** [comment]
#3238

**Comment by pptr3** [comment]
#3261

**Comment by roboFiddle** [comment]
#3425

**Comment by roboFiddle** [comment]
#3425 
#3426
#3427

**Comment by nuhpiskin** [comment]
#3554

**Comment by PatricYan** [comment]
- [ ] #3562

**Comment by JoelPendleton** [comment]
- [ ] #3600

**Comment by kimbring2** [comment]
- [ ] #4467

**Comment by martinoywa** [comment]
- [ ] #4586

**Comment by PatricYan** [comment]
- [ ] #4589
