### ISSUE TITLE
Add Array Instance methods for Numpy Frontend

### ISSUE THREAD

**Issue by Aarsh2001** [unifyai/ivy#1537]
Add [Array Instance methods](https://numpy.org/doc/stable/reference/arrays.ndarray.html#) for Numpy frontend:

- [ ] item
- [x] #4555
- [ ] itemset
- [ ] astype
- [x] copy
- [ ] view
- [ ] getfield
- [ ] fill
- [x] #6643
- [ ] resize
- [x] #4172 
- [x] #6711
- [ ] flatten
- [x] #6026
- [ ] squeeze
- [ ] take
- [ ] put
- [ ] repeat
- [ ] choose
- [x] #6485
- [ ] #6790
- [ ] partition
- [ ] argpartition
- [ ] searchsorted
- [ ] nonzero
- [ ] compress
- [ ] diagonal
- [ ] max
- [x] #2786
- [x] #5791
- [x] #5612
- [ ] ptp
- [ ] clip
- [ ] conj
- [ ] round
- [ ] trace
- [ ] #6620
- [ ] cumsum
- [x] #3945
- [ ] #6634
- [ ] std
- [ ] prod
- [x] #3781
- [ ] all
- [ ] any

**Comment by sampreet-arthi** [comment]
I would like to take this up

**Comment by Migabaj** [comment]
- [ ] #2786

**Comment by gunesevitan** [comment]
- [ ] #3051

**Comment by csowrab** [comment]
- [ ] #3304

**Comment by fkhjoy** [comment]
#3545

**Comment by sadra-barikbin** [comment]
- [] #3781

**Comment by jucamohedano** [comment]
#3942

**Comment by Harsimretsingh** [comment]
#3945

**Comment by ddzhulaii** [comment]
transpose #4172

**Comment by westrany** [comment]
tolist #4555

**Comment by acrulopez** [comment]
flatten #5607

**Comment by Oluwadurotimi10** [comment]
- [ ] #5612

**Comment by vohoanglong0107** [comment]
- [ ] #5791

**Comment by rotemgb** [comment]
- [ ] #5827

**Comment by Oluwadurotimi10** [comment]
Hello, @JLU-Neal I have created a Pull Request for adding argmin to NumPy ndarray frontend. Kindly review and let me know if I should make any changes. (https://github.com/unifyai/ivy/pull/5636)

**Comment by 0xcro3dile** [comment]
- [ ] 5882

**Comment by 0xcro3dile** [comment]
- [ ] #5882

**Comment by 0xcro3dile** [comment]
- [ ] #5883

**Comment by khadija267** [comment]
#5918

**Comment by khalilli** [comment]
- [ ] #6485

**Comment by jucamohedano** [comment]
- [ ] #6536

**Comment by khadija267** [comment]
var

**Comment by eswhy28** [comment]
- [ ]  #6643

**Comment by danielmunioz** [comment]
#6711

**Comment by Taciturny** [comment]
- [ ] #6790

**Comment by nkkrnkl** [comment]
The .copy array instance method for Numpy Frontend is completed

**Comment by nkkrnkl** [comment]
astype #6875

**Comment by nkkrnkl** [comment]
std #6875

**Comment by fspyridakos** [comment]
I have merged this list with #3607 and will be closing it, hopefully there will be less confusion about these lists.
