### ISSUE TITLE
Fix jax_numpy_math.test_jax_numpy_signbit

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#15397]
|   |   |
|---|---|
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5299360654/jobs/9592267862"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5299360654/jobs/9592267862"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5299360654/jobs/9592267862"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5299360654/jobs/9592267862"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5299360654/jobs/9592267862"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by KSANTHOSH200** [comment]
Can I work on this?
