### ISSUE TITLE
ivy.igamma

### ISSUE THREAD

**Issue by VitaliyStels** [unifyai/ivy#15490]
**Why should this be implemented?**
- 2+ of the native frameworks have this function
- it's needed for a Incomplete Gamma frontend function implementation

**Links to native framework implementations**
- [PyTorch](https://pytorch.org/docs/stable/special.html#torch.special.gammainc)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/math/igamma)

**Comment by AnnaTz** [comment]
Thanks for the suggestion! I have added it to the list.
