### ISSUE TITLE
Add Sparse functions for TensorFlow frontend

### ISSUE THREAD

**Issue by sreegandh804** [unifyai/ivy#1560]
Add [Sparse functions](https://www.tensorflow.org/api_docs/python/tf/sparse) for TensorFlow frontend:
- [ ] #3201
- [ ] cross_hashed
- [ ] eye
- [ ] fill_empty_rows
- [ ] from_dense
- [ ] map_values
- [ ] mask
- [ ] reduce_max
- [ ] reduce_sum
- [ ] reorder
- [ ] reset_shape
- [ ] retain
- [ ] segment_sqrt_n
- [ ] sparse_dense_matmul
- [ ] to_dense
- [ ] to_indicator

**Comment by Lancelot03** [comment]
- [ ]  #3212

**Comment by djl11** [comment]
closing temporarily, until ivy supports sparse arrays.
