### ISSUE TITLE
Add Activation functions for TensorFlow frontend

### ISSUE THREAD

**Issue by sreegandh804** [unifyai/ivy#1569]
Add [Activation functions](https://www.tensorflow.org/api\_docs/python/tf/keras/activations#functions) for TensorFlow frontend:

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [x] #2615 
- [x] #2511
- [x] #4504 
- [x] #5773
- [x] #5387
- [x] #5521
- [x] #6062
- [x] #5245
- [x] #5388
- [ ] #25851
- [x] #5329
- [x] #5328
- [x] #5383
- [x] #5382
- [x] #5381
- [x] #5342

> The main file paths where these functions are likely to be added are: 
> - `ivy/functional/frontends/tensorflow/activations.py`
> - `ivy\_tests/test\_ivy/test\_frontends/test\_tensorflow/test\_activations.py`
> - `ivy/functional/backends/tensorflow/activations.py`
> - `ivy/functional/frontends/tensorflow/keras/activations.py`
> - `ivy/functional/ivy/activations.py`
> - `ivy/functional/ivy/data\_type.py`

**Comment by Bobbyorr007** [comment]
- [ ] #1858

**Comment by Bobbyorr007** [comment]
- [ ] #1859

**Comment by Bobbyorr007** [comment]
- [ ] #1860

**Comment by FrankShi9** [comment]
- [ ] #2511.

**Comment by Bmackgold** [comment]
#2612

**Comment by ntg2208** [comment]
#2615

**Comment by umarfb** [comment]
#4504

**Comment by suvadityamuk** [comment]
[ ] #5245

**Comment by hirwa-nshuti** [comment]
[ ] #5328

**Comment by hirwa-nshuti** [comment]
- [ ] #5329

**Comment by hirwa-nshuti** [comment]
- [ ] #5381

**Comment by hirwa-nshuti** [comment]
- [ ] #5382

**Comment by hirwa-nshuti** [comment]
- [ ] #5383

**Comment by hmahmood24** [comment]
- [ ] #5387

**Comment by hmahmood24** [comment]
- [ ] #5388

**Comment by AdityaNikhil** [comment]
Can I contribute to this as a part of hacktoberfest?

**Comment by hirwa-nshuti** [comment]
Hi @AdityaNikhil
Yes sure you're welcome to contribute as part of hacktoberfest🙂

**Comment by anaghazachariah** [comment]
relu #5245

**Comment by Mina-88** [comment]
- [ ] #5521

**Comment by anaghazachariah** [comment]
tanh #5342

**Comment by ItIsUday** [comment]
serialize #5742

**Comment by oscar1marte** [comment]
- [ ] #5773

**Comment by MahmoudAshraf97** [comment]
new task for get started #6062

**Comment by oscar1marte** [comment]
- [ ] #6190

**Comment by MuhHanif** [comment]
#7392

**Comment by DevMachTech** [comment]
Serialized #7392

**Comment by maher-mohsen** [comment]
- [ ] ##7392

**Comment by waqaarahmed** [comment]
- [ mish] #1890

**Comment by SainiAditya1** [comment]
Hey I want to work on this issue as I have upwork contract.

**Comment by hainesdata** [comment]
https://github.com/unifyai/ivy/issues/22145

**Comment by Nik-code** [comment]
Added serialize https://github.com/unifyai/ivy/pull/23432

**Comment by eyabriki** [comment]
<serialize> #25684

**Comment by eyabriki** [comment]
<exponential> #25685

**Comment by abdul-rehman18** [comment]
#25772

**Comment by paulaehab** [comment]
Hello @eyabriki  I am very sorry @Nik-code had already made the function and he just forget to add issue with function name , also it was my fault that I didn't get it I am sorry for that could you pick another function and again sorry for this mistake hope you accept my apologizes

**Comment by Nik-code** [comment]
#25851
