### ISSUE TITLE
Add Layers functions for TensorFlow frontend

### ISSUE THREAD

**Issue by sreegandh804** [unifyai/ivy#1570]
Add [Layers functions](https://www.tensorflow.org/api_docs/python/tf/keras/layers#functions) for TensorFlow frontend:

- [ ] Input 
- [ ] add
- [ ] average
- [ ] #4183
- [ ] deserialize 
- [ ] dot
- [x] #4734
- [ ] #5016
- [ ] multiply
- [ ] serialize
- [ ] subtract

**Comment by ToobaJamal** [comment]
#2729

**Comment by ToobaJamal** [comment]
#2857

**Comment by LeumasA** [comment]
#2901

**Comment by rahulsnkr** [comment]
- [ ] #3009

**Comment by bicycleman15** [comment]
- [ ] #3186

**Comment by abou704** [comment]
#3287

**Comment by Aditya-Komaravolu** [comment]
@sreegandh804 I want to work on cosine_similarity. I have a doubt. Should the code for cosine similarity be written in [ivy/functional/frontends/tensorflow/metrics.py](https://github.com/Aditya-Komaravolu/ivy/blob/instance-addition-branch/ivy/functional/frontends/tensorflow/metrics.py) ?

**Comment by Aditya-Komaravolu** [comment]
- [ ] cosine_similarity #4521

**Comment by Jordan-Madden** [comment]
MAE #4668

**Comment by Jordan-Madden** [comment]
maximum #4734

**Comment by horair** [comment]
minimum

**Comment by horair** [comment]
minimum #5016
