### ISSUE TITLE
Fix ndarray.test_numpy_instance_tofile__

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#15723]
|   |   |
|---|---|
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5538552236/jobs/10108602079"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5538552236/jobs/10108602079"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5538552236/jobs/10108602079"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5538552236/jobs/10108602079"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5538552236/jobs/10108602079"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by rarisenpai** [comment]
#15858
