### ISSUE TITLE
ivy.lu_solve

### ISSUE THREAD

**Issue by moezAhmad** [unifyai/ivy#16069]
**Why should this be implemented?**
- 3+ of the native frameworks have this function
- it's needed for a complex/long frontend function implementation

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.linalg.lu_solve.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.linalg.lu_solve.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/lu_solve)
- [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_solve.html)

**Comment by AnnaTz** [comment]
I added it to the list. Thanks for the suggestion!
