### ISSUE TITLE
[Bug]: Numbering list in the documentation rendered as a paragraph

### ISSUE THREAD

**Issue by trgiangdo** [unifyai/ivy#16087]
### Bug Explanation

In https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html#maximizing-usage-of-native-functionality, several numbering lists are rendered as paragraph.

<img src="https://github.com/unifyai/ivy/assets/37588363/3ede186f-6f9f-4628-b8b6-963512790cef" alt="3ede186f-6f9f-4628-b8b6-963512790cef" width="75%">

### Steps to Reproduce Bug

It's in the [live doc](https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html#maximizing-usage-of-native-functionality).

### Environment

It's in the [live doc](https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html#maximizing-usage-of-native-functionality).

### Ivy Version

dev

**Comment by MuhammadNizamani** [comment]
I have create PR this issue
