### ISSUE TITLE
 "SyntaxError: keyword argument repeated"

### ISSUE THREAD

**Issue by rubada** [unifyai/ivy#16220]
### Bug Explanation

In the test_layer.py, path "[ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py)", the test_dct function has the  on_device=on_device keyword argument repeated twice in the helpers.test_function

### Steps to Reproduce Bug

It is on [ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py)

### Environment

In Ivy repository in github

### Ivy Version

None

**Comment by Daniel4078** [comment]
Thanks for pointing that out! I fixed it here: https://github.com/unifyai/ivy/commit/cb40ead37837c13852ad39ab4c985f7e196c9355
