### ISSUE TITLE
irfft2

### ISSUE THREAD

**Issue by XinyuanWang283** [unifyai/ivy#16393]

**Comment by rajveer43** [comment]
hey @XinyuanWang283 I am already working on this rfft2 kindly choose another issue.

**Comment by XinyuanWang283** [comment]
okay! are you working on the irfft2?  

> hey @XinyuanWang283 I am already working on this rfft2 issue #16357 . kindly choose another issue.

**Comment by rajveer43** [comment]
Its my Bad, I apologize, you can carry on that funciton
