### ISSUE TITLE
Creating Logical Functions to PaddlePaddle Frontend (paddle.tensor.logic)

### ISSUE THREAD

**Issue by Saumyadeepm** [unifyai/ivy#16409]
_Created Rest of The Functions(Logical_Functions) as given below into Paddle Frontend (paddle.tensor.logic)_

- [x] #16411
- [x] #16412 
- [x] #16413 
- [x] #16414 
- [x] #16415 
- [x] #16416 
- [x] #16417

**Comment by Saumyadeepm** [comment]
Now what do I need to do next ?

**Comment by AnnaTz** [comment]
Hi @Saumyadeepm, the `Suggestion` issues are supposed to be used to recommend adding a new function to Ivy API. 
To implement frontend functions you are expected to use the existing ToDo list issues composed by our team. In this case, please refer to this https://github.com/unifyai/ivy/issues/15036.

**Comment by Saumyadeepm** [comment]
Thats what I did created Rest of the Logical functions with respect to the ToDo List
