### ISSUE TITLE
ivy.<triangular>

### ISSUE THREAD

**Issue by sasori-s** [unifyai/ivy#16472]
**Why should this be implemented?**
- 3+ of the native frameworks have this function
- it's an NN-related function and should be as efficient as possible
- it's needed for a complex/long frontend function implementation

**Links to native framework implementations**
- [Jax](<FUNC_URL_DOCS>)
- [PyTorch](<FUNC_URL_DOCS>)
- [TensorFlow](<FUNC_URL_DOCS>)
- [NumPy](<FUNC_URL_DOCS>)

**Comment by sasori-s** [comment]
@AnnaTz  Hi, I can not find the page where I created this issue. Can you please provide me with the link to the page?

**Comment by sasori-s** [comment]
@AnnaTz   Hi, I can not find the page where I created this issue. Can you please provide me with the link to the page?

**Comment by AnnaTz** [comment]
> @AnnaTz Hi, I can not find the page where I created this issue. Can you please provide me with the link to the page?

Hi @sasori-s, which page do you mean? This one https://github.com/unifyai/ivy/issues/new/choose ?

**Comment by sasori-s** [comment]
@AnnaTz  Thanks for replying. I did find the page. . Please check out this page if this page contains the same triangular function https://github.com/unifyai/ivy/issues/1530

**Comment by sasori-s** [comment]
@AnnaTz  I am confused about this. I want to do the frontends part. The issue number is https://github.com/unifyai/ivy/issues/16554.  Please assign me to this. 
Also the main question is I can not find the triangular in ivy API

**Comment by AnnaTz** [comment]
I have also added `triangular` to our Experimental API ToDo list since we don't already have an ivy function with this functionality. You could either wait until someone takes on the task to implement it, or implement the frontend function using a composition of existing ivy functions.
