### ISSUE TITLE
ivy.dot

### ISSUE THREAD

**Issue by xoiga123** [unifyai/ivy#16493]
**Why should this be implemented?**
- 5 of the native frameworks have this function
- it's an NN-related function and should be as efficient as possible
- it's needed for a complex frontend function implementation (can do up to 5 different things depending on the dimension of inputs)

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.dot.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.dot.html)
- [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [PaddlePaddle](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/dot_en.html)
- [MXNet](https://mxnet.apache.org/versions/master/api/python/docs/api/np/generated/mxnet.np.dot.html)

**Note**:
- If this suggestion is approved, I would love to implement this myself.
- The current frontend for `jax.numpy.dot` mistakenly uses `matmul` but the accompanying test `test_jax_numpy_dot` has too narrow arguments generation, so it still passes.

**Comment by AnnaTz** [comment]
Hi, doesn't `ivy.multi_dot` fully cover the functionality of `dot`?

**Comment by AnnaTz** [comment]
You're right, I will add `dot` to our list. Thanks for looking into this!
