### ISSUE TITLE
<Function_Name>

### ISSUE THREAD

**Issue by zuhair997** [unifyai/ivy#16530]

**Comment by MuhammadNizamani** [comment]
@zuhair997  sir mention the name of function which you are going to implement in paddle.tensor.tensor.Tensor. Look at this issue https://github.com/unifyai/ivy/issues/16552 in which I am going to implement erf. so kindly make it right

**Comment by zuhair997** [comment]
Sir can you share some examples that how I have to mention because I try
alot and spend alot of time but don't know how to add and mention.
