### ISSUE TITLE
 triangular_solve

### ISSUE THREAD

**Issue by AbdulKhaliq293** [unifyai/ivy#16579]

**Comment by rishabgit** [comment]
Hi @AbdulKhaliq293, someone else seems to have started working on this much earlier but forgot to link their work correctly - https://github.com/unifyai/ivy/pull/16482
Please feel free to pick any other open issues, sorry about the inconvenience!

**Comment by AbdulKhaliq293** [comment]
I am also stuck in testing but no problem i will close the issue.
