### ISSUE TITLE
Want to contribute 💘 unsure about usefulness😕 

### ISSUE THREAD

**Issue by tornikeo** [unifyai/ivy#169]
Just as the title says. I would like to contribute to this fledgling ML framework. But, I simply can't see how this is going to become useful to people who already use pytorch, tensorflow, JAX or MXNet. 

I can imagine two scenarios where yet another ML framework could be used:

- First, imagine a seasoned PyTorch dev who also had to work with tensorflow (e.g. for deployment) and played around with JAX (out of curiosity). On any given working day, what existing problem could possibly compel this dev to seek out a unified ML framework, when the tried-and-true torch is just an `import torch` away?
-  Second, imagine a researcher testing a wholly new kind of network topology. Suppose for that, he or she is using JAX, given its finegrained control over ops. Now, what would compel this person to use IVY instead?
 
Last but not least, how does IVY compare with ONNX? I would like to know, since ONNX is frequently used in order to bridge the gap between popular ML frameworks.

Please don't take these questions as undue criticism. I'm more than happy to contribute, however, I believe that if this framework is to succeed, these kinds of questions should be answered.

**Comment by Ishticode** [comment]
When building a new technology, simply builiding it in Ivy to begin with removes the hassle of replicating it in jax, torch etc. and ivy can generate computational graph (guranteed to be same as if created in the user's chosen framework) for that technology geting rid of any overhead or inconsistencies.

**Comment by djl11** [comment]
As helpfully explained by @Ishticode, the best place to see our motivation is currently the [blog series](https://medium.com/@unifyai/the-unified-ml-framework-5bf99774d8ab). However, the README, website, and other docs will soon be updated to more closely follow the narrative on the blog series. I'll then respond with some more details to this useful issue, which I'll leave open to continue such discussions.
