### ISSUE TITLE
ivy.nanprod

### ISSUE THREAD

**Issue by Gwyn-The-Human** [unifyai/ivy#17026]
**Why should this be implemented?**
- it's needed for a complex/long frontend function implementation. (https://github.com/unifyai/ivy/issues/17019) 

**Links to native framework implementations**
- [Jax] (https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.nanprod.html#jax.numpy.nanprod)

**Comment by AnnaTz** [comment]
Thanks for the suggestion! I have added this to our list.
