### ISSUE TITLE
ivy.matmul 1-D inputs --> inconsistent results 

### ISSUE THREAD

**Issue by Ishticode** [unifyai/ivy#1705]
**To reproduce the results, one will need to use [this version](https://github.com/unifyai/ivy/tree/f8d1849c46f50438c83a9f7708c39a1aa79aa070) of ivy before the fixes were applied.**

Here are the results of applying matmul on two 1-D arrays. (code at the end)
```
# Ivy
jax ivy: ivy.array(43)
numpy ivy: 43
torch ivy: ivy.array(43)
tensorflow ivy: ivy.array(12)

# original fw
jax: 43
numpy: 43
torch: tensor(43)
tensorflow: tf.matmul requires inputs rank >1
```
The first block is results using `ivy.matmul` with each respective backend. The inputs are 1-D arrays with values `array([2, 3, 4])` and `array([6, 5, 4])`. According to array api standard a 0-dimensional array should be returned. `ivy_jax` and `ivy_torch` work as expected but numpy returns a scalar and tensorflow has a totally different value.
The second block returns results using the actual frameworks without ivy wrappings.

There are two problems:
1. Ivy with numpy returns a scalar where it should be an array as per standard
2. Ivy with tensorflow backend returns a wrong value.

Here is the code generating the results above. A bit repetitive. Mostly copilot generated.

```python
import ivy
import numpy as np
import torch
import jax.numpy as jnp


x = np.array([2, 3, 4])
y = np.array([6, 5, 4])
ivy.set_backend("jax")
jx = ivy.array(x)
jy = ivy.array(y)
print()
print("jax ivy:", ivy.matmul(jx,jy))
ivy.unset_backend()


ivy.set_backend("numpy")
nx = ivy.array(x)
ny = ivy.array(y)
print()
print("numpy ivy:", ivy.matmul(nx,ny))
ivy.unset_backend()


ivy.set_backend("torch")
tx = ivy.array(x)
ty = ivy.array(y)
print()
print("torch ivy:", ivy.matmul(tx,ty))
ivy.unset_backend()

ivy.set_backend("tensorflow")
tfx = ivy.array(x)
tfy = ivy.array(y)
print()
print("tensorflow ivy:", ivy.matmul(tfx, tfy))
ivy.unset_backend()

print()
print("jax:", jnp.matmul(x, y))
print("numpy:", np.matmul(x, y))
print("torch:", torch.matmul(torch.tensor(x), torch.tensor(y)))
print("tensorflow: tf.matmul requires inputs rank >1")

```

**Comment by Ishticode** [comment]
Tensorflow wrong/different values are fixed in [this commit](https://github.com/unifyai/ivy/commit/a332482f5b0caf9b184e792e0ba69216618fd2af).

**Comment by Ishticode** [comment]
Numpy returning a scalar has been fixed in [this commit](https://github.com/unifyai/ivy/commit/011c963a204c8be8ff327ff4efb5c0221fb79a4c).

**Comment by Ishticode** [comment]
The results are as expected now:
```
# Ivy
jax ivy: ivy.array(43)
numpy ivy: ivy.array(43)
torch ivy: ivy.array(43)
tensorflow ivy: ivy.array(43)

# original
jax: 43
numpy: 43
torch: tensor(43)
tensorflow: tf.matmul requires inputs rank >1
```

**Comment by Ishticode** [comment]
The numpy problem was solved only under the specific function `matmul` in the numpy backend. 
But the deeper issue is the function `to_ivy` doesn't turn scalars into ivy arrays as per docstring and also apparent in the logic of inner function `_ivy_array`. This might be an issue to be addressed where the standard requires an array return but the backend return a scalar for example, the `@to_ivy_arrays_and_back` decorator might not do the job in that case. 
But this doesn't sit with the fact that the jax backend did return a scalar too which was converted to an ivy.array anyway as clear from the results in the very first comment.
Although the numpy issue was was fixed. **It remains to be shown why the jax returned scalar was converted and the numpy one wasn't**

**Comment by Ishticode** [comment]
About why the Array API tests were passing.
The following logic in `test_matmul` is meant to check for the problem at hand (Two 1-D entries to matmul)
```python
    if len(x1.shape) == len(x2.shape) == 1:
        assert res.shape == ()
```

however, a scalar value returned by `np.matmul` of type `numpy.int64` also has this attribute too. 
as seen by the code
```python
res = np.matmul(x, y)
print("type:", type(res))
print("Has zero dimension: ", res.shape==())
print("is a scalar: ", np.isscalar(res))
```
 which prints

```
type: <class 'numpy.int64'>
Has zero dimension:  True
is a scalar:  True
```

but is not a zero dimensional array as clear from this table from [this numpy documentation page](https://numpy.org/doc/stable/reference/generated/numpy.isscalar.html) as in that case, `np.isscalar` above should've been false. 

![image](https://user-images.githubusercontent.com/53497039/176970725-bf4611d0-9bc6-44bd-aaf5-9ea4b99c556b.png)

The conclusion is that it is possible to have `True` return for `result.shape == ()` even when the result is not a zero dimensional array. So this assertion is insufficient check for the result being zero-dimensional array and allows scalars to pass through.

**Comment by djl11** [comment]
This is likely not a problem with the array test suite itself, but rather an issue with NumPy not adhering to the standard. For example, the standard probably makes it clear that `assert res.shape == ()` should not evaluate to `True` for scalars. I think it is known that NumPy does not adhere to the standard, and there is a dedicated namespace for the Array API Standard compliant version of NumPy, under `numpy.array_api` or something similar. Thanks for digging into this though, very interesting to see why the Array API tests were passing! Given that your commits have fixed this problem, I'll close this for now :)
