### ISSUE TITLE
ivy.elementwsie.frac

### ISSUE THREAD

**Issue by MuhammadNizamani** [unifyai/ivy#17230]
According to Todo list #15115, the task is to implement the frac function in paddle.tensor.tensor.Tensor. However, before implementing frac in paddle.tensor.tensor.Tensor, we need to first implement the frac function in ivy/functional/ivy/elementwise.py.

**Comment by AnnaTz** [comment]
Thanks for the suggestion!
I added `modf` to the list. [This](https://numpy.org/doc/stable/reference/generated/numpy.modf.html) is the corresponding numpy function. It returns the fractional and integral parts of an array, element-wise.
