### ISSUE TITLE
bitwise_and

### ISSUE THREAD

**Issue by samthakur587** [unifyai/ivy#17637]
implementing the bitwise and for paddle frontend

**Comment by alovega** [comment]
Hello @samthakur587 I had set this up earlier on the list of tasks but forgot to comment please do not do this task if possible

**Comment by alovega** [comment]
bitwise_and #17630

**Comment by alovega** [comment]
Could yu let me pick the other one, bitwise_or/bitwise_not

**Comment by samthakur587** [comment]
Hey @alovega 
There is lots of issue in ivy to solve and many Todo subtask to do you can pick any of them.

Thank you

**Comment by alovega** [comment]
Yeah, no worries I picked a new one
