### ISSUE TITLE
 Incorrect Syntax in build_submodules.py

### ISSUE THREAD

**Issue by Alex19578** [unifyai/ivy#17849]
I noticed that there is an issue with the syntax in the build_submodules.py file. The print statement is `missing parentheses`, causing a syntax error when running the script.

Current Code
```
print cmd
print "cannot create directory {}".format(dir)
print 'Cannot find a suitable version of Visual Studio (require 10.0-15.0 or 2017 or 2019)'
print "submodules/z3 not found. try 'git submodule update; git submodule update'"

```

Expected Code:
```
print(cmd)
print ("cannot create directory {}".format(dir))
print ('Cannot find a suitable version of Visual Studio (require 10.0-15.0 or 2017 or 2019)')
print ("submodules/z3 not found. try 'git submodule update; git submodule update'")
```

**Comment by SHUBHAPRIYA95** [comment]
print(cmd)
print("cannot create directory {}".format(dir))
print('Cannot find a suitable version of Visual Studio (require 10.0-15.0 or 2017 or 2019)')
print("submodules/z3 not found. try 'git submodule update; git submodule update'")
print statements require parentheses around the arguments. Additionally, for consistency, it's better to use either single or double quotes consistently for string literals.

**Comment by SHUBHAPRIYA95** [comment]
print(cmd)
print("cannot create directory {}".format(dir))
print('Cannot find a suitable version of Visual Studio (require 10.0-15.0 or 2017 or 2019)')
print("submodules/z3 not found. try 'git submodule update; git submodule update'")
print statements require parentheses around the arguments. Additionally, for consistency, it's better to use either single or double quotes consistently for string literals.

**Comment by AnnaTz** [comment]
Hi @Alex19578, please open a `Bug Report` issue for this. `Next Release`/`Suggestion` issues are for suggesting new functions for our API.
