### ISSUE TITLE
[Feature Request]: Add `mlc-llm` to the support list

### ISSUE THREAD

**Issue by tigerinus** [unifyai/ivy#17886]
**Is your feature request related to a problem? Please describe.**
We are currently using MLC-LLM (https://mlc.ai/mlc-llm/) in our AI project. It already provides a way to transcompile regular models into MLC code. Due to broader scope of framework support by Ivy, I'd like to request adding MLC to the support list of Ivy.

**Describe the solution you'd like**
I'd like to pick any model that's built for PyTorch/JAX and use it in MLC framework.

**Describe alternatives you've considered**
Not really.

**Additional context**
I could misunderstand the goal of Ivy. I assume it's goal is to bring models/frameworks/processes to one-stop.

**Comment by djl11** [comment]
Thanks for pointing this out @tigerinus Super interesting proposal! I hadn't heard of this project before, but then looking at the star growth, I'm not surprised why, it's really exploded onto the scene 😅 @vaatsalya123 do you think this might make sense as another deployment target? It's by some of the creators of ApacheTVM, with significant contributions from the OctoML team as well. We'll definitely keep it on our radar, and we'll keep this issue open until we've built an integration. Thanks again @tigerinus!
