### ISSUE TITLE
Add Utilities to PyTorch Frontend

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#18]
Add [Utilities](https://pytorch.org/docs/stable/torch.html#utilities) to PyTorch frontend:

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #7829
- [x] #5197
- [x] #10559

**Comment by KevinUnadkat** [comment]
result_type #7803

**Comment by KevinUnadkat** [comment]
#7829

**Comment by AnnaTz** [comment]
- [ ] #7829

**Comment by KevinUnadkat** [comment]
#10559
