### ISSUE TITLE
ivy.multivariate_normal

### ISSUE THREAD

**Issue by akgokce** [unifyai/ivy#18188]
**Why should this be implemented?**
- 3+ of the native frameworks have this function
- it's needed for a complex/long frontend function implementation

**Links to native framework implementations**
- [Jax](<https://jax.readthedocs.io/en/latest/_autosummary/jax.random.multivariate_normal.html>)
- [PyTorch](<https://pytorch.org/docs/stable/distributions.html#multivariatenormal>)
- [TensorFlow](<https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalDiag>)
- [NumPy](<https://numpy.org/doc/stable/reference/random/generated/numpy.random.multivariate_normal.html#numpy.random.multivariate_normal>)

**Comment by AnnaTz** [comment]
Thanks for the suggestion, I'll add this to our list!
