### ISSUE TITLE
searchsorted

### ISSUE THREAD

**Issue by diksha-shrivastava13** [unifyai/ivy#18267]
#15044

**Comment by Aayushkumr** [comment]
Hey, I want to work on the issue #18268 can you please assign it to me.

**Comment by diksha-shrivastava13** [comment]
Hi @Aayushkumr! That PR is almost completed and minimal changes, if any, would need to be added. If you want to work on any of the tasks listed in #15044, the steps to take up a subtask would be:

1. Set up your environment as instructed in https://unify.ai/docs/ivy/overview/contributing/setting_up.html
2. Create an issue with the "new issue" button on the right on https://github.com/unifyai/ivy/issues/15044 with the title as just the function name
3. Go back to https://github.com/unifyai/ivy/issues/15044 and comment "- [ ] #issue_number" linking the issue you created in 2.
4. Create a new branch on your fork after which you can start working on the function and create a PR once you're good to go.

Happy contributing!
Do let me know if you have any questions and you can also join the discord channel here to engage with the community: https://discord.com/invite/sXyFF8tDtm

**Comment by Aayushkumr** [comment]
Alright, Thanks Diksha for guiding me.
