### ISSUE TITLE
silu

### ISSUE THREAD

**Issue by sachelsout** [unifyai/ivy#18946]

**Comment by Lucifer60** [comment]
I have implemented the code in paddle/nn/functional/activation.py. However, there is something wrong when I commit.


An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://github.com/psf/black/': Failed to connect to github.com port 443: Connection timed out
Check the log at /home/qxy/.cache/pre-commit/pre-commit.log

Is there any methods to skip the pre-commit process?

**Comment by Lucifer60** [comment]
Close PR #18977
