### ISSUE TITLE
ivy.lgamma

### ISSUE THREAD

**Issue by marccgrau** [unifyai/ivy#18985]
**Why should this be implemented?**
- 3+ of the native frameworks have this function
- no implementation of the gamma function available in ivy, only gamma distribution available

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.lgamma.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.lgamma.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/math/lgamma)
- [Paddle](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/lgamma_en.html)

**Comment by AnnaTz** [comment]
Thanks for the suggestion! I have added this to our ToDo list.
