### ISSUE TITLE
Fix paddle_tensor.test_paddle_instance_asinh

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#19047]
|   |   |
|---|---|
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5508914326"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5508914326"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5508914326"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5508914326"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5508914326"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by MuhammadNizamani** [comment]
@ivy-leaves can you tell me can resolve this issue give me any hint or point at any direction.
This function as written by me and I have check it on locally it is working fine.
