### ISSUE TITLE
compute.v1.instance

### ISSUE THREAD

**Issue by HopeFloats99** [unifyai/ivy#1926]
I'd say that yes, this app is still maintained! Even though it's not likely to receive big new features, there is interest in keeping it alive.

@maniac103 Maybe this is a good time to release a new version of the app, after merging the remaining fixup PRs?
We have months of unreleased changes that would be great to make available to the public.

**Comment by HopeFloats99** [comment]
http://www.apache.org/licenses/LICENSE-2.0

**Comment by jkeane508** [comment]
Hi, I think this issue was a mistake 😀
