### ISSUE TITLE
[Bug]: Wrong display in homepage

### ISSUE THREAD

**Issue by stefenson** [unifyai/ivy#19294]
### Bug Explanation

![30c3507b-59e7-4041-a180-f060956b3836](https://github.com/unifyai/ivy/assets/17709715/69384926-6378-47a5-bf2b-f1b9706f6d63)

### Steps to Reproduce Bug

view the homepage

### Environment

emmmm......

### Ivy Version

no, not the framework

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

well...

**Comment by bipinKrishnan** [comment]
Thanks for raising this @shephinphilip , closing the issue since this is fixed now :slightly_smiling_face:
