### ISSUE TITLE
Setting Up: GitHub Codespaces

### ISSUE THREAD

**Issue by AhmadAli016** [unifyai/ivy#19307]
### Path

https://unify.ai/docs/ivy/overview/contributing/setting_up.html#setting-up

### Section

GitHub Codespaces

### Actual Behavior

The screenshots used to guide the setting up of GitHub Codespaces are old. The folder names have been updated creating confusion while setting up GitHub Codespaces.
Besides this, I have been trying to set up codespaces as stated in the documentation but I have failed many times as I am unable to run array API tests by following the documentation.

### Expected Behavior

Update the documentation which when followed as stated, will create a working GitHub Codespace for contributors to work on.

### Screenshots

![image](https://github.com/unifyai/ivy/assets/114653743/0462e928-eb35-4144-893e-dffe758e5720)
Lasted Repo create from ivy development environment (image)
![image](https://github.com/unifyai/ivy/assets/114653743/056941ee-b665-4e02-9fd6-c33c0cfba642)
Screenshot from Setting Up: GitHub Codespaces

**Comment by hirwa-nshuti** [comment]
Currently, there is a known issue in running the array API tests locally which we are looking into😊
Thanks for flagging this🫡
