### ISSUE TITLE
[Documentation]: Ivy.to_native() function expects ivy.Array object, but accepts torch.Tensor object in documentation

### ISSUE THREAD

**Issue by shephinphilip** [unifyai/ivy#19530]
### Path

 https://unify.ai/docs/ivy/overview/design/building_blocks.html

### Section

Building Blocks

### Actual Behavior

The documentation for the Ivy.to_native() function states that it expects to be passed an Ivy.Array object. However, the code snippet in the documentation passes a Torch.Tensor object to the function. This results in an error, as the Ivy.to_native() function cannot convert Torch.Tensor objects to native objects.

### Expected Behavior

The documentation should be updated to state that the Ivy.to_native() function only works with Ivy.Array objects. Additionally, the code snippet in the documentation should be updated to pass an Ivy.Array object to the function.

### Screenshots

![Screenshot (56)](https://github.com/unifyai/ivy/assets/132887262/7fe0d524-c2b6-4238-995b-2d6b927701f4)

**Comment by Ookamice** [comment]
See: https://github.com/unifyai/ivy/pull/19531#issuecomment-1639794237
