### ISSUE TITLE
Amax missing in paddle math.py

### ISSUE THREAD

**Issue by sroycho4** [unifyai/ivy#19541]
### Bug Explanation

It says amax is present in math.py (Paddle frontend) but it is actually not present as the implementation was removed due to a bug. Kindly mark it as not done so I can take it up.

### Steps to Reproduce Bug

N/A

### Environment

PyCharm CE + Docker

### Ivy Version

Latest

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by AnnaTz** [comment]
Hi @sroycho4, I have re-opened the `amax` subtask issue. Feel free to link your PR there. Thanks!
