### ISSUE TITLE
lstsq

### ISSUE THREAD

**Issue by MuminAhmadKhan** [unifyai/ivy#19544]
Subtask of Add Linear Algebra functions for TensorFlow frontend #1546

**Comment by BranoKusik** [comment]
Hi 
Can I complete this task?

**Comment by MuminAhmadKhan** [comment]
Hi
I have chosen this task for myself.
Please read the doc and chose a task for yourself.
https://unify.ai/docs/ivy/overview/contributing/open_tasks.html
