### ISSUE TITLE
scatter_add

### ISSUE THREAD

**Issue by aryaman82** [unifyai/ivy#19562]

**Comment by aryaman82** [comment]
the task wasn't taken so i put a sub-task , I'm sorry were you working on this

**Comment by 00umar** [comment]
What's your say?

**Comment by aryaman82** [comment]
It's yours, but can you keep me in the loop , im rather invested in this now

**Comment by 00umar** [comment]
Have you worked on it?

**Comment by 00umar** [comment]
Here's my email.

***@***.***
