### ISSUE TITLE
Add `lgamma` to numpy backend

### ISSUE THREAD

**Issue by akshatvishu** [unifyai/ivy#19630]
`Numpy` currently lacks a native implementation of the `lgamma` function, which computes the logarithm of the absolute value of "Gamma(x)" element-wise. Therefore, I propose adding this functionality to `numpy` using a compositional approach until a native implementation becomes available.

**Comment by aadya940** [comment]
I can work on this if anyone has no objection?

**Comment by akshatvishu** [comment]
@aadya940  Thanks for showing interest but I am currently working on it!
