### ISSUE TITLE
reptile_step

### ISSUE THREAD

**Issue by suryathecreator** [unifyai/ivy#1969]

**Comment by 1Doomdie1** [comment]
Please choose a function from that issue and name this issue accordingly.

**Comment by 1Doomdie1** [comment]
Can you please mention this issue where you took this function from?

**Comment by suryathecreator** [comment]
Done.

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would liketo continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues
