### ISSUE TITLE
Add commonly used Activations to Ivy's Stateful API

### ISSUE THREAD

**Issue by HaiderSultanArc** [unifyai/ivy#19727]
Add commonly used Activations to Stateful API

> Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

- [ ] GELU
- [ ] GEGLU
- [ ] ReLU
- [ ] LeakyReLU
- [ ] LogSoftmax
- [ ] Softmax
- [ ] Softplus
- [ ] Mish
- [ ] SiLU
- [ ] Sigmoid
- [ ] Tanh
- [ ] ReLU6
- [x] #19740
- [x] #19746
- [x] #19750
- [ ] ThresholdedReLU
- [x] #19745
- [x] #19808
- [x] #19747

**Comment by tejeshbhalla** [comment]
#19747

**Comment by OkeyAmy** [comment]
19754

**Comment by OkeyAmy** [comment]
- [ ] 19754

**Comment by guodh321** [comment]
- [SeLU]

**Comment by guodh321** [comment]
- [SeLU] #19727

**Comment by HaiderSultanArc** [comment]
> * [SeLU] [Add commonly used Activations to Ivy's Stateful API #19727](https://github.com/unifyai/ivy/issues/19727)

You have to add the issue number of the newly opened issue with the name of the sub-task.
On the top right corner of this screen you can see "New Issue", go there and open a new issue under the category "Sub-task" with the name "SeLU" then copy the number of that issue and write in your comment after like this: "[SeLU] #issue_number" 😊

**Comment by guodh321** [comment]
SeLU#19808

**Comment by nadine-ramirez** [comment]
Issue # 19745

**Comment by guodh321** [comment]
> 

Hi @HaiderSultanArc, is there any description or guidance on how to solve these kinds of tasks? Thanks.

**Comment by SaimR036** [comment]
SeLU #19808

**Comment by SaimR036** [comment]
#19861

**Comment by so-dipe** [comment]
ThresholdedReLU #19889

**Comment by SaimR036** [comment]
[SeLU] #19861

**Comment by SaimR036** [comment]
HaiderSultanArc my comment isnt getting deleted would you help

**Comment by HaiderSultanArc** [comment]
> HaiderSultanArc my comment isnt getting deleted would you help

Hey @SaimR036 , this issue has been assigned to someone else. You can select other issues 😀

**Comment by sohamkumar05** [comment]
- [ ] #20794

**Comment by MohamedEzzatIsmail** [comment]
- [ ] #19889

**Comment by Praneet9** [comment]
#19745

**Comment by Praneet9** [comment]
- [ ] #19745

**Comment by aks1204** [comment]
[HaiderSultanArc](https://github.com/HaiderSultanArc) Can you assign either #19889 or #19745 to me?

**Comment by aks1204** [comment]
@HaiderSultanArc can I work on [ThresholdedReLU] #19889 or [LogSigmoid] #19745 ?

**Comment by Praneet9** [comment]
> @HaiderSultanArc can I work on [ThresholdedReLU] #19889 or [LogSigmoid] #19745 

I've already almost completed #19745

**Comment by aks1204** [comment]
> > @HaiderSultanArc can I work on [ThresholdedReLU] #19889 or [LogSigmoid] #19745
> 
> I've already almost completed #19745

@HaiderSultanArc then can I work on [ThresholdedReLU] #19889

**Comment by HaiderSultanArc** [comment]
> > @HaiderSultanArc can I work on [ThresholdedReLU] #19889 or [LogSigmoid] #19745
> 
> I've already almost completed #19745

Hey @Praneet9 , this issue is assigned to someone else 😄 . You have to get an issue assigned to you before you can work on it.

**Comment by HaiderSultanArc** [comment]
> > > @HaiderSultanArc can I work on [ThresholdedReLU] #19889 or [LogSigmoid] #19745
> > 
> > 
> > I've already almost completed #19745
> 
> @HaiderSultanArc then can I work on [ThresholdedReLU] #19889

Hey @aks1204 this issue is already assigned to someone else 😄

**Comment by Harisrp82** [comment]
I am interested in contributing to this task. Could you please assign it to me

**Comment by SaimR036** [comment]
-[] #22612

**Comment by SaimR036** [comment]
@HaiderSultanArc The RELU issue is open right i have created an issue

**Comment by imessam** [comment]
[ReLU] #22620

**Comment by imessam** [comment]
Sigmoid #22621

**Comment by imessam** [comment]
- [] #22620

**Comment by HaiderSultanArc** [comment]
> @HaiderSultanArc The RELU issue is open right i have created an issue

Hey @SaimR036. I think there's an issue with our bot. These Activation Functions are actually done. We'll look into it 😄. In the meantime, you can look for other open tasks. Thanks!
