### ISSUE TITLE
Github Workflow runs

### ISSUE THREAD

**Issue by RakshitKhajuria** [unifyai/ivy#19763]
When I create a pull request (PR), it undergoes several checks, some of which pass, while others fail. However, I am unable to identify the specific errors causing the failures. I believe there is room for improvement in the feedback provided by the checks.

![image](https://github.com/unifyai/ivy/assets/71117423/22315507-4bc8-477e-94b3-4398048d1616)

**Comment by AnnaTz** [comment]
If you expand the Determine Tests field you can see the functions that are failing. 
The `Suggestion` issues are supposed to be opened to suggest new ivy functions, so I will close this. But I will make sure to suggest improving the CI checks format to our team. Thanks!

**Comment by RakshitKhajuria** [comment]
![image](https://github.com/unifyai/ivy/assets/71117423/09b528f3-1a00-465c-9657-3a8ee9371878)
Cool ! what i meant was it doesn't give in which line it gives the error and doesn't display it. It can be improved thanks ! :)

**Comment by AnnaTz** [comment]
There are details under `[display_test_results](https://github.com/unifyai/ivy/actions/runs/5619114864/job/15225863350?pr=19762#logs)`.
