### ISSUE TITLE
dev_dist_array

### ISSUE THREAD

**Issue by rjsun06** [unifyai/ivy#1979]

**Comment by rjsun06** [comment]
#1980

**Comment by 1Doomdie1** [comment]
Please leave a comment with the issue from where you took this function from

**Comment by rjsun06** [comment]
#814

**Comment by Unevilicorn** [comment]
Hi there,
It seems that we've made a mistake :sweat_smile: , we're not longer supporting this function for the next release and we should have removed this function from the todo-list beforehand. Sorry about this oversight. Please choose another function to work on.
Thanks!
