### ISSUE TITLE
Add Pooling Layers

### ISSUE THREAD

**Issue by GenghuiQu** [unifyai/ivy#2]
Would be better to be able to add pooling in the layers, like MaxPool2D.

**Comment by djl11** [comment]
Regarding your second point, I believe this is only an issue with the latest PyPI release. A unit test has been added for this demo in master. The PyPI release will be updated soon, thanks for pointing this out :)

Regarding the issue with jupyter notebook, does the issue appear simply when calling `import ivy.tensorflow`?

**Comment by djl11** [comment]
Could you also please create separate issues for the "Quick Start" issue and the Jupyter notebook issue? I can then close these issues individually once they have been resolved. Thanks!

**Comment by 792370706** [comment]
> Could you also please create separate issues for the "Quick Start" issue and the Jupyter notebook issue? I can then close these issues individually once they have been resolved. Thanks!

**Comment by 792370706** [comment]
> Could you also please create separate issues for the "Quick Start" issue and the Jupyter notebook issue? I can then close these issues individually once they have been resolved. Thanks!

Done! 

Regarding the issue with jupyter notebook, it's my fault - I didn't add 'ivy.unset_framework()' after running in PyTorch, so something went wrong when running in tensorflow. Sorry for that!
