### ISSUE TITLE
Attribute error : the 'ivy' module doesn't seem to have the function 'set_backend'

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [unifyai/ivy#2064]
line of code (from the documentation):
"ivy.set_backend('torch')  # change to any backend!"
the error message :
"AttributeError: module 'ivy' has no attribute 'set_backend'"
tried doing this 
>>> print('set_backend' in dir(ivy))
>>> False

Has the module name been updated to something else . I am using python 3.9.13  and pip3

**Comment by someshfengde** [comment]
please refer to this issue https://github.com/unifyai/ivy/issues/2055

I've managed to solve this by using ivy.set_framework("torch") 
there is version difference from documentation

**Comment by someshfengde** [comment]
welcome :smile: 

you can close this issue @bloodgroup-cplusplus
