### ISSUE TITLE
Stop spamming people's email to advertise this product.

### ISSUE THREAD

**Issue by thcrt** [unifyai/ivy#20706]
**This is a copy of an email I sent in response to recieving unsolicited spam from Daniel, the maintainer of Ivy. I've reuploaded it here to enter it into a more public record.**

---

Hi Daniel,

Thanks for your email. I have a few questions and comments I'm willing to share with you, Ronald and the Ivy team.

> Apologies for the cold email

Where did you get this email address? You claim to be knowingly sending a cold email, so you're obviously aware I never asked or consented to hear from you regarding this or anything else. My first thought was that you purchased a list of emails scraped from the internet or obtained in database breaches, either of which doesn't go far towards painting you in a good light. But a small bit of digging pulls up a few issues on GitHub ([#4413](https://github.com/unifyai/ivy/issues/4413), [#13014](https://github.com/unifyai/ivy/issues/13014) and [#1202](https://github.com/unifyai/ivy/issues/1202)) where you're confronted with the reality that you're mass-mailing people to hawk your product. You claim that you sourced the emails from public profiles and websites, a claim faced with a subsequent challenge which the nature of the platform of which you're in control conveniently allows you to ignore.  You mention that "[the] vast majority of the people we reach out to are interested in what we're building, and would like to learn more" -- a claim I find extremely doubtful. If you give me concrete statistics showing that the majority of people don't simply ignore your spam, I'll buy you a beer. 

> we thought you might be interested in giving it a spin

Did you? That's odd, considering you don't know what I'm interested in. If you did, you wouldn't have offered. I have never done any work on machine learning or AI, nor have I contributed any code to or made any substantial engagements in the communities of any projects related to those fields. Daniel, we're only at the third real paragraph, and you've already lied to me. We're not setting a great precedent for the rest of our communication here. 

> We’d love to hear your general thoughts on what we’ve built, both positive and negative :)

In case I haven't already made it clear, I don't give a damn what you've built. Here are my thoughts on you, though, Daniel: sending spam emails in bulk to advertise your project is an extremely poor look. Not only does it reflect badly on Ivy, the practice, along with my concerns about where you source your email lists, casts a great level of doubt in my mind on the ethical practices of Imperial College London. I'd love to talk with you, your PhD supervisor or anyone else at the university who specialises in professional ethics.

Your final call to "just ignore" if "none of this is of interest" suggests you've recieved more negative feedback than you'd like to admit on GitHub, and is an excellent way to shift focus from your malpractice towards those awfully unreasonable people who take issue with it. 

I'd hope that you take some time to reconsider your strategy here. Failing that, I'd appreciate a closer look by the university into the same.

Regards

Theo Court
https://theocourt.com/
he/him

**Comment by thcrt** [comment]
Closed without comment? That’s embarrassing.

**Comment by fouric** [comment]
@thcrt Suggestion: mark as spam in Gmail - if enough people do that, then the emails will be sent directly to spam and not seen in the inbox at all - that's what I'm doing. This is not acceptable.
