### ISSUE TITLE
Fix ndarray.test_numpy___truediv__

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#20718]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6408219481/job/17396712237"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6408219481/job/17396712237"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6408219481/job/17396712237"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6408219481/job/17396712237"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6408219481/job/17396712237"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by BilgehanMehmet** [comment]
Hello,
I am a new contributor, and it's my first time contributing. I would like to work on this issue. 

I have been debugging the test cases for numpy and torch frontends. I have fixed the errors for the numpy version. And now I am working on the torch test case.  

Please assign me.

**Comment by BilgehanMehmet** [comment]
@DragosStoican can you please advise?

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
