### ISSUE TITLE
adaptive_avg_pool2d

### ISSUE THREAD

**Issue by Zamokuhle23** [unifyai/ivy#20804]
Close #20804

**Comment by Zamokuhle23** [comment]
![image](https://github.com/unifyai/ivy/assets/65773452/a87acc70-d315-4514-a824-0df1b1f7fdbb)


When I test it locally its working, Can you help me write the ivy test as Mindspore is not imported in ivy_tests.

**Comment by Zamokuhle23** [comment]
the same values produce the same results in jupyter
![image](https://github.com/unifyai/ivy/assets/65773452/d0c2c1f3-6c11-4e95-b858-32c655969948)

**Comment by Zamokuhle23** [comment]
@Ishticode will anyone review this pull request?

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would like to continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues

**Comment by Zamokuhle23** [comment]
> 

@ivy-seed I have been waiting for this issue to be assigned to someone and review but to no vail for a month now
#20804
