### ISSUE TITLE
[Documentation]: <ivy image simulation not loading correctly>

### ISSUE THREAD

**Issue by DoudGaya** [unifyai/ivy#21057]
### Path

https://unify.ai/docs/ivy/

### Section

Ivy > Ivy as a Framework

### Actual Behavior

The following image https://github.com/unifyai/unifyai.github.io/blob/master/img/regressor_lq.gif is not loading correctly on the docs. In the Ivy Section under Ivy as a framework Heading. 

### Expected Behavior

Image section should display a visual example of a model output.

### Screenshots

![image](https://github.com/unifyai/ivy/assets/57319135/004433e7-74fd-465b-96e8-b52f658733a3)

**Comment by KareemMAX** [comment]
@DoudGaya Thank you for your feedback.
Fixed by 6a18494
