### ISSUE TITLE
[Bug]: ivy.multi_dot infinite recursion on Paddle backend

### ISSUE THREAD

**Issue by 4di03** [unifyai/ivy#21119]
### Bug Explanation

ivy.multi_dot produces the following error message when testing with paddle backend:

```
ivy.utils.exceptions.IvyBackendException: paddle: multi_dot: paddle: multi_dot: paddle: multi_dot: paddle: multi_dot: paddle: multi_dot: paddle: multi_dot:  . . .  paddle: nested_map: maximum recursion depth exceeded
```

### Steps to Reproduce Bug

Run any test for a function that invokes multi_dot. You can also run the test for multi_dot itself but you will need to edit the code to add the on_device argument.

For example, test numpy_multi_dot:

```
pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_linalg/test_matrix_and_vector_products.py::test_numpy_multi_dot
```

### Environment

Environements tested:

- github codespaces, latest version of master
- pycharm with local conda interpreter

### Ivy Version

commit 1545a85 on master

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

M1 Mac

**Comment by akshatvishu** [comment]
Hey @OmarJabri7  I have tried to fix this issue and linked a `PR` for it.
