### ISSUE TITLE
[Bug]: Missing test for frontend `torch.igamma` frontend method

### ISSUE THREAD

**Issue by alexkoziell** [unifyai/ivy#21166]
### Bug Explanation

A frontend implementation of `torch.igamma` exists in `ivy/functional/frontends/torch/pointwise_ops.py` but no test for it is present in `ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py`

---
#### Suspected Cause:

The test introduced in #21031 for the frontend implementation of `torch.igamma` was accidentally written for the `torch.tensor.igamma` instance method.

I think the actual test should have been written in `ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py`, rather than `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py`.

### Steps to Reproduce Bug

The test is missing, so this fails silently!

### Environment

MacOS PyCharm with Docker

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by chethanreddy123** [comment]
@alexkoziell I would like to take up this bug, could please help me out?

**Comment by hello-fri-end** [comment]
Looks like a fix for this has already been implemented here https://github.com/unifyai/ivy/commit/3ee037943f88f9fc96f066da8da1944c8fc03b47
