### ISSUE TITLE
ivy.einsum

### ISSUE THREAD

**Issue by dhanush-2501** [unifyai/ivy#21177]
**Why should this be implemented?**
- 3+ of the native frameworks have this function
- required to implement a frontend TODO
**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.einsum.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.einsum.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/einsum)
- [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html)

**Comment by AnnaTz** [comment]
Hi @dhanush-2501, `ivy.einsum` is already implemented [here](https://github.com/unifyai/ivy/blob/44652adf076cc5bd9f80d417930d9981522e88b2/ivy/functional/ivy/statistical.py#L1190).
