### ISSUE TITLE
`--wrapped_mode true` testing parameter causes numpy (only) tests to fail in all math functions

### ISSUE THREAD

**Issue by Abdelrhman-Hosny** [unifyai/ivy#212]
I was trying to implement functions in the `math.py` file, however, I kept facing two errors. One of them I figured out and submitted a PR #165 explaining the problem and how I fixed it . The other I'll show to you now.

****
## Steps to reproduce

1. Add the effects from PR #165 (if not added, you don't reach the stage of the next error)
2. run the tests normally, just adding the parameters `--framework numpy --wrapped_mode true`

****

These are some screenshots for the tests, run using different parameters.

**N.B.** all the functions fail in the `assert ivy.is_array(x)`

Using default parameters and running, we get a total of 52 errors.
![all_tests_normal](https://user-images.githubusercontent.com/59120704/154495186-c9a3831b-902d-4b20-bbca-7174bb029c00.png)

Running with the parameter `--framework numpy` gives the same amount of errors
![all_tests_np_only](https://user-images.githubusercontent.com/59120704/154495346-1452d22f-5374-41b2-abf1-94c3da44ac99.png)

Running with the parameters `--framework numpy --wrapped_mode true` also gives 52 errors.
![all_tests_np_wrapped_true](https://user-images.githubusercontent.com/59120704/154495473-0d342198-1bac-4843-bb22-480a0c271144.png)

I ran with the parameters `--framework numpy --wrapped_mode false` and all 52 of them passed.

****
When I went to debug, I think I found the problem but still can't quite explain it.

as stated above all cases fail at the `ivy.is_array(x)`.

When debugging using `--framework torch --wrapped_mode true`. I got the following
![test_wr_true_torch](https://user-images.githubusercontent.com/59120704/154496165-2576cf37-5087-4269-805c-28e1b034d84f.png)

Notice that the type of `x` is a `torch.tensor` which passes the `isinstance(x, _torch.Tensor)`

However, if we run the same with numpy (`--framework numpy --wrapped_mode true`), we get the following
![test_wr_true_np](https://user-images.githubusercontent.com/59120704/154496497-14387a60-4883-43ec-97ab-a9447eae7e6a.png)

Notice that `x` is now an `ivy.array` not a `ndarray`. this causes it to fail the check of `isinstance(x, _np.ndarray)`

****

I'm not sure why they don't all act the same (i.e. either both PyTorch and NumPy become `ivy.array` or both stay the same).

I'm also not sure why `ivy.array` doesn't pass the test `ivy.is_array`, I know what happens in the code but design-wise I'm not sure why it doesn't pass.

This should be easily fixable, however, I'm not sure of the steps to be taken and don't want to take a step that might go against the design of the framework without referring to somebody first.

****

**Comment by djl11** [comment]
Is this still an issue with the latest version?

**Comment by djl11** [comment]
Given that these tests have temporarily been removed. I will close this issue for now.
