### ISSUE TITLE
[Bug]: Inconsistent Behavior of paddle.sqrt in Ivy Backend with Non-Floating Dtypes Support

### ISSUE THREAD

**Issue by akshatvishu** [unifyai/ivy#21231]
### Bug Explanation

As the [paddle.sqrt](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/sqrt_en.html#sqrt) only supports floating dtypes (`float16`, `float32`, `float64`) natively, the current backend implementation of it in `ivy` is modified to add support for integer, unsigned, bool, and complex dtypes. However, this current implementation behavior does not match with any other framework that supports these dtypes and the value outputted seems to be wrong too due to casting it back to their original dtype .

Thus, I want to know which framework's behavior we should try to emulate with it, and upon reaching this resolution, I can raise a pull-request for it.

### Steps to Reproduce Bug

```
import numpy as np
import jax.numpy as jnp
import torch
import ivy


dtypes = [
    np.int8,
    np.int16,
    np.int32,
    np.int64,
    np.uint8,
    np.float16,
    np.complex64,
    np.complex128,
]

for dtype in dtypes:
    x = np.array([2], dtype=dtype)
    y = np.sqrt(x)

    print(f"Output:{y}, Input dtype: {x.dtype}, Output dtype: {y.dtype}")

dtypes = [
    torch.int8,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.uint8,
    torch.complex64,
    torch.complex128,
    torch.bool,
]

for dtype in dtypes:
    x = torch.tensor([2], dtype=dtype)
    y = torch.sqrt(x)

    print(f"Output:{y},Input dtype: {x.dtype}, Output dtype: {y.dtype}")


dtypes = [
    jnp.int8,
    jnp.int16,
    jnp.int32,
    jnp.int64,
    jnp.uint8,
    jnp.float16,
    jnp.complex64,
    jnp.complex128,
    jnp.bool_,
]

for dtype in dtypes:
    x = jnp.array([2], dtype=dtype)
    y = jnp.sqrt(x)

    print(f"Output:{y},Input dtype: {x.dtype}, Output dtype: {y.dtype}")


dtypes = [
    ivy.int8,
    ivy.int16,
    ivy.int32,
    ivy.int64,
    ivy.uint8,
    ivy.complex64,
    ivy.complex128,
    ivy.bool,
]

for dtype in dtypes:
    ivy.set_backend("paddle")
    x = ivy.array([2], dtype=dtype)
    y = ivy.sqrt(x)
    print(f"Output:{y},Input dtype: {x.dtype}, Output dtype: {y.dtype}")
    
    
    """
# --- Numpy  --- #
Output:[1.414], Input dtype: int8, Output dtype: float16
Output:[1.4142135], Input dtype: int16, Output dtype: float32
Output:[1.41421356], Input dtype: int32, Output dtype: float64
Output:[1.41421356], Input dtype: int64, Output dtype: float64
Output:[1.414], Input dtype: uint8, Output dtype: float16
Output:[1.414], Input dtype: float16, Output dtype: float16
Output:[1.4142135+0.j], Input dtype: complex64, Output dtype: complex64
Output:[1.41421356+0.j], Input dtype: complex128, Output dtype: complex128

# --- Torch  --- #
Output:tensor([1.4142]),Input dtype: torch.int8, Output dtype: torch.float32
Output:tensor([1.4142]),Input dtype: torch.int16, Output dtype: torch.float32
Output:tensor([1.4142]),Input dtype: torch.int32, Output dtype: torch.float32
Output:tensor([1.4142]),Input dtype: torch.int64, Output dtype: torch.float32
Output:tensor([1.4142]),Input dtype: torch.uint8, Output dtype: torch.float32
Output:tensor([1.4142+0.j]),Input dtype: torch.complex64, Output dtype: torch.complex64
Output:tensor([1.4142+0.j], dtype=torch.complex128),Input dtype: torch.complex128, Output dtype: torch.complex128
Output:tensor([1.]),Input dtype: torch.bool, Output dtype: torch.float32

# --- Jax  --- #
Output:[1.4142135],Input dtype: int8, Output dtype: float32
Output:[1.4142135],Input dtype: int16, Output dtype: float32
Output:[1.4142135],Input dtype: int32, Output dtype: float32
Output:[1.41421356],Input dtype: int64, Output dtype: float64
Output:[1.4142135],Input dtype: uint8, Output dtype: float32
Output:[1.414],Input dtype: float16, Output dtype: float16
Output:[1.4142135+0.j],Input dtype: complex64, Output dtype: complex64
Output:[1.41421356+0.j],Input dtype: complex128, Output dtype: complex128
Output:[1.],Input dtype: bool, Output dtype: float32

# --- Paddle --- #
Output:ivy.array([1]),Input dtype: int8, Output dtype: int8
Output:ivy.array([1]),Input dtype: int16, Output dtype: int16
Output:ivy.array([1]),Input dtype: int32, Output dtype: int32
Output:ivy.array([1]),Input dtype: int64, Output dtype: int64
Output:ivy.array([1]),Input dtype: uint8, Output dtype: uint8
Output:ivy.array([1.4142135+0.j]),Input dtype: complex64, Output dtype: complex64
Output:ivy.array([1.41421356+0.j]),Input dtype: complex128, Output dtype: complex128
Output:ivy.array([ True]),Input dtype: bool, Output dtype: bool
    
    """

```

### Environment

Linux + vscode + docker

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX
- [x] Paddle

### Device

CPU

**Comment by Pchatain** [comment]
Based on the standard for sqrt function [here](https://data-apis.org/array-api/latest/API_specification/generated/array_api.sqrt.html?highlight=square%20root), I think we should follow the type promotion linked in the guide [here](https://data-apis.org/array-api/latest/API_specification/type_promotion.html#type-promotion), and the returned type must be a floating-point data type.

So in the types you gave, the return types should be

```
# --- Paddle --- #
Output:ivy.array([1]),Input dtype: int8, Output dtype: float32
Output:ivy.array([1]),Input dtype: int16, Output dtype: float32
Output:ivy.array([1]),Input dtype: int32, Output dtype: float32
Output:ivy.array([1]),Input dtype: int64, Output dtype: float64
Output:ivy.array([1]),Input dtype: uint8, Output dtype: float32
Output:ivy.array([1.4142135+0.j]),Input dtype: complex64, Output dtype: complex64
Output:ivy.array([1.41421356+0.j]),Input dtype: complex128, Output dtype: complex128
Output:ivy.array([1.]),Input dtype: bool, Output dtype: float32
```
^ obviously the outputs would then be fixed to not be all 1's. 

I think we should support float16 -> float16 as well, unless you see a reason we shouldn't for paddle.

The last case of bool is a special case. The doc says "Type promotion of non-numerical data types to numerical data types is unspecified." This makes me really curious of cases such as Input dtype: torch.bool, Output dtype: torch.float32. Since all the other frameworks do that, I recommend we do that as well.

**Comment by akshatvishu** [comment]
> Based on the standard for sqrt function [here](https://data-apis.org/array-api/latest/API_specification/generated/array_api.sqrt.html?highlight=square%20root), I think we should follow the type promotion linked in the guide [here](https://data-apis.org/array-api/latest/API_specification/type_promotion.html#type-promotion), and the returned type must be a floating-point data type.
> 
> So in the types you gave, the return types should be
> 
> ```
> # --- Paddle --- #
> Output:ivy.array([1]),Input dtype: int8, Output dtype: float32
> Output:ivy.array([1]),Input dtype: int16, Output dtype: float32
> Output:ivy.array([1]),Input dtype: int32, Output dtype: float32
> Output:ivy.array([1]),Input dtype: int64, Output dtype: float64
> Output:ivy.array([1]),Input dtype: uint8, Output dtype: float32
> Output:ivy.array([1.4142135+0.j]),Input dtype: complex64, Output dtype: complex64
> Output:ivy.array([1.41421356+0.j]),Input dtype: complex128, Output dtype: complex128
> Output:ivy.array([1.]),Input dtype: bool, Output dtype: float32
> ```
> 
> ^ obviously the outputs would then be fixed to not be all 1's.
> 
> I think we should support float16 -> float16 as well, unless you see a reason we shouldn't for paddle.
> 
> The last case of bool is a special case. The doc says "Type promotion of non-numerical data types to numerical data types is unspecified." This makes me really curious of cases such as Input dtype: torch.bool, Output dtype: torch.float32. Since all the other frameworks do that, I recommend we do that as well.

Hey @Pchatain , I linked a `PR` for this issue which now makes `paddle.sqrt` behave the same as we discussed above.  It would be great if you can give your insight on the code and it's readability .
