### ISSUE TITLE
ivy.channel_shuffle

### ISSUE THREAD

**Issue by zawyar** [unifyai/ivy#21235]
**Why should this be implemented?**
- 2 native frameworks, namely PyTorch and Paddle support it
- The documentation recommends ivy front-end functions to be 1 line long by convention. Without an Ivy implementation, the only possibility is a long compositional implementation

**Links to native framework implementations**
- [PyTorch](https://pytorch.org/docs/stable/_modules/torch/nn/modules/channelshuffle.html#ChannelShuffle)
- [Paddle](https://pytorch.org/docs/stable/_modules/torch/nn/modules/channelshuffle.html#ChannelShuffle)

**Comment by zawyar** [comment]
For now, I have added a compositional implementation and added a Todo comment

**Comment by AnnaTz** [comment]
Thanks for the suggestion! I have added `channel_shuffle` to our ToDo list.
