### ISSUE TITLE
[Bug]: ModuleNotFoundError

### ISSUE THREAD

**Issue by aks1204** [unifyai/ivy#21248]
### Bug Explanation

No module named 'ivy.functional.frontends.jax.scipy' in ivy_tests/test_ivy/helpers/testing_helpers.py

### Steps to Reproduce Bug

Configure the array_api_tests/_array_module.py file(lines 8 and 9) as
```
import ivy as array_module
array_module.set_backend('numpy')
```
Add a .vscode folder to your workspace and then add a settings.json file containing the following
```
{
   "python.testing.pytestArgs": [
      "./ivy_tests/test_ivy/",
      "./ivy_tests/array_api_testing/test_array_api/",
   ],
   "python.testing.unittestEnabled": false,
   "python.testing.pytestEnabled": true
}
```
Configure Python tests and select PyTest as the test framework keeping ivy_tests as the root directory for testing.

### Environment

GitHub Codespaces + VS Code

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

4 core CPU + 8 GB RAM + 32 GB Storage

**Comment by shephinphilip** [comment]
@aks1204   I don't   find   any  "ivy.functional.frontends.jax.scipy"  in the directory you mentioned   "ivy_tests/test_ivy/helpers/testing_helpers.py"  .  Please correct  me if I am  missing something here .

**Comment by aks1204** [comment]
@shephinphilip Try to set up files up for testing as I have mentioned above.
