### ISSUE TITLE
[Bug]: Absence of a file for retrieving html_theme_options from docs/conf.py in the docs\partial_conf.py file.

### ISSUE THREAD

**Issue by shephinphilip** [unifyai/ivy#21300]
### Bug Explanation

The bug involves the absence of a file required for retrieving html_theme_options from docs/conf.py, resulting in an error in the docs\partial_conf.py file.

### Steps to Reproduce Bug

- Navigate to the docs directory within the project.

- Locate the partial_conf.py file , in the line 48 in the  vs code

### Environment

Operating System: Windows 10
IDE: Visual Studio Code (VScode)

### Ivy Version

1.1.10

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by KareemMAX** [comment]
`partial_conf.py` is working as intended and shouldn't be run alone. You will need to use our doc builder for this code to execute correctly. As mentioned in our [building the docs guide](https://unify.ai/docs/ivy/overview/contributing/building_the_docs.html).

If you are interested of how exactly our pipeline works please refer to this [deep dive](https://unify.ai/docs/ivy/overview/deep_dive/building_the_docs_pipline.html)
