### ISSUE TITLE
solve

### ISSUE THREAD

**Issue by dhanush-2501** [unifyai/ivy#21319]
### Bug Explanation

The `paddle.linalg.solve` tests are failing. The tests and the front-end function are not implemented properly.
The test should generate two matrices of shape [ *, M, M ] and [ *, M, K ] but the written test just generates two matrices of the same shape, and function arguments are mismatched returning 
`TypeError: solve() got an unexpected keyword argument 'x'`

### Steps to Reproduce Bug

Run : `pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_linalg.py::test_paddle_solve`

### Environment

MacOs : 13.5

### Ivy Version

 0.0.0.0.0

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

Mac M1

**Comment by dhanush-2501** [comment]
I have resolved this bug and made a PR. Have a look on it

**Comment by dhanush-2501** [comment]
@satakshigarg   I have found the fix as well

**Comment by satakshigarg** [comment]
Thank you @dhanush-2501 for sharing the bug. Could you please share the high level overview of the fix, so that I can get a better idea about it ?

**Comment by dhanush-2501** [comment]
@satakshigarg it's very simple. We need to generate two different arrays of shape [*,M,M] and [*, M, k] and have to pass it. The current approach just generates two arrays of the same shape that's the cause of the error.

**Comment by ivy-leaves** [comment]
This issue is being closed as the function implementation is already present.
          Thanks for contributing so far.
          Feel free to look at other issues if you want to contribute further ✌️

**Comment by sachelsout** [comment]
Hello @ReneFabricius , could you please reopen this issue named 'solve'. This issue is seen as completed (ivy-leaves tagged it as completed and closed) but when I checked the code (function, relevant tests), and ran the tests, the tests still fails. The code is not updated as per the above discussion thread.

Thank you.

**Comment by satakshigarg** [comment]
Thanks @dhanush-2501 for mentioning the failing tests 😃
Feel free to ping us when you feel it's ready.
Thank you !!

**Comment by dhanush-2501** [comment]
@satakshigarg @ReneFabricius  I Fixed it. pls review it and provide feedback
