### ISSUE TITLE
ivy.stanh(x, scale_a,scale_b)

### ISSUE THREAD

**Issue by davidMadueke** [unifyai/ivy#21341]
**Why should this be implemented?**
- it's needed for a complex/long frontend function implementation namely the stanh function (see issue #20903)

**Links to native framework implementations**
- [Paddle Paddle](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/stanh_en.html)

**Comment by AnnaTz** [comment]
Thanks for the suggestion! I have added `stanh` to our ToDo list.
