### ISSUE TITLE
Chore(dx): rename master to branch

### ISSUE THREAD

**Issue by a0m0rajab** [unifyai/ivy#21367]
GitHub took some efforts to change master branch to main in the previous year (at the time of BLM). Since master could be connected to slavery, as from inclusion perspective, it would be great to change the name of the branch for ivy as well. 

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

Renaming process: 
https://github.com/github/renaming

**Comment by rishabgit** [comment]
Hey, thanks a ton for bringing this up and for linking the renaming process! :smile: 

We'll make this update ASAP. I'll keep this issue open until then as we'll have to do the necessary research and set proper guardrails to make sure it'll not cause any unexpected breaks in our CI/CD pipelines, pip installs or anything Ivy.

**Comment by rishabgit** [comment]
Thanks for the suggestion @a0m0rajab, default branch has been renamed :smile:
