### ISSUE TITLE
[Bug]: Typo in Numpy Frontend Tests for FFT

### ISSUE THREAD

**Issue by hnhparitosh** [unifyai/ivy#21429]
### Bug Explanation

In the file `ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py` there are a few typos.
The function name in line 19 `test_numpy_iftt` should be `test_numpy_ifft`.
The function name in line 42 `test_numpy_ifttshift` should be `test_numpy_ifftshift`.
Same for line 95, `fttshift`.

### Steps to Reproduce Bug

Just view the typos in the code.

### Environment

Windows 11, PyCharm + Docker

### Ivy Version

latest (idk)

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by Pchatain** [comment]
yeah this looks like a good catch!

**Comment by dark-developer15** [comment]
can close this bug, if resolved?

**Comment by Pchatain** [comment]
@dark-developer15 Nice, can you link the related PR to Ivy that fixes it? All I see is your local copy of the code with the fixes. @pranith7 apologies for not seeing this, it somehow slipped through my notifications.

**Comment by pranith7** [comment]
> @dark-developer15 Nice, can you link the related PR to Ivy that fixes it? All I see is your local copy of the code with the fixes. @pranith7 apologies for not seeing this, it somehow slipped through my notifications.

@Pchatain No problem.

**Comment by dark-developer15** [comment]
https://github.com/unifyai/ivy/pull/22400#issue-1863152922
I am new here and still looking through docs, that's why I didn't knew, I will remember it next time.

**Comment by Pchatain** [comment]
Thanks @dark-developer15 I'll close this now. @hnhparitosh pretty sure his PR addresses this issue, comment again if otherwise.
