### ISSUE TITLE
ivy.cross

### ISSUE THREAD

**Issue by rajveer43** [unifyai/ivy#21521]
**Why should this be implemented?**
- 3+ of the native frameworks have this function

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.cross.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.cross.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/cross)
- [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.cross.html)

**Comment by hirwa-nshuti** [comment]
It is implemented https://unify.ai/docs/ivy/docs/functional/ivy/linear_algebra/ivy.functional.ivy.linear_algebra.cross.html#cross
