### ISSUE TITLE
[Documentation]: Incorrect file path in documentation for ivy.current_backend()

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [unifyai/ivy#21574]
### Path

https://unify.ai/docs/ivy/overview/design/building_blocks.html#backend-handler

### Section

Backend Handler

### Actual Behavior

The actual documentation mentions `ivy/backend_handler.py` as the path to the file where `ivy.current_backend()` is defined. This can be seen in the first line in the **# Backend Handler** section

### Expected Behavior

The actual path for `ivy.current_backend()` as found in the repository is `ivy/utils/backend/handler.py`

### Screenshots

The present docs 
![image](https://github.com/unifyai/ivy/assets/89456541/22d9a01c-dcb1-4739-91a4-f55ca2018427)

Actual Path
![image](https://github.com/unifyai/ivy/assets/89456541/67f1a497-7caa-4195-86f3-d4872c8debe4)

**Comment by MuhammadNizamani** [comment]
@sahil-sagwekar2652  are you going to create a PR for this issue?

**Comment by KareemMAX** [comment]
@sahil-sagwekar2652 Yeah seems like the document is a bit outdated, updating it now

**Comment by sahil-sagwekar2652** [comment]
@KareemMAX That's great, thank you
