### ISSUE TITLE
ModuleNotFoundError when importing ivy.compiler._compiler locally

### ISSUE THREAD

**Issue by ANIRUDH-333** [unifyai/ivy#21587]
### Path

https://unify.ai/docs/ivy/compiler/compiler.html

### Section

Graph compiler

### Actual Behavior

The module should be imported without any errors, but throwing an error when running the code given in the documentation. Same thing works fine when running in google colab.

`import ivy

ivy.set_backend("torch")

def fn(x, y):
    z = x**y
    print(z)
    k = x * y
    j = ivy.concat([x, z, y])
    sum_j = ivy.sum(j)
    return z

x = ivy.array([1, 2, 3])
y = ivy.array([2, 3, 4])

# Compile the function
compiled_fn = ivy.compile(fn, args=(x, y))`

### Expected Behavior

The code should run well in the local environment as well.

I tried with python 3.9 and 3.10.12 as well. Both dont work.

### Screenshots

![ivy_issue](https://github.com/unifyai/ivy/assets/68942952/653ae71c-dc76-4029-890b-e7f625d6ebcd)

**Comment by KareemMAX** [comment]
This issue is more compiler related. Maybe @vaatsalya123 @guillesanbri, can you look into this issue?

**Comment by vaatsalya123** [comment]
Hey @ANIRUDH-333 , Maybe your running the above code locally inside an Windows environment , If so currently Windows OS is not supported and is something we are looking to get up and running soon! 

Thanks!

**Comment by ANIRUDH-333** [comment]
Ohh okayy... you are right! I am running it on Windows OS. 

Thank you for clarifying.

**Comment by ANIRUDH-333** [comment]
@iamade Hello, sorry but I am unsure about MAC OS as I have never used it.
