### ISSUE TITLE
Add Linear functions to PyTorch Frontend

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#22]
Add [Linear functions](https://pytorch.org/docs/stable/nn.functional.html#linear-functions) to PyTorch frontend:

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #2441 
- [x] #4286

**Comment by Winvoker** [comment]
- [] #2441

**Comment by Winvoker** [comment]
- [ ] #2441

**Comment by pradyyadav** [comment]
I would like to start contributing to ivy with this issue. #2868

**Comment by Nielsencu** [comment]
#4286
