### ISSUE TITLE
ivy.functional.frontends.paddle.tensor.tensor in std method 

### ISSUE THREAD

**Issue by samthakur587** [unifyai/ivy#22151]
### Bug Explanation

there a method called std in ivy.functional.frontends.paddle.tensor.tensor is only implemented without the test function. and it has wrong implementation.

```python 
@with_unsupported_dtypes({"2.4.2 and below": ("float32", "float64")}, "paddle")
    def std(self, axis=None, unbiased=True, keepdim=False, name=None):
        return paddle_frontend.Tensor(
            ivy.std(self._ivy_array, axis=axis, keepdims=keepdim)
        )

```
it has previous paddle version and also the wrong supported dtype.

### Steps to Reproduce Bug

go to the ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py this file location and write the test function.

it is not passing any case.

### Environment

wsl2 , ubuntu20.04 , vscode 

### Ivy Version

latest 

### Backend

- [X] NumPy
- [X] TensorFlow
- [X] PyTorch
- [X] JAX

**Comment by samthakur587** [comment]
hii @Mr-Niraj-Kulkarni,

i have added the PR to solve this bug can you please checkout this.

**Comment by srivarshithdaladuli** [comment]
def test_std(self):
    ivy_array = ...  # create an Ivy tensor for testing
    paddle_tensor = paddle_frontend.Tensor(ivy_array)
    ivy_std = ivy.std(ivy_array)
    paddle_std = paddle_tensor.std()
    assert np.allclose(ivy_std, paddle_std.numpy())

**Comment by Aaryan562** [comment]
Hey @samthakur587 there is another bug which I would like you to know in ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_search.py in function top_k. The test cases are not passing could you check that?

**Comment by samthakur587** [comment]
> def test_std(self): ivy_array = ... # create an Ivy tensor for testing paddle_tensor = paddle_frontend.Tensor(ivy_array) ivy_std = ivy.std(ivy_array) paddle_std = paddle_tensor.std() assert np.allclose(ivy_std, paddle_std.numpy())

hii @srivarshithdaladuli thanks for adding your contribution in this PR but the problem here is not in the test function. actual problem in std method is supported dtpye the supported. the std method support the float32 and float64. but here it is in unsupported dtype and in the ivy.std he is not using the unbiased parameter. its using the default value of True for all the case.

thats why i have created this PR in this method. for solving this bug.

thnak you

**Comment by samthakur587** [comment]
> Hey @samthakur587 there is another bug which I would like you to know in ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_search.py in function top_k. The test cases are not passing could you check that?

hii @Aaryan562 sorry for late reply. yeah there is also a bug in the top_k method. so I spent find that. actually while implementing this function. he forget to add the wrapping decorator @to_ivy_arrays_and_back.

use this code to solve the issue.

```python 
@with_supported_dtypes(
    {"2.5.1 and below": ("float32", "float64", "int32", "int64")},
    "paddle",
)
@to_ivy_arrays_and_back
def topk(x, k, axis=None, largest=True, sorted=True, name=None):
    return ivy.top_k(x, k, axis=axis, largest=largest, sorted=sorted)
```
 now is should be pass all the backend. and thanks for asking me.

thank you

**Comment by Aaryan562** [comment]
> > Hey @samthakur587 there is another bug which I would like you to know in ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_search.py in function top_k. The test cases are not passing could you check that?
> 
> hii @Aaryan562 sorry for late reply. yeah there is also a bug in the top_k method. so I spent find that. actually while implementing this function. he forget to add the wrapping decorator @to_ivy_arrays_and_back.
> 
> use this code to solve the issue.
> 
> ```python
> @with_supported_dtypes(
>     {"2.5.1 and below": ("float32", "float64", "int32", "int64")},
>     "paddle",
> )
> @to_ivy_arrays_and_back
> def topk(x, k, axis=None, largest=True, sorted=True, name=None):
>     return ivy.top_k(x, k, axis=axis, largest=largest, sorted=sorted)
> ```
> 
> now is should be pass all the backend. and thanks for asking me.
> 
> thank you

I sometimes wonder how these PR are getting merged. Are the reviewers not checking these before merging lol because there are more such cases where there are frontend end func and not test func or vice versa or taking this scenario where there are bugs or incomplete solutions.
