### ISSUE TITLE
reciprocal_

### ISSUE THREAD

**Issue by samthakur587** [unifyai/ivy#22562]
implementing the reciprocal_ to math paddle frontend

**Comment by rishabgit** [comment]
Hi! Your comment wasn't made correctly, so it wasn't assigned by our bot and someone [else](https://github.com/unifyai/ivy/pull/22824) picked it up instead. Noticed you haven't raised a PR for this yet, so closing it. Hope this helps - https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues 😅
