### ISSUE TITLE
missed word in the docuemtation

### ISSUE THREAD

**Issue by a0m0rajab** [unifyai/ivy#22842]
### Bug Explanation

In this [page](https://unify.ai/docs/ivy/overview/related_work/what_does_ivy_add.html) we have a missing word in the next sentence: `ML models using their “”` we need to fix it. 

![image](https://github.com/unifyai/ivy/assets/18273833/60f1b512-6fbb-4184-8d89-9ac87e964ee5)

### Steps to Reproduce Bug

NA

### Environment

Na

### Ivy Version

NA

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by Pchatain** [comment]
I think the missing word should be infrastructure based on reading their website - https://www.modular.com/

Do you want to go ahead and update the docs @a0m0rajab  and link the PR to this issue?

**Comment by Aryan8912** [comment]
I am working on this issue please assign to me
