### ISSUE TITLE
[Documentation]: Images not rendering 

### ISSUE THREAD

**Issue by yashj8** [unifyai/ivy#23010]
### Path

https://unify.ai/docs/ivy/overview/contributing/setting_up.html#github-codespaces

### Section

Can be seen at multiiple places

### Actual Behavior

Displays the alt link to the image like https://raw.githubusercontent.com/unifyai/unifyai.github.io/main/img/externally_linked/contributing/setting_up/github_codespaces/extension_install.png?raw=true

This link is also unresponsive.

### Expected Behavior

It is supposed to display the image.

### Screenshots

![Screenshot (57)](https://github.com/unifyai/ivy/assets/57638523/344837a6-aac3-4f92-ab6b-aec666e28e09)

**Comment by KareemMAX** [comment]
Hey @yashj8,
Thanks for you report, but things seem to work fine with me:
<img width="762" alt="image" src="https://github.com/unifyai/ivy/assets/16426366/089ba663-ae76-405d-b3d2-b04b011f48e9">

Can you please confirm if it's still not loading on your end?

**Comment by Aryan8912** [comment]
It's working fine, for my side please check properly

**Comment by yashj8** [comment]
In that case it seems to be an issue at my end. (It seems ok in another device of mine)
Thanks!
