### ISSUE TITLE
[Documentation]: Docs mentioning non-existing section

### ISSUE THREAD

**Issue by KareemMAX** [unifyai/ivy#23138]
### Path

https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis:~:text=Try%20to%20implement%20the%20function%20as%20a%20composition%20of%20currently%20present%20ivy%20functions%2C%20as%20explained%20in%20the%20%E2%80%9CTemporary%20Compositions%E2%80%9D%20sub%2Dsection%20of%20the%20Ivy%20Frontends

### Section

Frontend APIs

### Actual Behavior

There is no section called "Temporary Compositions" in [Ivy frontends](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#ivy-frontends).

### Expected Behavior

The documentation need to be updated

**Comment by AnnaTz** [comment]
https://github.com/unifyai/ivy/commit/8237dfec397325f6ae2c66ddb3f68f380f91a671
