### ISSUE TITLE
[Documentation]: <TITLE> ToDo List Issues

### ISSUE THREAD

**Issue by eniola-ajala** [unifyai/ivy#23294]
### Path

https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues

### Section

Who to Ask

### Actual Behavior

The documentation is not grammatically complete and clear.

### Expected Behavior

The documentation is not grammatically complete and clear.

### Screenshots

![B53FDF4A-1426-4A6A-937D-F2A1B280806F](https://github.com/unifyai/ivy/assets/73951563/495602c5-d4d0-4cd7-aedc-54f8c548765a)

Starting the sentence with "Whenever you are starting a discussion" would make it more grammatically complete and clear. 

Here's the revised sentence:

"Whenever you are starting a discussion or creating an issue, you are very welcome to tag members of the Ivy team using '@,' selecting the person you think would be most suitable to interact with, based on the information gained from the above steps."

**Comment by eniola-ajala** [comment]
- [ ] #23294

**Comment by haszankauna** [comment]
Hi @eniola-ajala can I please be assigned this?

**Comment by eniola-ajala** [comment]
Whenever you are starting a discussion or creating an issue, you are very welcome to tag members of the Ivy team using '@,' selecting the person you think would be most suitable to interact with, based on the information gained from the above steps.
