### ISSUE TITLE
Swich nvidia-ml-py3 to nvidia-ml-py

### ISSUE THREAD

**Issue by mattip** [unifyai/ivy#2343]
There is a [dependency](https://github.com/unifyai/ivy/blob/89cf59c35dbf0cc8ff765776d6e3fc7fbbc2b498/requirements.txt#L7) here on nvidia-ml-py3. That library has not seen a release in a while. It also pins its version of pynvml to an older version which [breaks the gpustat package](https://github.com/wookayin/gpustat/pull/107#issuecomment-1189837063). Would it be possible to use nvidia-ml-py instead?

**Comment by jkeane508** [comment]
Hi Matti

Thanks for flagging this issue! I have looked into it and we are going to make this change as soon as possible. I will keep this issue open until it has been merged.

Thanks!
James

**Comment by juliagsy** [comment]
Hello @mattip 

We've made the fix through the linked PR, therefore closing this issue now!

Thanks a lot for your suggestion!
