### ISSUE TITLE
Further directions 

### ISSUE THREAD

**Issue by TruscaPetre** [unifyai/ivy#235]
I stumbled across this project and it seems to me that it has a similarity with ONNX and Onnxruntime but it is much less mature. Maybe you can find a collaboration with ONNX or implement ONNX in ivy?

**Comment by djl11** [comment]
Yes this is definitely something we will explore doing! ONNX is predominantly targeted at runtime portability, whereas we focus on training portability. However, we won't reinvent the wheel, and we'll look for the best ways to integrate the great work of ONNX!
