### ISSUE TITLE
linear

### ISSUE THREAD

**Issue by Winvoker** [unifyai/ivy#2441]

**Comment by Winvoker** [comment]
<img width="1217" alt="Screen Shot 2022-07-29 at 23 29 11" src="https://user-images.githubusercontent.com/45109898/181872361-b424745e-80ef-4841-8eba-2a9b2f5c9398.png">
Is this folder structure okay?

**Comment by pradyyadav** [comment]
> Is this folder structure okay?

@Winvoker, help me with this if you figured it out.

**Comment by Winvoker** [comment]
I am not working on this but they said this folder structure is okay in discord.

**Comment by AnnaTz** [comment]
This was completed in [here](https://github.com/unifyai/ivy/commit/697431724d19f411680276efad6aec9814ffe26b).
