### ISSUE TITLE
[Bug]: Unexpected output type when using `@to_ivy_arrays_and_back` decorator on nested function calls

### ISSUE THREAD

**Issue by akshatvishu** [unifyai/ivy#24873]
### Bug Explanation

Currently, when calling `chisquare` function defined at `ivy/functional/frontends/numpy/random/functions.py` returns a  `ivy.frontends.numpy.ndarray` , which in-turn leads to the error below -when calling other ivy functions on it's output.

```py
ivy.utils.exceptions.IvyBackendException: numpy: mean: Cannot interpret 'ivy.frontends.numpy.dtype('float64')' as a data type
```

### Steps to Reproduce Bug

```py
import ivy
import ivy.functional.frontends.numpy as ivy_np
import numpy as np

ivy.set_numpy_backend()
ivy.seed(seed_value=19650)
np.random.seed(19650)
x = np.random.chisquare(2,4)
y = ivy_np.chisquare(2,4)
print(f"np:{x},np.shape:{x.shape}, dtype:{x.dtype}")
print(f"ivy:{y},ivy.shape:{y.shape}, dtype:{y.dtype}")
"""
np:[3.58525856 5.82353171 0.76664563 2.51713281],np.shape:(4,), dtype:float64
ivy:ivy.frontends.numpy.ndarray([0.35762059, 1.49176801, 0.06850934, 2.18534521]),ivy.shape:ivy.Shape(4,), dtype:ivy.frontends.numpy.dtype('float64')
"""

```
This causes problem when you want to call other ivy `fn` with the output  of `ivy_np.chisquare` as `ivy.frontends.numpy.dtype('float64')` is not a **passable/valid**  `dtype` to pass onto an ivy fn.  For example:-

```py
# continuing from above example:
print(f"np:{x},np.shape:{x.shape}, dtype:{x.dtype}")
print(f"ivy:{y},ivy.shape:{y.shape}, dtype:{y.dtype}")
print(np.mean(x))  # this works
print(np.var(x))   # this works
print("ivy")
print(ivy.mean(y)) # this will throw error
print(ivy.var(y)) # this will throw error
```
will raise the following `error`:
```py
# error:
Traceback (most recent call last):
  File "/workspaces/ivy/useless.py", line 46, in <module>
    print(ivy.mean(y))
  File "/workspaces/ivy/ivy/utils/exceptions.py", line 364, in _handle_exceptions
    _handle_exceptions_helper(e, ivy_exception)
  File "/workspaces/ivy/ivy/utils/exceptions.py", line 368, in _handle_exceptions_helper
    raise cls(fn.__name__, str(e), include_backend=True)
ivy.utils.exceptions.IvyBackendException: numpy: mean: Cannot interpret 'ivy.frontends.numpy.dtype('float64')' as a data type
```

The problem probably lies in how we've defined these function at numpy frontend at [frontends/numpy/random/functions.py](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/numpy/random/functions.py)

[numpy_frontend.random.chisquare](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/numpy/random/functions.py#L35)
```py
@to_ivy_arrays_and_back
@from_zero_dim_arrays_to_scalar
def chisquare(df, size=None):
    df = ivy.array(df)  # scalar ints and floats are also array_like
    if ivy.any(df <= 0):
        raise ValueError("df <= 0")

    # ivy.gamma() throws an error if both alpha is an array and a shape is passed
    # so this part broadcasts df into the shape of `size`` first to keep it happy.
    if size is not None:
        df = df * ivy.ones(size)

    return ivy.gamma(df / 2, 2, dtype="float64")
```

and [numpy_frontend.random.gamma](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/numpy/random/functions.py#L84)

```py
@to_ivy_arrays_and_back
@from_zero_dim_arrays_to_scalar
def gamma(shape, scale=1.0, size=None):
    return ivy.gamma(shape, scale, shape=size, dtype="float64")

```

My **intuition** is that  since we're calling `ivy.gamma` inside our ` chisquare` and since the `gamma` function already calls the `@to_ivy_arrays_and_back` decorator , using the `@to_ivy_arrays_and_back` decorator again at `chisquare` defination is causing it to return `ivy.frontends.numpy.ndarray` instead of `ivy.array` which is the **core cause** of this whole issue.

### Proposed Solution:
- remove  `@to_ivy_arrays_and_back` decorator from  `chisquare` defination at numpy frontend.

```py
# after removing the decorator:
"""
# the modified fn defination looks like:
@from_zero_dim_arrays_to_scalar
def chisquare(df, size=None):
    df = ivy.array(df)  # scalar ints and floats are also array_like
    if ivy.any(df <= 0):
        raise ValueError("df <= 0")

    # ivy.gamma() throws an error if both alpha is an array and a shape is passed
    # so this part broadcasts df into the shape of `size`` first to keep it happy.
    if size is not None:
        df = df * ivy.ones(size)

    return ivy.gamma(df / 2, 2, dtype="float64")
"""
import ivy
import ivy.functional.frontends.numpy as ivy_np
import numpy as np

ivy.set_numpy_backend()
ivy.seed(seed_value=19650)
np.random.seed(19650)
x = np.random.chisquare(2,4)
y = ivy_np.chisquare(2,4)
print(f"np:{x},np.shape:{x.shape}, dtype:{x.dtype}")
print(f"ivy:{y},ivy.shape:{y.shape}, dtype:{y.dtype}")

"""
# we're now returning ivy.array
np:[3.58525856 5.82353171 0.76664563 2.51713281],np.shape:(4,), dtype:float64
ivy:ivy.array([0.35762059, 1.49176801, 0.06850934, 2.18534521]),ivy.shape:ivy.Shape(4,), dtype:float64
"""

```

### Environment

linux+docker+vscode

### Ivy Version

v1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

CPU

**Comment by a0m0rajab** [comment]
Thanks for opening this bug, I just want to get the full user story, were you trying to develop something with Ivy framework? or did you encounter this through contributing?

**Comment by akshatvishu** [comment]
> Thanks for opening this bug, I just want to get the full user story, were you trying to develop something with Ivy framework? or did you encounter this through contributing?

Actually someone ask me to check their `PR` at ivy discord (as they were facing this bug) and I tested it locally and reach this conclusion.

You can look at discord discussion for this at here : [LINK](https://discord.com/channels/799879767196958751/1028707030199980063/1153678230432256094)

**Comment by akshatvishu** [comment]
Also, I notice that currently almost all of the `functions` defined at [frontends/numpy/random/functions.py](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/numpy/random/functions.py) are returning `ivy.frontends.numpy.ndarray` , should be use `@inputs_to_ivy_arrays` decorator instead of `@to_ivy_arrays_and_back` in all of them or returning `ivy.frontends.numpy.ndarray` instances is the desired behaviour?

**Comment by a0m0rajab** [comment]
Thanks for the information, to be honest I think it's better to ask that question in the PR, I do not have full context about the technical background here.
