### ISSUE TITLE
max

### ISSUE THREAD

**Issue by leroberto8** [unifyai/ivy#2491]
To contribue .

**Comment by leroberto8** [comment]
#2491

**Comment by leroberto8** [comment]
def_max():
	li[]
	max=li[0]
	 i=0
	for i in range(0 len(li)):
		if li[i]<li[i+1]:
			max=li[i+1]
	print(max)

**Comment by 1Doomdie1** [comment]
what was the issue that you took this function from?

**Comment by leroberto8** [comment]
Yes i took issue max from Unify Ai/ivy
Best regards,
Robert Mbogni


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1Doomdie1** [comment]
Maybe my question was unclear.
I am asking what was the issues from where you took this function from.
Can you please provide the issue ID so I can allocate this function to you?
Thank you.

**Comment by leroberto8** [comment]
https://github.com/unifyai/ivy/issues Update ivy_array.rst #2493   Best regards/Bien cordialementRobert MbogniTechnical support Engineer From: DoomdieSent: Monday, 1 August 2022 12:06To: unifyai/ivyCc: leroberto8; AuthorSubject: Re: [unifyai/ivy] max (Issue #2491) Maybe my question was unclear.I am asking what was the issues from where you took this function from.Can you please provide the issue ID so I can allocate this function to you?Thank you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com

**Comment by 1Doomdie1** [comment]
Can you please provide the issue ID from where this function was chosen?
Thank you!

**Comment by leroberto8** [comment]
#2491
it was max fuction please.

**Comment by 1Doomdie1** [comment]
Hey, please follow [this](https://www.youtube.com/watch?v=wBKTOGmwfbo) video to clarify the confusion.

**Comment by leroberto8** [comment]
Please i alredy wash the Video before me someone was there 
i follow what was on video.

**Comment by leroberto8** [comment]
https://github.com/unifyai/ivy/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by leroberto8** [comment]
Someone was on it before me please.

**Comment by VedPatwardhan** [comment]
Hey @leroberto8, the process of getting a function assigned has been specified in the [docs](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) please go through them and get a function assigned accordingly. 
1. Basically, you have to go through the issues in the [ToDo lists](https://github.com/unifyai/ivy/issues?q=is%3Aopen+is%3Aissue+label%3AToDo). 
2. All these issues contain a list of issues inside them, some of the issues marked as completed in purple, some are marked as ones currently being worked on in green and the others are without a color which haven't been assigned yet. 
3. You need to go through the non-coloured ones, select the one you want to work on and then get it assigned to you by creating an issue with that function name and then typing `- [ ] #Issue_number` in the chat of the [ToDo List](https://github.com/unifyai/ivy/issues?q=is%3Aopen+is%3Aissue+label%3AToDo) you've picked the function from.
4. In some time, you'll be able to see the function you've selected as marked in green and getting linked to the issue that you created. If you create an issue and not type `- [ ] #Issue_number` in the chat of the [ToDo List](https://github.com/unifyai/ivy/issues?q=is%3Aopen+is%3Aissue+label%3AToDo), that issue would still remain unassigned on the ToDo list where someone else could get it assigned.
5. Once you see the issue linked on the ToDo list, you can start working on the issue based on the task you're doing out of the [Open Tasks](https://lets-unify.ai/ivy/contributing/4_open_tasks.html) and create a PR, the team will take a look at it.

**Comment by leroberto8** [comment]
that was
# 3912
