### ISSUE TITLE
cos

### ISSUE THREAD

**Issue by gurkankilicaslan** [unifyai/ivy#2508]
#1525

**Comment by dgoel200113** [comment]
I will like to work on this, Kindly assign it.

**Comment by gurkankilicaslan** [comment]
> I will like to work on this, Kindly assign it.

Hello @dgoel200113  if you follow the contribution guide you can be able to know how to pick an issue to work on and reserve it for you. Because I opened this issue and linked it to the issue I wanted to implement the function for and I completed it actually.
Thanks
