### ISSUE TITLE
set_queue_timeout

### ISSUE THREAD

**Issue by AbdulrahmanHammouda** [unifyai/ivy#2549]

**Comment by 1Doomdie1** [comment]
Can you provide the issue ID from where you took this function from?
Thank you!

**Comment by AbdulrahmanHammouda** [comment]
[ ] #2549

**Comment by AbdulrahmanHammouda** [comment]
[ ] #2549.

**Comment by 1Doomdie1** [comment]
This is the ID of this issue, I need the the issue ID of the issue from where you choose this function.

**Comment by AbdulrahmanHammouda** [comment]
I got it from Reformat general #791. Sorry for the confusion.

**Comment by 1Doomdie1** [comment]
Thank you! :D
