### ISSUE TITLE
[Feature Request]: Add `isort` as a pre-commit hook.

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#25714]
**Is your feature request related to a problem? Please describe.**
I found that the [isort](https://github.com/PyCQA/isort) check is very common (recommended) and used in most of the big `Python` based organizations including [dask](https://github.com/dask/dask/blob/main/.pre-commit-config.yaml), [jina](https://github.com/jina-ai/jina/blob/master/.pre-commit-config.yaml), [mindsbd](https://github.com/Sai-Suraj-27/mindsdb/blob/staging/.pre-commit-config.yaml), [pandas](https://github.com/Sai-Suraj-27/pandas/blob/main/.pre-commit-config.yaml#L72), etc. So, it will be nice to have it in our codebase.

**Benefits**
It automatically rearranges imports in a Python file based on the specified rules and settings to ensure consistent and standardized import organization.

Additionally, `isort` hook follows specific guidelines for line length and line wrapping to keep imports within a specified character limit, promoting readability and maintainability. By following these rules, `isort` helps maintain a clean and standardized import layout across your Python codebase, making it easier to read, and understand.

**Describe the solution you'd like**
The solution would be to update the `.pre-commit-config.yaml` file by adding this [check](https://github.com/PyCQA/isort). Similar to the checks I introduced in this [Pull Request](https://github.com/unifyai/ivy/pull/22974).

**Describe alternatives you've considered**

**Additional context**

**Comment by hirwa-nshuti** [comment]
Hey @Sai-Suraj-27 

Thanks for the suggestion, the team was extensively working on a similar issue, let's see what they think about it.
cc @KareemMAX and @jshepherd01
