### ISSUE TITLE
Fix pointwise_ops.test_torch_igamma

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#25764]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6361237144/job/17275530099"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6361237144/job/17275530099"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6361237144/job/17275530099"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6361237144/job/17275530099"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6361237144/job/17275530099"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by Aryan8912** [comment]
please assign to me so I am start working on it
