### ISSUE TITLE
Remove duplicate `imports` and `functions`

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#25781]
At some places in the codebase un-necessary [reimports](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/reimported.html) are present, I found them by using the [`ruff`](https://github.com/astral-sh/ruff) tool. These can be removed.
like in the following files:

[ivy\functional\frontends\scipy\__init__.py](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/scipy/__init__.py)
line 18 & 19 have the same import.

[ivy_tests\test_ivy\test_frontends\test_jax\test_numpy\test_creation.py](https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_creation.py)
The function `def test_jax_numpy_in1d` is repeated twice from line 839 and line 875.
Edit: This is just fixed through this PR (https://github.com/unifyai/ivy/pull/25786).

**Comment by muhammadhammad-tech** [comment]
can you assign me this issue

**Comment by Sai-Suraj-27** [comment]
@muhammadhammad-tech I see that both these problems are fixed by the very recent PRs that got merged today (https://github.com/unifyai/ivy/pull/25786, and https://github.com/unifyai/ivy/pull/25717). So, I am closing this issue as completed.

**Comment by Sai-Suraj-27** [comment]
@muhammadhammad-tech sorry, I have already made a PR for this. Also, I am not a maintainer to assign issues to new contributors. I am also a contributor 😄.
