### ISSUE TITLE
eye

### ISSUE THREAD

**Issue by HotzingTone** [unifyai/ivy#258]
Function [ivy.eye](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.eye.html#signatures.creation_functions.eye) needs to be created first in order to run [test_matrix_power](https://github.com/data-apis/array-api-tests/blob/511929cebea939f137f910b4a68ddbce42f69611/array_api_tests/test_linalg.py#L353)

_Originally posted by @HotzingTone in https://github.com/unifyai/ivy/issues/153#issuecomment-1046334475_

**Comment by Archymade** [comment]
Is someone already working on this? If not, may this function be assigned to me?
