### ISSUE TITLE
wrong docstring examples for static_clip

### ISSUE THREAD

**Issue by danielmunioz** [unifyai/ivy#2581]
HI! Sorry, this function was merged in https://github.com/unifyai/ivy/issues/1624, but the example using multiple `ivy.Container` inputs over at https://github.com/unifyai/ivy/blob/master/ivy/container/manipulation.py#L999, uses Container. static_roll instead of Container. static_clip, also the example doesn't work even when switching to the correct function.

**Comment by jiahanxie353** [comment]
> HI! Sorry, this function was merged in #1624, but the example using multiple `ivy.Container` inputs over at https://github.com/unifyai/ivy/blob/master/ivy/container/manipulation.py#L999, uses Container. static_roll instead of Container. static_clip, also the example doesn't work even when switching to the correct function.

Thanks for pointing out! 
What do you mean by `the example doesn't work even when switching to the correct function`. Could you elaborate?

**Comment by danielmunioz** [comment]
HI! I meant that if you just change `ivy.Container.static_roll` to `ivy.Container.static_clip`, the example still doesn't work, meaning that the whole "With multiple :code:`ivy.Container` inputs:" example is wrong not only the `static_roll` part.
The whole thing was probably just copied and pasted from somewhere else.

**Comment by jiahanxie353** [comment]
> HI! I meant that if you just change `ivy.Container.static_roll` to `ivy.Container.static_clip`, the example still doesn't work, meaning that the whole "With multiple :code:`ivy.Container` inputs:" example is wrong not only the `static_roll` part. The whole thing was probably just copied and pasted from somewhere else.

Yeah, but if try to run 
```
x = ivy.Container(a=ivy.array([0., 1., 2.]),
                  b=ivy.array([3., 4., 5.]))
x_min = ivy.Container(a=1, b=-1)
x_max = ivy.Container(a=1, b=-1)

y = ivy.Container.static_clip(x, x_min, x_max)
```
and print the result, it's the same as 
```
{
    a: ivy.array([1., 1., 1.]),
    b: ivy.array([-1., -1., -1.])
}
```
Are you suggesting that  `x_max = -1` but all values in the leaf `b=ivy.array([3., 4., 5.])` are larger than 1 does not make sense?

**Comment by danielmunioz** [comment]
Sorry, but it doesn't work, the `min` and `max` value for the `a` and `b` containers are the same, hence the clip operation cannot be performed.
I believe it should return an `Assertion Error`.

**Comment by jiahanxie353** [comment]
> Sorry, but it doesn't work, the `min` and `max` value for the `a` and `b` containers are the same, hence the clip operation cannot be performed. I believe it should return an `Assertion Error`.
> 
> Did you try running that code on the latest ivy commit?

Yes, you are right, `Assertion Error` occurs.
Yes, I tried last time and it was fine. Now I try again and it throws Error. I'm not sure about the inconsistent outputs, but thanks very much for pointing out! I will fix this docstring :)

**Comment by zaeemansari70** [comment]
Hey! Thank you soo much for contributing to ivy! 🙂
Thanks for pointing out the problem in the `docstring`, it's fixed now! 

We hope you contribute to Ivy in the future as well! ✨
