### ISSUE TITLE
stable_divide

### ISSUE THREAD

**Issue by Ajisco** [unifyai/ivy#2585]
Add stable_divide function to numpy frontend.

**Comment by 1Doomdie1** [comment]
Can you provide the issue ID from where you took this function?
Thank you!

**Comment by Ajisco** [comment]
It's a new issue I just opened.

**Comment by 1Doomdie1** [comment]
Please watch [this](https://www.youtube.com/watch?v=wBKTOGmwfbo) video for more clariffication.
Thank you!

**Comment by Ajisco** [comment]
Thanks.
I'll act accordingly.
Kindly delete this.

**Comment by Ajisco** [comment]
However, I contributed to an issue that wasn't assigned initially an got rejected only to fin out someone hs been working on it.
It wasn't assigned though.
