### ISSUE TITLE
tanh

### ISSUE THREAD

**Issue by kanakmi** [unifyai/ivy#2600]
Hi team
I am willing to add tanh function to the Tensorflow frontend. I have checked that there are no open issues and pull requests for the same.

**Comment by 1Doomdie1** [comment]
Can you please provide the main issue ID from where you took this function?
Thank you!

**Comment by kanakmi** [comment]
Hey @1Doomdie1 
I know this function is not listed in one of the main issue IDs but can I still add it? Because eventually, it has to be added right?

**Comment by kanakmi** [comment]
Hey @1Doomdie1 
This function is actually a part of #1565 
I will be making a PR soon.
Meanwhile, please change the labels to Single Function and TensorFlow Frontend.
