### ISSUE TITLE
Fix functions.test_numpy_noncentral_chisquare

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#26228]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6353956708"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6353956708"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6353956708"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6353956708"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6353956708"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by BowNicole** [comment]
https://github.com/unifyai/ivy/issues/26228
