### ISSUE TITLE
[Bug]: Discrepancy in `not_equal` API for paddle vs rest of the frameworks(NumPy, TensorFlow, PyTorch, JAX)

### ISSUE THREAD

**Issue by akshatvishu** [unifyai/ivy#26234]
### Description:

We have observed a discrepancy in the behavior of the [paddle.not_equal](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/not_equal_en.html#not-equal) function between `PaddlePaddle` and other major frameworks like` NumPy, TensorFlow, PyTorch, and JAX` , specifically when comparing floating-point numbers. This is leading any instances of it  to fail for all frontend implementation at ivy paddle frontend.

### The origin of the issue:
`PaddlePaddle` introduces a tolerance of `1e-8` for floating-point comparisons within the` EqualFunctor` and `NotEqualFunctor `structures, which results in treating close floating-point numbers as equal, and hence, `not_equal` may return unexpected results and potential issues, especially when precision is crucial.

**code for `EqualFunctor` and `NotEqualFunctor` :** [LINK](https://github.com/PaddlePaddle/Paddle/blob/36275716ad24d1391f0a69005b79fe28382a8707/paddle/phi/kernels/funcs/compare_functors.h#L51)
```py
// PaddlePaddle's logic introduces tolerance, treating close floating-point numbers as equal
return static_cast<OutT>(fabs(static_cast<double>(a - b)) < 1e-8);

```

### Ivy Adjustment at  Paddle Backend:
Ivy engineers are aware of this behavior discrepancy in PaddlePaddle's `not_equal` operation. To address this, the` not_equal` implementation in Ivy’s PaddlePaddle backend has been modified as follows:-  
[ivy_paddle_backend.not_equal](https://github.com/unifyai/ivy/blob/main/ivy/functional/backends/paddle/elementwise.py#L700) 
```py
return paddle.logical_not(paddle_backend.equal(x1, x2))
```

### Steps to Reproduce the Error:

Now, making changes at Ivy's paddle backend to rectify this discrepancy with `not_equal` API has lead to it failing for `paddle_frontend` implementation of `not_equal`  since it compares against paddle native `not_equal` and not our Ivy' paddle backend.

Now, while test for  Ivy paddle backend `not_equal ` will pass successfully:
```py
# to run the test 
python3 -m pytest --num-examples=100 ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py::test_not_equal -B=paddle
```
![image](https://github.com/unifyai/ivy/assets/33392262/e48cfcd4-2a00-40a6-a723-62200a297015)

It will fail for all instance of `not_equal` implemented for paddle frontend at Ivy:
**For `tensor`  instance**  (https://github.com/unifyai/ivy/pull/25936)
```py
python3 -m pytest --num-examples=100 ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_not_equal
```
![image](https://github.com/unifyai/ivy/assets/33392262/aa8e30d5-06e9-49b6-9e06-0da3e4d3c272)

for [ivy_paddle_frontend.not_equal](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/paddle/logic.py#L285)  (which is already present at ivy codebase): 

```py
python3 -m pytest --num-examples=100 ivy_tests/test_ivy/test_frontends/test_paddle/test_logic.py::test_paddle_not_equal

```
![image](https://github.com/unifyai/ivy/assets/33392262/d14eca20-046d-4766-9226-c6681f179ea1)

### Paddle `not_equal` API vs rest of the frameworks `not_equal` API:

`NumPy, TensorFlow, PyTorch, and JAX` exhibit consistent behavior for the `not_equal` operation, performing a straightforward comparison between two numbers without any tolerance for floating-point inaccuracies.

```py

import jax.numpy as jnp
import ivy
import tensorflow as tf
import torch
import paddle
import ivy.functional.backends.paddle as pd_b

a = paddle.to_tensor(-7.450581e-09, dtype=paddle.float32)
b = paddle.to_tensor(-1.1175871e-08, dtype=paddle.float32)
# b = paddle.to_tensor(-2.7e-08, dtype=paddle.float32)
# Compute not_equal using PaddlePaddle
paddle_result = paddle.not_equal(a, b)
print("PaddlePaddle not_equal result:", bool(paddle_result))
ivy = pd_b.not_equal(a,b)
print("IVY modified Paddle not_equal result:", bool(ivy))
# Convert tensors to NumPy arrays for comparison
a_np = np.array(-7.450581e-09, dtype=np.float32)
b_np = np.array(-1.1175871e-08, dtype=np.float32)

jnp1 = jnp.array(-7.450581e-09, dtype=jnp.float32)
jb_np = jnp.array(-1.1175871e-08, dtype=jnp.float32)
c = jnp.not_equal(jnp1, jb_np)
print("Jax not_equal result:", c)

a = torch.tensor(-7.450581e-09, dtype=torch.float32)
b = torch.tensor(-1.1175871e-08, dtype=torch.float32)
c = torch.ne(a,b)
print("torch not_equal result:", c)

a = tf.constant(-7.450581e-09, dtype=tf.float32)
b = tf.constant(-1.1175871e-08, dtype=tf.float32)
c = tf.math.not_equal(a,b)
print("TensorFlow not_equal result:", c)

# Compute not_equal using NumPy
numpy_result = np.not_equal(a_np, b_np)
print("NumPy not_equal result:", numpy_result)

# Check if the absolute difference is less than 1e-8
diff = np.abs(a_np - b_np)
print("Absolute difference between a and b:", diff)
print("Difference is less than 1e-8:", diff < 1e-8)

"""
PaddlePaddle not_equal result: False
IVY modified Paddle not_equal result: True
Jax not_equal result: True
torch not_equal result: tensor(True)
TensorFlow not_equal result: tf.Tensor(True, shape=(), dtype=bool)
NumPy not_equal result: True
Absolute difference between a and b: 3.7252903e-09
Difference is less than 1e-8: True
"""

```

**Comment by AnnaTz** [comment]
As you said `ivy.not_equal` has been implemented in a way that achieves consistent results across all backends, with its behavior being different from paddle's. 
Hence, we need a compositional approach to implement the paddle frontend function.
I don't think there is a bug anywhere though, is there?

**Comment by akshatvishu** [comment]
I will be closing this  issue  as the appropriate changes has be added to `paddle frontend` for `not_equal` API to emulate native `paddle.not_equal` by @AryanSharma21.
