### ISSUE TITLE
bessel_i0

### ISSUE THREAD

**Issue by TobeTek** [unifyai/ivy#26241]

**Comment by DirectriX01** [comment]
@TobeTek does your PR add bessel_i0e(mentioned in PR) or bessel_i0(mentioned in issue)

**Comment by TobeTek** [comment]
> @TobeTek does your PR add bessel_i0e(mentioned in PR) or bessel_i0(mentioned in issue)

Ahah. A mixup on my part @DirectriX01 . I'll make a PR for `bessel_i0` now.
