### ISSUE TITLE
[Bug]: `ivy.utils.clean_and_fetch_binaries()` not working!

### ISSUE THREAD

**Issue by akshatvishu** [unifyai/ivy#26257]
### Bug Explanation

Currently, It seems like ivy has added some new binaries into their code-base and throws a warning if they're not present in user's system with a message to update it 

But when I run the cmd given in the message to download the new binaries it leads to the following error below:
cmd to run:
```py
ivy.utils.cleanup_and_fetch_binaries() 
```
```py
WARNING:root:   Some binaries seem to be missing in your system. This could be either because we don't have compatible binaries for your system or that newer binaries were available. In the latter case, calling ivy.utils.clean_and_fetch_binaries() should fetch the binaries binaries. Feel free to create an issue on https://github.com/unifyai/ivy.git in case of the former

WARNING:root:
Following are the supported configurations :
compiler : cp38-none-manylinux_2_17_x86_64, cp310-none-manylinux_2_17_x86_64
engines : cp310-none-manylinux_2_17_x86_64

WARNING:root:   ivy/compiler/_compiler.so not found.
WARNING:root:   ivy/compiler/utils/CC.so not found.
WARNING:root:   ivy/compiler/utils/CD.so not found.
WARNING:root:   ivy/compiler/utils/CI.so not found.
WARNING:root:   ivy/compiler/utils/CL.so not found.
WARNING:root:   ivy/compiler/utils/CM.so not found.
WARNING:root:   ivy/compiler/utils/CV.so not found.
WARNING:root:   ivy/compiler/utils/CX.so not found.
WARNING:root:   ivy/compiler/utils/C.so not found.
WARNING:root:   ivy/compiler/utils/DC.so not found.
WARNING:root:   ivy/compiler/utils/DD.so not found.
WARNING:root:   ivy/compiler/utils/DI.so not found.
WARNING:root:   ivy/compiler/utils/DL.so not found.
WARNING:root:   ivy/compiler/utils/DM.so not found.
WARNING:root:   ivy/compiler/utils/DV.so not found.
WARNING:root:   ivy/compiler/utils/DX.so not found.
WARNING:root:   ivy/compiler/utils/D.so not found.
WARNING:root:   ivy/compiler/utils/IC.so not found.
WARNING:root:   ivy/compiler/utils/ID.so not found.
WARNING:root:   ivy/compiler/utils/II.so not found.
WARNING:root:   ivy/compiler/utils/IL.so not found.
WARNING:root:   ivy/compiler/utils/IM.so not found.
WARNING:root:   ivy/compiler/utils/IV.so not found.
WARNING:root:   ivy/compiler/utils/IX.so not found.
WARNING:root:   ivy/compiler/utils/I.so not found.
WARNING:root:   ivy/compiler/utils/LC.so not found.
WARNING:root:   ivy/compiler/utils/LD.so not found.
WARNING:root:   ivy/compiler/utils/LI.so not found.
WARNING:root:   ivy/compiler/utils/LL.so not found.
WARNING:root:   ivy/compiler/utils/LM.so not found.
WARNING:root:   ivy/compiler/utils/LV.so not found.
WARNING:root:   ivy/compiler/utils/LX.so not found.
WARNING:root:   ivy/compiler/utils/L.so not found.
WARNING:root:   ivy/compiler/utils/MI.so not found.
WARNING:root:   ivy/compiler/utils/ML.so not found.
WARNING:root:   ivy/compiler/utils/MV.so not found.
WARNING:root:   ivy/compiler/utils/MX.so not found.
WARNING:root:   ivy/compiler/utils/M.so not found.
WARNING:root:   ivy/compiler/utils/VC.so not found.
WARNING:root:   ivy/compiler/utils/VD.so not found.
WARNING:root:   ivy/compiler/utils/VI.so not found.
WARNING:root:   ivy/compiler/utils/VL.so not found.
WARNING:root:   ivy/compiler/utils/VM.so not found.
WARNING:root:   ivy/compiler/utils/VV.so not found.
WARNING:root:   ivy/compiler/utils/VX.so not found.
WARNING:root:   ivy/compiler/utils/V.so not found.
WARNING:root:   ivy/compiler/utils/XC.so not found.
WARNING:root:   ivy/compiler/utils/XD.so not found.
WARNING:root:   ivy/compiler/utils/XI.so not found.
WARNING:root:   ivy/compiler/utils/XL.so not found.
WARNING:root:   ivy/compiler/utils/XM.so not found.
WARNING:root:   ivy/compiler/utils/XV.so not found.
WARNING:root:   ivy/compiler/utils/XX.so not found.
WARNING:root:   ivy/compiler/utils/X.so not found.
WARNING:root:   ivy/engines/ivy2xla.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/activations.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/creation.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/elementwise.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/general.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/layers.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/linear_algebra.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/manipulation.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/norms.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/stateful_activations.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/stateful_layers.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/stateful_norms.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/statistical.so not found.
WARNING:root:   ivy/engines/XLA/rust_api/python_frontend/xla_core.so not found.

WARNING:jax._src.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Cleaning up existing binaries...
Downloading new binaries...
Traceback (most recent call last):
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 1031, in _send_output
    self.send(msg)
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 969, in send
    self.connect()
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 1441, in connect
    super().connect()
  File "/opt/miniconda/envs/multienv/lib/python3.10/http/client.py", line 940, in connect
    self.sock = self._create_connection(
  File "/opt/miniconda/envs/multienv/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/miniconda/envs/multienv/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/ivy/useless.py", line 148, in <module>
    ivy.utils.cleanup_and_fetch_binaries()
  File "/workspaces/ivy/ivy/utils/binaries.py", line 97, in cleanup_and_fetch_binaries
    response = request.urlopen(
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/miniconda/envs/multienv/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
```

I ran some additional command for better context:
```bash
uname -m
"""
x86_64
"""

lsb_release -a

"""
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

"""
ldd --version
"""
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
"""

```

### Steps to Reproduce Bug

```py
ivy.utils.clean_and_fetch_binaries()
```

Another thing I notice is that :
```py
                try:
                    response = request.urlopen(
                        "https://github.com/unifyai/binaries/raw/"
                        f"{version}/{search_path}",
                        timeout=40,
                    )
```
This `url:https://github.com/unifyai/binaries/raw/` results in `error 404`:
![image](https://github.com/unifyai/ivy/assets/33392262/8618a589-1c89-4798-a53b-c4582958a46e)

### Environment

linux + docker + vscode

### Ivy Version

v1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

CPU

**Comment by lucasalavapena** [comment]
Hi @akshatvishu , Thanks for creating the report. 

I could be wrong, but this looks to me like an issue related to ports and docker, you are not getting an access denied error (HTTP code 403) which would suggest you do not have access to the resources. The error you got was `OSError: [Errno 99] Cannot assign requested address`, which I believe happens because since you are in a docker container the desired host/port is not exposed? At least when I go into the unifyai/ivy docker (without any port mapping) container inside codespaces, I cant even ping google or 1.1.1.1, in the actual codespaces I can use the `ivy.utils.cleanup_and_fetch_binaries() ` without a problem.

**Comment by akshatvishu** [comment]
> Hi @akshatvishu , Thanks for creating the bug report.
> 
> I could be wrong, but this looks to me like an issue related to ports and docker, you are not getting an access denied error (HTTP code 403) which would suggest you do not have access to the resources. The error you got was `OSError: [Errno 99] Cannot assign requested address`, which I believe happens because since you are in a docker container the desired host/port is not exposed? At least when I go into the unifyai/ivy docker (without any port mapping) container inside codespaces, I cant even ping google or 1.1.1.1, in the actual codespaces I can use the `ivy.utils.cleanup_and_fetch_binaries() ` without a problem.

Hey @lucasalavapena , thanks of looking into it , I don;t have much experience with docker so, can't really comment on that but I found another potential cause of error at:

```py
# path: ivy/utils/binaries.py/ cleanup_and_fetch_binaries(clean=True) :
                try:
                    response = request.urlopen(
                        "https://github.com/unifyai/binaries/raw/"
                        f"{version}/{search_path}",
                        timeout=40,
                    )
```
the `url` is throwing `404 `

**Comment by lucasalavapena** [comment]
> > Hi @akshatvishu , Thanks for creating the bug report.
> > I could be wrong, but this looks to me like an issue related to ports and docker, you are not getting an access denied error (HTTP code 403) which would suggest you do not have access to the resources. The error you got was `OSError: [Errno 99] Cannot assign requested address`, which I believe happens because since you are in a docker container the desired host/port is not exposed? At least when I go into the unifyai/ivy docker (without any port mapping) container inside codespaces, I cant even ping google or 1.1.1.1, in the actual codespaces I can use the `ivy.utils.cleanup_and_fetch_binaries() ` without a problem.
> 
> Hey @lucasalavapena , thanks of looking into it , I don;t have much experience with docker so, can't really comment on that but I found another potential cause of error at:
> 
> ```python
> # path: ivy/utils/binaries.py/ cleanup_and_fetch_binaries(clean=True) :
>                 try:
>                     response = request.urlopen(
>                         "https://github.com/unifyai/binaries/raw/"
>                         f"{version}/{search_path}",
>                         timeout=40,
>                     )
> ```
> 
> the `url` is throwing `404 `

No worries! What url is giving you a 404?  https://github.com/unifyai/binaries/ works for me even in incognito.

**Comment by akshatvishu** [comment]
> > the `url` is throwing `404 `
> 
> No worries! What url is giving you a 404? https://github.com/unifyai/binaries/ works for me even in incognito.


`"https://github.com/unifyai/binaries/raw/" present here <https://github.com/unifyai/ivy/blob/main/ivy/utils/binaries.py#L98>

**Comment by akshatvishu** [comment]
> > > > the `url` is throwing `404 `
> > > 
> > > 
> > > No worries! What url is giving you a 404? https://github.com/unifyai/binaries/ works for me even in incognito.
> > 
> > 
> > This url: `https://github.com/unifyai/binaries/raw/` present at https://github.com/unifyai/ivy/blob/main/ivy/utils/binaries.py#L98
> > ![image](https://user-images.githubusercontent.com/33392262/271294896-ad58a6cc-9d68-413e-8835-371c2bc8ba80.png)
> 
> That is not the full url it is visting, it would be f"[https://github.com/unifyai/binaries/raw/{version}/{search_path}](https://github.com/unifyai/binaries/raw/%7Bversion%7D/%7Bsearch_path%7D)" if you put it on one line, so it depends on the version and search path.
> 
> For example in the path https://github.com/unifyai/binaries/blob/main/compiler/CC_cp310-none-manylinux_2_17_x86_64.so , if you instead use https://github.com/unifyai/binaries/raw/main/compiler/CC_cp310-none-manylinux_2_17_x86_64.so (notice that the url now has raw in it) you download that file. So all this is doing is finding the right path to download the binary.
> 
> I am still fairly convinced the issue is just your docker setup. Try to use [codespaces](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#github-codespaces) if you do not want to deal with fixing it, it is awesome.

I ran of my free quota for `codespace` so can;t use it but I found something else:

when I use my local network , my connection works alright from inside my docker (checked with pinging google), but when I try to download the above binary file manually , it throws:
![image](https://github.com/unifyai/ivy/assets/33392262/de9cfae3-9576-4081-ada1-dbb0697d2b3b)

But if I use a `VPN` (my docker network doesn't work) but the binary file is installed in seconds!
