### ISSUE TITLE
any

### ISSUE THREAD

**Issue by ajaysai6601** [unifyai/ivy#2626]
[ ] # Issue_num

**Comment by ajaysai6601** [comment]
tracked in # 758

**Comment by ajaysai6601** [comment]
Reformat utility # 758

**Comment by 1Doomdie1** [comment]
Hey, thank you for contributing.
This function has already been allocated to someone but it looks like there was no update or PR opened.
With that in mind if there will be no updates in the next 24h then I'll re-allocate the function to you!
