### ISSUE TITLE
[Bug]: JAX frontends don't work with jax._src.prng.PRNGKeyArrayImpl

### ISSUE THREAD

**Issue by Sam-Armstrong** [unifyai/ivy#26386]
### Bug Explanation

This minimal example shows that keys generated with jax.random.PRNGKey work fine with the JAX frontends, but keys generated with jax.random.key do not (but both work fine with the original jax function).

```
import jax
import ivy.functional.frontends.jax as jax_frontend

# works
key = jax.random.PRNGKey(42)
print('key type', type(key))
new_key_orig = jax.random.fold_in(key, 1)
new_key_front = jax_frontend.random.fold_in(key, 1)

# doesn't work
key = jax.random.key(seed=42)
print('key type', type(key))
new_key_orig = jax.random.fold_in(key, 1)
new_key_front = jax_frontend.random.fold_in(key, 1)
```

### Steps to Reproduce Bug

Run minimal example provided

### Environment

-

### Ivy Version

latest

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by AnnaTz** [comment]
Fixed [here](https://github.com/unifyai/ivy/commit/33b2d967e8b4e3b141423a8d1e0095234cb667af).

**Comment by KareemMAX** [comment]
Hey @Sam-Armstrong @AnnaTz, I'm closing this issue. Reopen it if you think the fix is not working.
