### ISSUE TITLE
flip, fliplr, flipud

### ISSUE THREAD

**Issue by PatternFinder** [unifyai/ivy#2647]

**Comment by 1Doomdie1** [comment]
Hey, thank you for contributing.
Can you please open an issue for each function and then mention them in your PR?
This way we can allocate these functions to you in the main issue list.

**Comment by PatternFinder** [comment]
@1Doomdie1 got it. closing this issue to file each functions separately.
Additionally, could you take a look at my other PRs? most of them have not received any attention for a while; I would really love to get some feedbacks on what the correct way to do thing so I can make lots of contributions in the following days. :)

my PRs: #2706, #2707, #2709, #2710, #2711
