### ISSUE TITLE
subtract

### ISSUE THREAD

**Issue by ajaysai6601** [unifyai/ivy#2653]
[ ] #Issue_num

**Comment by 1Doomdie1** [comment]
Can you please provide the issue ID from where you took this function, please?
Thank you.

**Comment by ajaysai6601** [comment]
Add Pointwise ops to PyTorch Frontend #12

**Comment by ajaysai6601** [comment]
It is pytorch frontend not tensorflow.

**Comment by 1Doomdie1** [comment]
Sorry, my mistake.
Thank you for flagging :D

**Comment by ajaysai6601** [comment]
Hi 1Doomdie1,
My workflows needs approval.
