### ISSUE TITLE
[Bug]: Small broken link in dashboard_automation/update_db.py

### ISSUE THREAD

**Issue by Archit-Kohli** [unifyai/ivy#27037]
### Bug Explanation

action_url seems to be broken in [automation_tools/dashboard_automation/update_db.py](https://github.com/unifyai/ivy/blob/main/automation_tools/dashboard_automation/update_db.py). I could be mistaken, but I think a simple fix could be to replace `https://github.com/unifyai/ivy/actions/runs/` with `https://github.com/unifyai/ivy/actions/`

### Steps to Reproduce Bug

Go to the above url, copy paste the given url in action_url in anew tab, it shows a 404 error

### Environment

Chrome Version 118.0.5993.71 (Official Build) (64-bit)

### Ivy Version

0.0.3.0

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by joshiayush** [comment]
Indeed it seems broken. A simple replacement might do the fix.
