### ISSUE TITLE
[Documentation]: Update Example Helper Function

### ISSUE THREAD

**Issue by Anteemony** [unifyai/ivy#27094]
### Path

https://unify.ai/docs/ivy/overview/deep_dive/navigating_the_code.html#submodule-helper-functions

### Section

Submodule Helper Functions

### Actual Behavior

`check_fill_value_and_dtype_are_compatible()` is defined in the code block. 

But `_assert_fill_value_and_dtype_are_compatible()` is mentioned in the explanation.

[This](https://github.com/unifyai/ivy/commit/81c68086bff719bf021d1e19dfabaa6bd4a86cec#diff-e83c33e3ce2c069e7b3b6c7576aa3f82f70a35757089815d2de2ed91fc1ec6f4L182) shows that the function was updated, but the explanation wasn't updated.

### Expected Behavior

[This](https://github.com/unifyai/ivy/commit/4a67bc09594fd1a47a9f3c93106905d788c0dd02#diff-32deaea08aabe47d24cf6951ae6f0cb015e06980ccdb40c2570289debb3fb362L193) shows the updated function, `check_fill_value_and_dtype_are_compatible()` is now removed. So perhaps a new function should be used as an example entirely.

**Comment by Aryan8912** [comment]
please assign to me, so I can work on this issue

**Comment by brahmika** [comment]
I addressed the issue by updating the documentation and here is the PR https://github.com/unifyai/ivy/pull/27786
