### ISSUE TITLE
Missing mandatory keyword argument `backend_to_test` in function calls.

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#27109]
In few files, in some of the function calls, the mandatory key-word argument `backend_to_test` is missing.
like in the following cases:
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/test_stateful/test_activations.py#L40
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/test_stateful/test_activations.py#L175

From the definition of `test_method` I see that `backend_to_test` is a mandatory key-word argument.
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/helpers/function_testing.py#L1573
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/helpers/function_testing.py#L1593

So, I see that this argument is missing at few places when calling `helpers.test_method()`. I think at all these places `backend_to_test=backend_fw` should be passed. Please correct me if I'm wrong.

**Comment by Sai-Suraj-27** [comment]
@vedpatwardhan sir, Can you please look into this issue when you are free. I would make a PR if you think this needs to be fixed. Thank you.

**Comment by vedpatwardhan** [comment]
> @vedpatwardhan sir, Can you please look into this issue and a similar one (#27110) when you are free. I would make a PR if you think this needs to be fixed. Thank you.

Yeah I think this is something that needs to be fixed, feel free to create a PR, same applies to https://github.com/unifyai/ivy/issues/27110. Thanks @Sai-Suraj-27 😄
