### ISSUE TITLE
Missing mandatory keyword argument `backend` in function calls.

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#27110]
In few files, in some of the function calls, the mandatory key-word argument `backend` is missing:
like in the following cases:
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py#L10194
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py#L10195

From the definition of `flatten_and_to_np` I see that `backend` is a mandatory key-word argument.
https://github.com/unifyai/ivy/blob/b5422a79808a860068e63d11233b0c0a2461d30f/ivy_tests/test_ivy/helpers/function_testing.py#L2408
So, I see that this argument is missing at few places when calling `helpers.flatten_and_to_np()` I think at all these places `backend=backend_fw` should be passed. Please correct me if I'm wrong.

**Comment by Ayush-Sharma410** [comment]
Hey 
can i work on this issue?

**Comment by Sai-Suraj-27** [comment]
Hey @Ayush-Sharma410, I found this issue and reported it to make a PR. Can you please look into some other issues?
Also, sorry for the late response, thank you.

**Comment by Ayush-Sharma410** [comment]
@Sai-Suraj-27 Sure
