### ISSUE TITLE
negative

### ISSUE THREAD

**Issue by kanakmi** [unifyai/ivy#2712]
Hi team Ivy
I would like to add negative math function as mentioned in issue #1545 
Please assign it to me.
Thanks

**Comment by kanakmi** [comment]
Hey @1Doomdie1 
When I opened this issue and asked it to be assigned to me, why was it not assigned to me? Did I not follow the procedure correctly?

**Comment by modanesh** [comment]
reopening the issue since the `negative` test is failing in the TF frontned
