### ISSUE TITLE
 feat: Add local_response_norm

### ISSUE THREAD

**Issue by kamlishgoswami** [unifyai/ivy#27187]

**Comment by AnnaTz** [comment]
Hi @kamlishgoswami, it turns out this function is of high priority for our team so we will be implementing it internally. Please feel free to pick another task to contribute to! Apologies for any inconvenience.

**Comment by kamlishgoswami** [comment]
Hello @AnnaTz,

Thank you so much for your response. :)

**Comment by kamlishgoswami** [comment]
Hello @AnnaTz ,

Please assign this issue to me: unsorted_segment_prod #27230. Thank you!

**Comment by AnnaTz** [comment]
> Hello @AnnaTz ,
> 
> Please assign this issue to me: unsorted_segment_prod #27230. Thank you!

Hi @kamlishgoswami, you should be able to reserve this yourself if you comment under the ToDo list as instructed [here](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues). The comment you added is not in the correct format.
