### ISSUE TITLE
Remove Duplicate Data Type Attributes in `class SupportedDtypes`

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#27213]
In the file: [`ivy_tests\test_ivy\test_frontends\config\base.py`](https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/test_frontends/config/base.py)

The following lines are repeated (duplicated):
https://github.com/unifyai/ivy/blob/82986f40c8f2e72dbfd5aee902dc34cb478348d9/ivy_tests/test_ivy/test_frontends/config/base.py#L28
https://github.com/unifyai/ivy/blob/82986f40c8f2e72dbfd5aee902dc34cb478348d9/ivy_tests/test_ivy/test_frontends/config/base.py#L29
They can be removed.

**Comment by itoriahimanshu** [comment]
Hi @Sai-Suraj-27, I'd have removed the duplicates and committed the changes, please assign me the issue and I'll create the PR for the same.

**Comment by itoriahimanshu** [comment]
Oh sure! Thanks for letting me know, I'll pick something up then, by the
way feel free to ping incase you want to collaborate and work on
something in Ivy's codebase.

Thanks

**Comment by Sai-Suraj-27** [comment]
Sure 😄
