### ISSUE TITLE
Numpy min

### ISSUE THREAD

**Issue by alvin-98** [unifyai/ivy#27387]

**Comment by 20481A05K0** [comment]
@alvin-98 can i work on this issue

**Comment by alvin-98** [comment]
Hi @20481A05K0, I'm almost done with this one. Going to create a PR now.

**Comment by Anuhya30110** [comment]
Okay thanks for responding

**Comment by Anuhya30110** [comment]
But @alvin-98 I have one doubt there is no transpose method for matrices in numpy I have opened the issue but where should I implement that logic
