### ISSUE TITLE
Use of requests call without `timeout` parameter

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#27741]
In the following places, `timeout` parameter is not used.
https://github.com/unifyai/ivy/blob/1f6264e1be8946b4b142668a0201fbaa73ee0810/docker/gpu_framework_directory.py#L18
https://github.com/unifyai/ivy/blob/1f6264e1be8946b4b142668a0201fbaa73ee0810/scripts/run_tests/helpers.py#L7
The `timeout` parameter is used to set the maximum time to wait for a response from the server. By omitting the `timeout` parameter, the program may hang indefinitely while awaiting a response.

From the [documentation](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts), I see that the value of timeout can be mentioned in seconds (like 5 seconds).

I think it's good to use the `timeout` parameter with a value of 10 seconds.

**Comment by vedpatwardhan** [comment]
Yep feel free to create a PR, certainly a useful addition. Thanks @Sai-Suraj-27 😄
