### ISSUE TITLE
Merge `setup.cfg` into `pyproject.toml`

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#27775]
Starting with [PEP 621](https://peps.python.org/pep-0621/), the Python community selected `pyproject.toml` as a standard way of specifying project metadata. `Setuptools` has adopted this standard and will use the information contained in this file as an input in the build process.

Also, I see that none of the big Python organizations ([jax](https://github.com/google/jax/blob/main/pyproject.toml), [Numpy](https://github.com/numpy/numpy/blob/main/pyproject.toml), [pandas](https://github.com/pandas-dev/pandas/blob/main/pyproject.toml), [mlflow](https://github.com/mlflow/mlflow/blob/master/pyproject.toml),...etc.) are using `setup.cfg` now especially when they are already using a `pyproject.toml` file.

`pyproject.toml` became the modern standard for build configuration in Python projects. Our current [`setup.cfg`](https://github.com/unifyai/ivy/blob/main/setup.cfg) also can be easily merged into the `pyproject.toml` file.
So, I think It is better to keep everything in one file `pyproject.toml`.

**Comment by vedpatwardhan** [comment]
Thanks for diving into this issue @Sai-Suraj-27. 1 sounds good to me as well, but I'll leave the final decision with @KareemMAX on which one to go with 😄

**Comment by KareemMAX** [comment]
Hello all, 
I totally agree with the suggestion, `ruff` is infact under our radar for sometime and replacing flake8 with it will be beneficial. Feel free to start implementing the changes @Sai-Suraj-27
