### ISSUE TITLE
Fix Ivy Failing Test: tensorflow - elementwise.subtract

### ISSUE THREAD

**Issue by samthakur587** [unifyai/ivy#27841]

**Comment by SrijanShovit** [comment]
Hello @samthakur587 Can I give this a try ? I really want to get a kickstart in contributing to ivy.

**Comment by samthakur587** [comment]
yeah you can start working on this issue if it's it good for you to kickstart in contributing to ivy. No problem . i can work on other issue . feel free to ask anything if you stuck anywhere.

**Comment by SrijanShovit** [comment]
Thanks @samthakur587

**Comment by SrijanShovit** [comment]
Btw I would like to know which part of documentation I shall study to understand whatever would be required for this issue!!

**Comment by samthakur587** [comment]
you should look at this  https://unify.ai/docs/ivy/overview/deep_dive.html
