### ISSUE TITLE
Wrong key-word arguments `return_index` and `return_inverse` in `ivy.unique_all()` function call

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#27895]
In the following function call, the arguments `return_index` and `return_inverse` are passed,
https://github.com/unifyai/ivy/blob/06508027180ea29977b4cafd316d536247cb5664/ivy/functional/frontends/sklearn/model_selection/_split.py#L80
From the actual `def` of `unique_all()`, there are no arguments like `return_index` and `return_inverse`.
https://github.com/unifyai/ivy/blob/06508027180ea29977b4cafd316d536247cb5664/ivy/functional/ivy/set.py#L29-L35

**Comment by Sai-Suraj-27** [comment]
Hey, @Ishticode, I see that you modified/added this file/lines, So can you look into this?
Thank you.

**Comment by Ishticode** [comment]
Hi @Sai-Suraj-27 
Thanks for pointing this out.
