### ISSUE TITLE
Fix Ivy Failing Test: numpy - manipulation.split

### ISSUE THREAD

**Issue by sgalpha01** [unifyai/ivy#28041]
ToDo: #27501
Task Type: Priority Open

**Comment by Aryan8912** [comment]
please assign to me

**Comment by ivy-leaves** [comment]
Hello @contributor,

Great news! The test 'split' is now passing. We are closing this issue. Feel free to choose and work on another failing test.

Thank you for your contribution!

Best,
Ivy Team
