### ISSUE TITLE
Fix Frontend Failing Test: paddle - creation.paddle.eye

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#28067]
To-do List: https://github.com/unifyai/ivy/issues/27500

**Comment by ivy-leaves** [comment]
Hello @contributor,

Great news! The test 'paddle.eye' is now passing. We are closing this issue. Feel free to choose and work on another failing test.

Thank you for your contribution!

Best,
Ivy Team

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves, it is failing for all the backends, without the appropriate decorator added
![image](https://github.com/unifyai/ivy/assets/87087741/cb1db621-b243-4f8e-a585-43c9ef4294d1)
