### ISSUE TITLE
Fix Frontend Failing Test: torch - tensor.torch.Tensor.__mul__

### ISSUE THREAD

**Issue by Aryan8912** [unifyai/ivy#28066]
ToDo: https://github.com/unifyai/ivy/issues/27498
Type: Priority

**Comment by ivy-leaves** [comment]
Hello @contributor,

Great news! The test 'torch.Tensor.__mul__' is now passing. We are closing this issue. Feel free to choose and work on another failing test.

Thank you for your contribution!

Best,
Ivy Team
