### ISSUE TITLE
Fixing pytest discovery issues on vscode

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28138]
Pytest discovery on vscode fails for our tests as of now with multiple errors regarding imports, unsupported dtypes, missing keys, etc. The goal of this task is to find workarounds and make fixes so that pytest discovery on vscode works for our repository.

**Comment by MuhammadNizamani** [comment]
@vedpatwardhan  can you give an example that we can run and produce the error and take look at this . It would be great help thanks

**Comment by vedpatwardhan** [comment]
Hey @Vismay-dev, have you already made a start on this issue? If yes, I'll assign this to you 😄

**Comment by Vismay-dev** [comment]
Hey @vedpatwardhan, yes I've already started trying to cross check file import paths for fixing pytest discovery issues.
