### ISSUE TITLE
Fixing the failing docstring tests

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28135]
There’s a number of docstring tests that were failing in the CI before. The ones that were failing are now being skipped through [this](https://github.com/unifyai/ivy/blob/abde04deb91ba2b455e62cae7ce2fa4e47223970/ivy_tests/test_docstrings.py#L117-L204) list. The goal of this task is to fix the docstring examples for the functions in that list and other functions failing on the docstring tests [workflow](https://github.com/unifyai/ivy/actions/runs/7723586890/job/21054000554#step:4:427) on `main `such that we’re in a state where the `skip_list_temp` is empty and `test_docstrings.yml` passes on the `main` branch

**Comment by Nightrider0098** [comment]
Hey @vedpatwardhan can i pick this issue?

**Comment by vedpatwardhan** [comment]
Hey @Nightrider0098, as mentioned in the [docs](https://unify.ai/docs/ivy/overview/contributing/volunteer_program.html#top-contributor), the bounty tasks are mainly open for top contributors. Happy to answer any other questions, thanks!

**Comment by Sai-Suraj-27** [comment]
@vedpatwardhan Can I work on this?

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves assign me

**Comment by vedpatwardhan** [comment]
> Hey, @vedpatwardhan Can I work on this? Also, will there be any deadline to finish the task?

Given that we were just getting started, there wasn't a deadline explicitly added to the task. But for upcoming tasks we'll add explicit deadlines, thanks for the suggestion 👍
