### ISSUE TITLE
Getting the stateful tests up and running

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28136]
Trying to run the stateful tests throws an error, e.g. running the tests for `ivy_tests/test_ivy/test_stateful/test_activations.py::test_elu` throws an error 
```
E           ModuleNotFoundError: No module named ‘ELU'
```
This is the same across all other stateful tests. The goal of this task is to fix this error so that all stateful tests run successfully without error unless there’s a genuine test failure

**Comment by vedpatwardhan** [comment]
@ivy-leaves assign me

**Comment by mosesdaudu001** [comment]
@ivy-leaves assign me

**Comment by soma2000-lang** [comment]
@ivy-leaves assign me

**Comment by soma2000-lang** [comment]
Hi @vedpatwardhan ,Can you assign me this issue

**Comment by vedpatwardhan** [comment]
Hey @NripeshN, could you please check if the `@ivy-leaves assign me` automation is fully working? The bot is yet to assign @mosesdaudu001 to the issue. Thanks!

**Comment by vedpatwardhan** [comment]
> Hi @vedpatwardhan ,Can you kindly assign me this issue.I am a TC.

Hey @soma2000-lang, given that @mosesdaudu001 messaged on the issue first, he'd get assigned on this one. We're creating a few more of these tasks over the next few days, feel free to check those out. Thanks 😄

**Comment by soma2000-lang** [comment]
Hi @vedpatwardhan  No problem 😄

**Comment by NripeshN** [comment]
Hey @soma2000-lang,
feel free to work on this issue
