### ISSUE TITLE
Enabling the casting modes by default in ivy and the tests

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28189]
The [casting modes](https://unify.ai/docs/ivy/overview/deep_dive/data_types.html#data-type-casting-modes) in `ivy` are used to allow automatic casting of input arrays to other supported dtypes of a backend implementation when it doesn't support the dtype of the input passed. 
These modes are currently disabled by default to allow users to decide whether or not they'd like to use automatic type casting or have more control over memory/precision and not use the casting modes.
However, it has become increasingly clear especially when trying to transpile from `torch` to `tensorflow`, that there are a large number of functions for which `torch` supports a particular dtype but `tensorflow` does not.

The goal here is to enable casting modes by default in `ivy`, we will continue to allow the users the option to opt out of it. Once this is done, we should also update the testing pipeline such that we don't make use of the supported/unsupported dtypes helpers for generating the dtypes for the tests but rather all dtypes that are supported by the backend as a whole.

These changes are expected to lead to a wide number of test failures in `ivy` as well as the frontends, but the goal here isn't to fix those tests but just to enable the casting modes by default in `ivy` and generate all dtypes supported by the backends in the tests!

**Comment by soma2000-lang** [comment]
@ivy-leaves assign me

**Comment by he11owthere** [comment]
@ivy-leaves assign me

**Comment by NripeshN** [comment]
Hi @he11owthere 
Is the issue being worked on? If not can you unassign yourself from this issue?

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves assign me
