### ISSUE TITLE
Adding a way to enable explicit `@example` in our tests

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28207]
Currently most tests in `ivy` and the frontends are property-based, wherein we define [strategies](https://github.com/unifyai/ivy/blob/2c465d6de04d04bdee0d7b07ede0bbbeb66b69b0/ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py#L287) for generating data inside our tests (more explanations [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html)).
Now, in certain cases where we'd like to test certain examples explicitly which are outliers and it isn't feasible to define them as a strategy. One such example is [this](https://github.com/unifyai/ivy/pull/28181/files#diff-a13fff36fcac31f1f8fa76cb78fceb815348b58f0b03358bbf471bd355416ee8R1651) where we need to test `ivy.set_item` with `slice` objects. 

`hypothesis` allows us to test with an explicit example deterministically using the [`@example`](https://hypothesis.readthedocs.io/en/latest/reproducing.html#hypothesis.example) decorator. One of the challenges currently is that we need to define all the [flags](https://github.com/unifyai/ivy/pull/28181/files#diff-a13fff36fcac31f1f8fa76cb78fceb815348b58f0b03358bbf471bd355416ee8R1659) as well even if we're using the default values for them. What we should instead have is a way to define those flags only if their values are different from a default we set for all these flags. 

This task would involve adding a new decorator to the tests (similar to how we have [`handle_test`](https://github.com/unifyai/ivy/blob/2c465d6de04d04bdee0d7b07ede0bbbeb66b69b0/ivy_tests/test_ivy/helpers/testing_helpers.py#L326), [`handle_frontend_test`](https://github.com/unifyai/ivy/blob/2c465d6de04d04bdee0d7b07ede0bbbeb66b69b0/ivy_tests/test_ivy/helpers/testing_helpers.py#L470), etc.) which would just wrap the function with `@example` but would use the default values of these flags similar to what `handle_test` and `handle_frontend_test` do (ofc in this case the default value would be a python str, list, bool, etc. instead of a hypothesis strategy that generates these values). Also, necessary generalizations should be made to the newly created decorator so that a single decorator with the tests of functions and methods both on ivy and the frontends when trying to specify explicit examples.

You should finally update [this](https://github.com/unifyai/ivy/pull/28181/files#diff-a13fff36fcac31f1f8fa76cb78fceb815348b58f0b03358bbf471bd355416ee8R1650) implementation using the new decorator and write up a sub-section under [this](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html#id2) section of the docs explaining how this decorator should be used.

Feel free to reach out for any questions!

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves assign me

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves assign me

**Comment by NitinRwt** [comment]
@ivy-leaves assign me
