### ISSUE TITLE
Delete the unnecessary github actions workflows

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28447]
There's a number of github actions workflows that used to be used in the past but aren't being used anymore or have been replaced with something else. All such workflows should be deleted. Your task is to create a PR that removes all such workflows which you think aren't being used anymore. One good way to find out which ones aren't being used is going through the [workflows](https://github.com/unifyai/ivy/actions) and seeing which ones were last triggered months ago and so on.
The decision on whether to remove a particular workflow is slightly subjective, so you should do a first pass through all the workflows and creating a PR that removes them, we'll then discuss further on the PR if there's any others that should be removed or ones which shouldn't be removed.
Feel free to reach out for any questions, thanks!

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves assign me
