### ISSUE TITLE
Adding a demo for transpiling torch models to jax and use it on a TPU

### ISSUE THREAD

**Issue by vedpatwardhan** [unifyai/ivy#28445]
We currently have a demo for transpiling torch models to jax followed by inference on a [gpu](https://unify.ai/docs/ivy/demos/examples_and_demos/torch_to_jax.html), but there was a recent request for being able to use the transpiled jax model on a tpu as well.
This task involves creating a colab notebook that demonstrates transpilation of torch models to jax and then inference on a tpu. This demo will then be added to our docs for the wider community. 
Feel free to reach out in case you face any issues, thanks!

**Comment by Sai-Suraj-27** [comment]
@ivy-leaves assign men

**Comment by samthakur587** [comment]
@ivy-leaves assign me
