### ISSUE TITLE
Reciprocal function missing in Ivy Functional API

### ISSUE THREAD

**Issue by TheMonocledHamster** [unifyai/ivy#2873]
It appears as though an element-wise function, 'reciprocal', is missing from the Ivy Functional API.
I believe that it should have been implemented in the [elementwise.py](https://github.com/unifyai/ivy/blob/f2d2e225e1df4fe6ca2110dcc2ef5b0f5a14a20d/ivy/functional/ivy/elementwise.py) sub-module, however that does not seem to be the case. 
It has not been implemented in another sub-module either, to the best of my knowledge. 
Is this an intentional omission? If not, may I go ahead and create a pull request fixing the same?

**Comment by sreegandh804** [comment]
Hey @TheMonocledHamster , thanks for flagging this, if it's an addition to the API, you should considering making a PR with the label "Extension" as advised in the link below:
https://lets-unify.ai/ivy/contributing/1_the_basics.html#extensions
