### ISSUE TITLE
`ivy.flatten`

### ISSUE THREAD

**Issue by 5hv5hvnk** [unifyai/ivy#3161]
ivy codebase lacks ivy.flatten method to flatten a matrix or a tensor which I feel is relevant for a lot of frontend/backend methods that would be added in future

**Comment by jkeane508** [comment]
Hi @5hv5hvnk,

Thanks for flagging, I will mention to the team!

I will leave this issue open and report back :)

**Comment by jkeane508** [comment]
Hi,

I have linked the issue to a PR that was working on an implementation for `ivy.flatten`. Once this PR has been merged this issue will be closed.

Thanks for Flagging!

**Comment by johanjino** [comment]
We have discussed internally, and we have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks!
