### ISSUE TITLE
Add Instance Methods to NumPy Frontend

### ISSUE THREAD

**Issue by jkeane508** [unifyai/ivy#3607]
Add [Instance Methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#) to NumPy Frontend:

- [ ] all
- [ ] any
- [ ] argmax
- [ ] argmin
- [ ] argpartition
- [ ] argsort
- [ ] astype
- [ ] byteswap
- [ ] choose
- [ ] clip
- [ ] compress
- [ ] conj
- [ ] conjugate
- [ ] copy
- [ ] cumprod
- [ ] cumsum
- [ ] diagonal
- [ ] fill
- [ ] flatten
- [ ] getfield
- [ ] item
- [ ] itemset
- [ ] max
- [ ] mean
- [ ] min
- [ ] newbyteorder
- [ ] nonzero
- [ ] partition
- [ ] prod
- [ ] ptp
- [ ] put
- [ ] ravel
- [ ] repeat
- [ ] reshape
- [ ] resize
- [ ] round
- [ ] searchsorted
- [ ] setfield
- [ ] sort
- [ ] squeeze
- [ ] std
- [ ] sum
- [ ] swapaxes
- [ ] take
- [ ] tobytes
- [ ] tofile
- [ ] tolist
- [ ] tostring
- [ ] trace
- [ ] transpose
- [ ] var
- [ ] view

**Comment by NicAOB97** [comment]
- [ ] #4715

**Comment by jkeane508** [comment]
> Hi! So each instance method needs to be added to: ivy/functional/frontends/numpy/ndarray.py

Yep, as documented [here](https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html#classes-and-instance-methods) :)

**Comment by hmahmood24** [comment]
- [] #4886

**Comment by hmahmood24** [comment]
- [ ] #4887

**Comment by westrany** [comment]
argmax #4924

**Comment by varshithamanasa** [comment]
#4940

**Comment by morleythomas** [comment]
- [ ] #5038

**Comment by alizahidraja** [comment]
- [ ] #5304

**Comment by geeythree** [comment]
- [ ] #5641

**Comment by Shajeeran** [comment]
#6002

**Comment by EvanMarie** [comment]
argmin #6239

**Comment by codeamic** [comment]
#6242

**Comment by EvanMarie** [comment]
I completed argmin #6239 following every detail of the instructions. The comments here did not include it had been done. It was still on the todo list. Because it was a very simple implementation, I did not test locally, and so I missed this until the PR.  Unfortunately, argmin was buried deep within the code, very far away from argmax.  So, whatever bot is supposed to be updating this todo list is being a silly bot.

**Comment by EvanMarie** [comment]
sum #6246

**Comment by codeamic** [comment]
Hi EvanMarie, please be patient.  The bot do the check after every one hour.

**Comment by EvanMarie** [comment]
> Hi EvanMarie, please be patient.  The bot do the check after every one hour. you don't need to create another issue as new contributors will need to work on them
> 
> 

I was doing another one since the previous had already been done. And it was done nine weeks ago, I believe. Yet it was still a todo. There's no problem. I just wanted to add clarity as to why I did the PR.

**Comment by Hassan-Ik** [comment]
Mean #6268

**Comment by JoelPendleton** [comment]
#6769

**Comment by hello-fri-end** [comment]
- [ ] #6832

**Comment by hello-fri-end** [comment]
@jkeane508 Please mark `reshape` as completed.

**Comment by hello-fri-end** [comment]
- [ ] #6837

**Comment by hello-fri-end** [comment]
- [ ] #6841

**Comment by hello-fri-end** [comment]
@jkeane508 @Aarsh2001 Looks like there's some overlap in the tasks in #1537 and this issue. Some of the tasks mentioned here (e.g reshape, transpose, swapaxes, etc.) are already completed/tracked in #1537

**Comment by hello-fri-end** [comment]
- [ ] #6885

**Comment by AlshimaaGamalAlsaied** [comment]
#6979

**Comment by geeythree** [comment]
- [ ] #7056

**Comment by Cstyler** [comment]
- [ ] 7189

**Comment by hnehme99** [comment]
- [ ] #7190

**Comment by Cstyler** [comment]
- [] #7189

**Comment by Cstyler** [comment]
- [ ] #7189

**Comment by codeamic** [comment]
astype #7356

**Comment by alizahidraja** [comment]
- [ ] #8389

**Comment by DsJamwal** [comment]
#8837

**Comment by DsJamwal** [comment]
#8838

**Comment by abhi27-web** [comment]
#8955

**Comment by abhi27-web** [comment]
#8956

**Comment by HarshitKmr10** [comment]
__pow__ #9005

**Comment by Chaitanya134** [comment]
__itruediv__ #9007

**Comment by hossamasaad** [comment]
Argpartition #9219

**Comment by hoanganhminh01** [comment]
- NumPy Frontend Instance Method __mod__ #9263

**Comment by ahmedelgamal0** [comment]
#9594

**Comment by mustafa1adel** [comment]
astype #9596

**Comment by onedeeper** [comment]
compress #9758

**Comment by onedeeper** [comment]
fill #9853

**Comment by ahmedelgamal0** [comment]
__len__ #9948

**Comment by rarisenpai** [comment]
resize #9984

**Comment by rarisenpai** [comment]
__floordiv__ #10110

**Comment by sergio-verduzco** [comment]
#10179

**Comment by guodh321** [comment]
__array__#10249

**Comment by rarisenpai** [comment]
__ifloordiv__ #10308

**Comment by Killua7362** [comment]
- [ ] #10468

**Comment by soma2000-lang** [comment]
round #10518

**Comment by sergio-verduzco** [comment]
#10528

**Comment by EdisonLeung** [comment]
- [Fill] #10544

**Comment by EdisonLeung** [comment]
- [ ] #10544

**Comment by EdisonLeung** [comment]
- [ ] #10544

**Comment by RajBommala** [comment]
#10660

**Comment by ranjua** [comment]
- [ ] #10764

**Comment by GrzegorzKrug** [comment]
#6620

**Comment by omarragi9** [comment]
fill #11502

**Comment by cressidasuphina** [comment]
tolist #11758

**Comment by Cosmogyrall** [comment]
- [ ] #11937

**Comment by Sph3inx** [comment]
choose #12704

**Comment by Sph3inx** [comment]
- [choose]  #12704

**Comment by Sph3inx** [comment]
-  choose #12704

**Comment by Sph3inx** [comment]
- [ ] choose #12704

**Comment by Sph3inx** [comment]
- [ ]#12704

**Comment by Sph3inx** [comment]
- [ ] #12704

**Comment by AkshayC2001** [comment]
- [ ] #12933

**Comment by AkshayC2001** [comment]
- [ ] #13015

**Comment by elabongaatuo** [comment]
__str__ #13025

**Comment by AkshayC2001** [comment]
- [ ] #13043

**Comment by AkshayC2001** [comment]
- [ ] #13043

**Comment by AjibolaMatthew1** [comment]
#13079

**Comment by elabongaatuo** [comment]
-  [ ] #13025

**Comment by IhorBoichuk** [comment]
#13485

**Comment by IhorBoichuk** [comment]
#13486

**Comment by IhorBoichuk** [comment]
byteswap #13556

**Comment by indrawatideasy** [comment]
Subtask [ptp](https://github.com/unifyai/ivy/issues/13611) for Instance Methods to NumPy Frontend https://github.com/unifyai/ivy/issues/3607

**Comment by indrawatideasy** [comment]
Subtask byteswap https://github.com/unifyai/ivy/issues/13433 for Instance Methods to NumPy Frontend https://github.com/unifyai/ivy/issues/3607

**Comment by Bfault** [comment]
- [ ] #13828

**Comment by hbarton2** [comment]
- [ ] #14174

**Comment by tdjogi010** [comment]
[ ] #14190

**Comment by edith007** [comment]
- [ ]  getfield #14195

**Comment by ratulMahjabin** [comment]
- [ ] #14554

**Comment by AnjelicaB** [comment]
put #14680

**Comment by KartikeyDubeyKD** [comment]
#14722

**Comment by KartikeyDubeyKD** [comment]
@jkeane508 close __deepcopy__ it's completed #14722

**Comment by KartikeyDubeyKD** [comment]
#14752

**Comment by AsmaaMHadir** [comment]
flat #14766

**Comment by AsmaaMHadir** [comment]
__setstate__ #14768

**Comment by KartikeyDubeyKD** [comment]
#14772

**Comment by RakshitKumar04** [comment]
- [ ] #15082

**Comment by indrawatideasy** [comment]
- [Conjugate] https://github.com/unifyai/ivy/pull/15059

**Comment by indrawatideasy** [comment]
- [Ptp] https://github.com/unifyai/ivy/pull/14825

**Comment by AsmaaMHadir** [comment]
flat #14766

**Comment by marschattha** [comment]
- [ ] #15453

**Comment by enjay-k** [comment]
- [ ] #15537

**Comment by bahbah94** [comment]
Trace #15751

**Comment by gaurav3247** [comment]
https://github.com/unifyai/ivy/issues/13015

**Comment by ahmadel1** [comment]
#16104

**Comment by ahmadel1** [comment]
#16104

**Comment by LowkeyBBQ** [comment]
std #16110

**Comment by enjay-k** [comment]
- [ ] #16182

**Comment by gaurav3247** [comment]
- round #13015

**Comment by PushpamJha14** [comment]
- [ ] #16333

**Comment by Faiq2001** [comment]
#16534

**Comment by redorblueorred** [comment]
- [ ] #16556

**Comment by jaysilver-5** [comment]
compress #12933

**Comment by gorantlasuhas** [comment]
take #17765

**Comment by GuisandeGolfer** [comment]
- [ ] #17772

**Comment by jaysilver-5** [comment]
#17975

**Comment by IIDCII** [comment]
#18005

**Comment by Maxzeno** [comment]
- [ ]  #18013

**Comment by Maxzeno** [comment]
trace #18013

**Comment by Maxzeno** [comment]
#18013

**Comment by ligia26** [comment]
#18055

**Comment by KartikeyDubeyKD** [comment]
#18141

**Comment by AsmaaMHadir** [comment]
__invert__ #18284

**Comment by gmonte29** [comment]
#19001

**Comment by Kappuccino111** [comment]
- [ ] #19478

**Comment by danushkhanna** [comment]
- [ ] #19535

**Comment by akshatvishu** [comment]
- [ ] #19554

**Comment by shuoandrew** [comment]
- [ ] #19634

**Comment by GabrielMazzali** [comment]
#19535

**Comment by k-e-ian** [comment]
- [ ] #19886

**Comment by a0m0rajab** [comment]
- [ ] #20710

**Comment by jaysilver-5** [comment]
#20870

**Comment by jaysilver-5** [comment]
#20871

**Comment by Ramzan-Ali12** [comment]
Add Instance Methods to NumPy Frontend #3607

**Comment by PushpamJha14** [comment]
#21949

**Comment by PushpamJha14** [comment]
#21949

**Comment by Saptarshi-Bandopadhyay** [comment]
- #22192

**Comment by niixxaaa** [comment]
#22203

**Comment by mtilerisoy** [comment]
- [ ] #22230

**Comment by vincenzofanizza** [comment]
- [ ] #22583

**Comment by vincenzofanizza** [comment]
- [ ] #23024

**Comment by vincenzofanizza** [comment]
@jkeane508 I'm working on argpartition (#23024). Could you please update the to-do list?

**Comment by paulmbuitu** [comment]
- [ ] #23150

**Comment by assem1390** [comment]
- [ ]  #23184

**Comment by OriginCoding** [comment]
- [ ] #23331

**Comment by paulmbuitu** [comment]
Hello there, I do not understand what you mean by this email. Please
elaborate more.

**Comment by VedangSavadi** [comment]
- [ ] #23782

**Comment by memorybase** [comment]
- [ ] #3607

**Comment by PushpamKJha** [comment]
- [ ] #24614

**Comment by RajniHarsha27** [comment]
- [ ] #24938

**Comment by manny-uncharted** [comment]
- [ ] #23331

**Comment by Ivanseven** [comment]
- [ ] #25896

**Comment by juliusmarkwei** [comment]
#26253

**Comment by cespinosa** [comment]
- [ ] #26921

**Comment by Abhinav-CHD** [comment]
- [ ]  #27052
