### ISSUE TITLE
arctan2

### ISSUE THREAD

**Issue by Nouran6Gamal** [unifyai/ivy#3792]

**Comment by Nouran6Gamal** [comment]
@ivy-seed  assign me to this function please

**Comment by Nouran6Gamal** [comment]
my pull request https://github.com/unifyai/ivy/pull/3832 but I'm trying to solve problems there

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would like to continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues

**Comment by Nouran6Gamal** [comment]
I'm still l working on this one but have issues
