### ISSUE TITLE
ivy.deg2rad

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#3926]

**Comment by KhalidAl-otaibi** [comment]
If this is decided to be included in the next release, I am happy to implement it If no one is assigned to it yet

**Comment by johanjino** [comment]
We have discussed internally, and we have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks!
