### ISSUE TITLE
to_device

### ISSUE THREAD

**Issue by juaolobo** [unifyai/ivy#396]

**Comment by juaolobo** [comment]
Hey there, 

I've been looking at the code for some time and there a few things I'm confused about. I noticed that all other 'categories' in the ToDo list have their specific files, even if there is not code inside of them, but Array Methods doesn't have one, even though there is an array_object.py file that is being tested. Should I create this file or is it somewhere and I missed it?

Another thing, I was taking a look at the tests code and I couldn't find where the Array Methods are being tested. When I look for my method in all the files, all that comes up is an empty definition in function_stubs/array_object.py and in function_stubs/\_\_init\_\_.py. I saw that array_object.py has a specific test file, but almost no methods that are in the ToDo list issue are being tested in there.

**Comment by 1Doomdie1** [comment]
Closing Issue due to interactivity.
