### ISSUE TITLE
I have an error in test-frontend-numpy / run-nightly-tests (pull_request)

### ISSUE THREAD

**Issue by Nouran6Gamal** [unifyai/ivy#4170]
I had this error in test-frontend-numpy / run-nightly-tests (pull_request) , how can I handle it issue pull request #4034 
2022-09-05T08:57:09.5877399Z E AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
2022-09-05T08:57:09.5877469Z E
2022-09-05T08:57:09.5877544Z E ret_np_flat:
2022-09-05T08:57:09.5877612Z E
2022-09-05T08:57:09.5877678Z E []
2022-09-05T08:57:09.5877748Z E
2022-09-05T08:57:09.5877832Z E ret_np_from_gt_flat:
2022-09-05T08:57:09.5877884Z E
2022-09-05T08:57:09.5877973Z E [array(0., dtype=float16)]

& If someone added a function in both files I'm working on that made conflicts with my branch , should I add the added code ?

**Comment by CatB1t** [comment]
Hello @Nouran6Gamal, this could be an issue from our side, does using `min_num_dims=1` fix it? You should also fix the merge conflict, if you're unfamiliar with fixing merge conflicts, this could help: https://youtu.be/TFMPihytg9U .

Feel free to join our discord and ask for help from the other contributors too!

**Comment by Nouran6Gamal** [comment]
@catB1t  I saw the part of min_num_dims=1  but I don't know in which part of code ? is it in a third file 
https://github.com/unifyai/ivy/pull/3373/commits/f64cc0a5b76c994eba8883c99c724800d8d0afdc

**Comment by Nouran6Gamal** [comment]
@CatB1t 
I added min_num_dims=1 & i solved the conflict then I found my function arctan2 and function deg2rad merged so I copied the file from ivy repo and added my code in these 2 files
https://github.com/Nouran6Gamal/ivy/blob/patch-1/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py 
and  https://github.com/Nouran6Gamal/ivy/blob/patch-1/ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py

in test- frontend-numpy I didn't find any error related to my function but related to another functions
and lint showed me error not in my 2 edited file
these are lint errors
ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:55:45: E12[8](https://github.com/unifyai/ivy/runs/8236938657?check_suite_focus=true#step:5:9) continuation line under-indented for visual indent
ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:56:45: E128 continuation line under-indented for visual indent
ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:57:45: E128 continuation line under-indented for visual indent
ivy_tests/test_ivy/test_functional/test_extensions.py:1:1: W3[9](https://github.com/unifyai/ivy/runs/8236938657?check_suite_focus=true#step:5:10)1 blank line at end of file

any thing I should edit in both files ?

**Comment by CatB1t** [comment]
The way you resolved the conflict is correct, you should ignore and not try to fix the lintng errors as far as they're not related to the files you're editing, you can refer back to the PR to make sure nothing needs more updating! Thanks for contributing :)

**Comment by Nouran6Gamal** [comment]
https://github.com/unifyai/ivy/pull/4034
