### ISSUE TITLE
AttributeError: module 'ivy.functional.backends.numpy' has no attribute 'to_ivy_module'

### ISSUE THREAD

**Issue by H4dr1en** [unifyai/ivy#4500]
Hi, I am trying to convert a torch model to tensorflow using ivy. Here is my code:

```
import timm
import ivy

net = timm.create_model("lcnet_035", features_only=True, exportable=True)
net = ivy.to_ivy_module(net)
net = net.compile_graph()
net = net.to_backend('tensorflow')
```

This throws the following error (on master [ffcd606](https://github.com/unifyai/ivy/commit/ffcd60610645aa4b4ec85eeb1c40fb694add29d6)):
```
Traceback (most recent call last):
  File "/Users/h4dr1en/convert.py", line 5, in <module>
    net = ivy.to_ivy_module(net)
  File "/opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/ivy/stateful/converters.py", line 47, in to_ivy_module
    return current_backend().to_ivy_module(
AttributeError: module 'ivy.functional.backends.numpy' has no attribute 'to_ivy_module'
```

Am I doing something wrong?

**Environment:**
Apple M1 Pro (macos 12.5.1)
Python 3.9.13
<details>
  <summary>$ pip freeze</summary>
absl-py==1.2.0

astunparse==1.6.3
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==5.2.0
certifi==2022.9.14
charset-normalizer==2.1.1
colorama==0.4.5
cycler==0.11.0
einops==0.4.1
etils==0.8.0
flatbuffers==1.12
fonttools==4.37.1
functorch==0.2.1
gast==0.4.0
google-auth==2.11.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio @ file:///Users/runner/miniforge3/conda-bld/grpc-split_1662408188328/work
h5py @ file:///Users/runner/miniforge3/conda-bld/h5py_1637964045648/work
idna==3.4
importlib-metadata==4.12.0
importlib-resources==5.9.0
ivy-core @ git+https://github.com/unifyai/ivy.git@ffcd60610645aa4b4ec85eeb1c40fb694add29d6
jax==0.3.17
jaxlib==0.3.15
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==14.0.6
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.3
ninja==1.10.2.3
numpy==1.23.0
nvidia-ml-py==11.495.46
nvidia-ml-py3==7.352.0
oauthlib==3.2.1
opt-einsum==3.3.0
packaging==21.3
Pillow==9.2.0
protobuf==3.19.5
psutil==5.9.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
python-dateutil==2.8.2
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scipy==1.9.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.9.0
tensorflow-macos==2.9.2
tensorflow-metal==0.5.1
termcolor==1.1.0
timm==0.6.7
torch==1.11.0
torchvision==0.12.0
typing_extensions==4.3.0
urllib3==1.26.12
Werkzeug==2.2.2
wrapt==1.14.1
zipp==3.8.1
</details>

**Comment by sharique1006** [comment]
@H4dr1en have you tried setting the backend before creating the model?

**Comment by H4dr1en** [comment]
@sharique1006 

This will raise

```
  File "/Users/h4dr1en/convert.py", line 4, in <module>
    ivy.set_backend("tensorflow")
  File "/opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/ivy/backend_handler.py", line 271, in set_backend
    ivy.__dict__[k] = _wrap_function(key=k, to_wrap=backend.__dict__[k], original=v)
  File "/opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/ivy/func_wrapper.py", line 453, in _wrap_function
    linalg_k, linalg_v, ivy.__dict__[linalg_k]
KeyError: 'NamedTuple'
```

**Comment by sharique1006** [comment]
yes, it is still being implemented.
