### ISSUE TITLE
Add Linear algebra functions to Jax frontend

### ISSUE THREAD

**Issue by hirwa-nshuti** [unifyai/ivy#4614]
Add [Linalg functions](https://jax.readthedocs.io/en/latest/jax.numpy.html#module-jax.numpy.linalg) to Jax frontend

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [x] #4716
- [x] cond
- [x] #4719
- [x] #6084
- [x] #4717
- [x] eigvals
- [x] #4724
- [x] #4718
- [x] #22867
- [x] #5972
- [x] matrix\_rank
- [x] #19403
- [x] #5758
- [x] #6207
- [x] #4720
- [x] slogdet
- [x] #5783
- [x] #7203
- [x] #7387
- [x] tensorsolve

> The main file paths where these functions are likely to be added are: 
> - `ivy/functional/frontends/jax/numpy/linalg.py`
> - `ivy\_tests/test\_ivy/test\_frontends/test\_jax/test\_jax\_numpy\_linalg.py`

**Comment by PatricYan** [comment]
- [ ] #4702

**Comment by karalleyna** [comment]
- [ ] #4716

**Comment by karalleyna** [comment]
- [ ] eigh

**Comment by karalleyna** [comment]
- [ ] #4718

**Comment by karalleyna** [comment]
- [ ] #4719

**Comment by karalleyna** [comment]
- [ ] #4720

**Comment by karalleyna** [comment]
- [ ] #4724

**Comment by ndurumo254** [comment]
- [ ] #4753

**Comment by AbhishekJha22** [comment]
[] #4825

**Comment by ukj02** [comment]
#5142

**Comment by ndurumo254** [comment]
[]#4964

**Comment by randomstate42** [comment]
- [ ] #5492

**Comment by VikramxD** [comment]
#5668

**Comment by mohame54** [comment]
#5758

**Comment by JonathanGhaly** [comment]
- [ ] #5781

**Comment by oscar1marte** [comment]
- [ ] #5783

**Comment by oscar1marte** [comment]
- [ ] #5783

**Comment by 0xcro3dile** [comment]
- [ ] #5921

**Comment by 11Kclarke** [comment]
-[]#5972

**Comment by sayantan1410** [comment]
#5999

**Comment by rubythalib33** [comment]
- [] #6084

**Comment by minivet** [comment]
- [ ]  #6207

**Comment by Pranjal-bisht** [comment]
- [] #6209

**Comment by Infrared1029** [comment]
[matrix power] #6225

**Comment by samuelbido** [comment]
- [] #6276

**Comment by hirwa-nshuti** [comment]
- [ ] #6464

**Comment by rubythalib33** [comment]
[ ] #6492

**Comment by Ajay6601** [comment]
slogdet #6724

**Comment by Taciturny** [comment]
- [ ] cond

**Comment by Taciturny** [comment]
- [ ] #6783

**Comment by WilliamHirst** [comment]
- [ ] #7203

**Comment by mmi333** [comment]
- [ ] #7387

**Comment by karalleyna** [comment]
- [ ] #7409

**Comment by danielmunioz** [comment]
#7974

**Comment by danielmunioz** [comment]
#9057

**Comment by Jigyasa-Kumari** [comment]
# 9408

**Comment by Jigyasa-Kumari** [comment]
#9408

**Comment by shireenchand** [comment]
#14218

**Comment by Principor** [comment]
- [ ] #16620

**Comment by avi-thakur-0812** [comment]
- [ ] #17525

**Comment by avi-thakur-0812** [comment]
#19403

**Comment by Supremolink81** [comment]
lstsq

**Comment by ahmet-SY** [comment]
@hirwa-nshuti should we close this since all functions are done?
