### ISSUE TITLE
ivy.dropout

### ISSUE THREAD

**Issue by Change-m** [unifyai/ivy#4618]

**Comment by sreegandh804** [comment]
Hey @Change-m , I would suggest you make 1 issue for each function that you make as you seem to have multiple issues open for the same function and only the other one seems to be assigned in the main function to you, https://github.com/unifyai/ivy/issues/4475.
Please refer to the contributor's guide, as the incorrect opening of issues may not close/update the function in the main issue body that your sub-task is linked to: https://lets-unify.ai/ivy/contributing.html. Hope this makes sense 😅
