### ISSUE TITLE
ivy.fill_diagonal

### ISSUE THREAD

**Issue by JamieLine** [unifyai/ivy#4672]
Found in Numpy as `np.fill_diagonal`, Torch as `torch.diagflat` and Tensorflow as `tf.linalg.diag`.

**Comment by hirwa-nshuti** [comment]
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks!
