### ISSUE TITLE
Hey,

### ISSUE THREAD

**Issue by ndurumo254** [unifyai/ivy#4902]
Hey, i still get some errors even after importing the pre commit

You still need to make the changes I outlined in the previous review :)

Moreover, there seems to be some lint failures, you can import a pre commit hook here which will format code automatically before every commit [here](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit)

_Originally posted by @jkeane508 in https://github.com/unifyai/ivy/pull/4763#pullrequestreview-1118748029_

**Comment by hirwa-nshuti** [comment]
Hey, the pre-commit hook helps you not push the code with lint errors if you're still getting some linting errors after pushing I advise you to check the error log you will clearly see the lines with problems and go on fixing them accordingly.
Thanks🙂
