### ISSUE TITLE
common functions

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#4908]
I did a search of functions not in Ivy which are in at least 3 of jax, torch, numpy and tensorflow, and hence may be worth considering. I just searched by function name so some of these may exist in Ivy under a different name, but I tried to remove any such cases (sorry if i missed some). 

```{'vander', 'unravel_index', 'ldexp', 'nextafter', 'nanmean', 'trapz', 'fmod', 'atleast_3d', 'msort', 'histogram', 'nanmedian', 'triu_indices', 'broadcast_shapes', 'nanquantile', 'isclose', 'quantile', 'ravel', 'heaviside', 'imag', 'dstack', 'logaddexp2', 'float_power', 'corrcoef', 'tril_indices', 'fix', 'flipud', 'histogramdd', 'moveaxis', 'nansum', 'angle', 'diagflat', 'frexp', 'diff', 'fmax', 'fliplr', 'exp2', 'frombuffer', 'cov', 'vstack', 'fmin', 'nan_to_num', 'median', 'count_nonzero', 'isin', 'column_stack', 'diag', 'isneginf', 'hsplit', 'allclose', 'copysign', 'row_stack', 'i0', 'signbit', 'gradient', 'dsplit', 'hypot', 'atleast_1d', 'kron', 'vsplit', 'bincount', 'hstack', 'atleast_2d', 'rot90', 'isposinf', 'conj'}```

**Comment by hirwa-nshuti** [comment]
Hi @mattbarrett98 
These functions should be added to Ivy's functional API. I added all of them to the  [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856) ToDo list. And I am going to close this issue. Thanks!
