### ISSUE TITLE
in case where docker fails, is it advisable to use the venv only?

### ISSUE THREAD

**Issue by ndurumo254** [unifyai/ivy#4966]
in case where docker fails, is it advisable to use the venv only?

_Originally posted by @ndurumo254 in https://github.com/unifyai/ivy/issues/4964#issuecomment-1259046132_

**Comment by hirwa-nshuti** [comment]
Hi, @ndurumo254 basically you don't need to have both Docker and venv installed on your system. If docker is failing for you, you can  install venv and do the needed setup as can be found in the [Setup Guide](https://lets-unify.ai/ivy/contributing/0_setting_up.html#using-venv)
