### ISSUE TITLE
Update Arithmetic Operators to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#50]
Update Arithmetic Operators to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/array_object.html#arithmetic-operators):

- [ ] \_\_pos\_\_
- [x] #509 
- [ ] \_\_add\_\_
- [ ] \_\_sub\_\_
- [ ] \_\_mul\_\_
- [ ] \_\_truediv\_\_
- [ ] \_\_floordiv\_\_
- [ ] \_\_mod\_\_
- [ ] \_\_pow\_\_

**Comment by 1Doomdie1** [comment]
- [ ] #509
