### ISSUE TITLE
 sigmoid

### ISSUE THREAD

**Issue by shoryak** [unifyai/ivy#5153]

**Comment by Monsurat-Onabajo** [comment]
Hello, I want to work on this issue for my contribution for the machine learning engineering role, can I start working on it?

**Comment by sreegandh804** [comment]
Hey @Monsurat-Onabajo 
Feel free to work on this function by creating a new issue and following the instructions given in the contributor's guide accordingly🙂 
https://lets-unify.ai/ivy/contributing.html

**Comment by a0m0rajab** [comment]
related PR: https://github.com/unifyai/ivy/pull/18133
