### ISSUE TITLE
Update Bitwise Operators to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#52]
Update Bitwise Operators to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/array_object.html#bitwise-operators):

- [ ] \_\_invert\_\_
- [ ] \_\_and\_\_
- [ ] \_\_or\_\_
- [ ] \_\_xor\_\_
- [ ] \_\_lshift\_\_
- [ ] \_\_rshift\_\_

**Comment by KenCox94** [comment]
- [ ] #108

**Comment by saniyakolangde** [comment]
-[] #232

**Comment by Nooby10** [comment]
- [ ] #233

**Comment by akaashkasi** [comment]
- [ ] #249

**Comment by jzjackjz** [comment]
- [ ] #248
