### ISSUE TITLE
Update Comparison Operators to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#53]
Update Comparison Operators to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/array_object.html#comparison-operators):

- [ ] \_\_lt\_\_
- [ ] \_\_le\_\_
- [ ] \_\_gt\_\_
- [ ] \_\_ge\_\_
- [ ] \_\_eq\_\_
- [ ] \_\_ne\_\_

**Comment by utkarsh8028** [comment]
- [ ] #301

**Comment by Lopamudrac** [comment]
- [ ] #302

**Comment by rishishounak** [comment]
[ ] #305

**Comment by rishishounak** [comment]
- [ ] #305
