### ISSUE TITLE
Should be added new activation function to ivy/array/activations.py #1

### ISSUE THREAD

**Issue by roostamovic** [unifyai/ivy#5446]
Tanh function which is commonly used as an activation function is now available in the list of activation functions

**Comment by hirwa-nshuti** [comment]
For now, we have `ivy.tanh` function which must be used the same way as the activation function. I don't see any need to re-implement it. See the Docs here [tanh](https://lets-unify.ai/ivy/functional/ivy/elementwise/tanh/tanh_functional.html#ivy-tanh)

Thanks
