### ISSUE TITLE
Update Array Attributes to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#56]
Update Array Attributes to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/array_object.html#attributes):

- [x] #748
- [x] #213
- [x] #749
- [x] #725
- [x] shape
- [x] #575
- [x] T

**Comment by anubhavagr** [comment]
- [ ] #91

**Comment by vnpedroso** [comment]
- [ ] #151

**Comment by uchennayah** [comment]
- [ ] #178

**Comment by dotserver** [comment]
- [ ] #188

**Comment by hubmiles** [comment]
-[] #213

**Comment by TRIPLEMEEN** [comment]
- [ ] #310

**Comment by ShivamPR21** [comment]
mT #345

**Comment by kevingoing214** [comment]
- [ ] #514

**Comment by UsamaHasan** [comment]
https://github.com/unifyai/ivy/issues/575

**Comment by Darshan-H-E** [comment]
-[ ] #579

**Comment by Darshan-H-E** [comment]
- [ ] #579

**Comment by Darshan-H-E** [comment]
- [ ] #580

**Comment by RashulChutani** [comment]
- [ ] #596

**Comment by kartiktripathy** [comment]
- [ ] #613

**Comment by sohil-hub** [comment]
- [ ] #725

**Comment by sohil-hub** [comment]
- [ ] #748

**Comment by sohil-hub** [comment]
Hi, dtype is already implemented.

**Comment by sohil-hub** [comment]
- [ ] #749
