### ISSUE TITLE
bitwise_or #4612

### ISSUE THREAD

**Issue by AlphaPro06** [unifyai/ivy#5677]

**Comment by sreegandh804** [comment]
Hey @AlphaPro06 , you are allowed to only open 3 issues at a time, Feel free to refer to the contributor's guide here : https://lets-unify.ai/ivy/contributing.html

**Comment by AlphaPro06** [comment]
Hey! I was just trying to make sure the ivy bot checkmarks the functions I've worked on. I'm currently waiting for a response to my pull request in #5575

**Comment by sreegandh804** [comment]
Hey @AlphaPro06 , you are supposed to make separate comments for each of the functions you want to get assigned to, where each issue you create needs to be the function name you choose, I would suggest you go through the contributor's guide here: https://lets-unify.ai/ivy/contributing.html or go through our youtube series here: https://www.youtube.com/playlist?list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG
