### ISSUE TITLE
Update Array Methods to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#57]
Update Array Methods to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/array_object.html#methods):

- [ ] #408
- [ ] #471 
- [ ] #401
- [ ] #404
- [ ] \_\_float\_\_
- [ ] \_\_getitem\_\_
- [ ] \_\_index\_\_
- [ ] \_\_int\_\_
- [ ] \_\_setitem\_\_
- [ ] to_device

**Comment by faruq2021** [comment]
#360

**Comment by AparAhuja** [comment]
- [ ] #381

**Comment by utkarsh8028** [comment]
- [ ] #384

**Comment by Lopamudrac** [comment]
- [ ] https://github.com/unifyai/ivy/issues/385

**Comment by omarjpeg** [comment]
- [ ] #389

**Comment by juaolobo** [comment]
- [ ] #396

**Comment by MarShaikh** [comment]
- [ ] #401

**Comment by li-xin-yi** [comment]
- [ ] #408

**Comment by harishsdev** [comment]
hey @djl11  can you please eloborate how to proceed to resolve this PR!

**Comment by faruq2021** [comment]
#471

**Comment by arv0804** [comment]
#380 __getitem__
