### ISSUE TITLE
prod

### ISSUE THREAD

**Issue by AmeenUrRehman** [unifyai/ivy#5713]
- [ ] #3607 add prod

**Comment by sreegandh804** [comment]
hey @AmeenUrRehman , I would suggest you go through the contributor's guide here: https://lets-unify.ai/ivy/contributing.html
which explains how you are supposed to create a comment on the main issue with this issue number which would then automatically assign you the issue.

**Comment by AmeenUrRehman** [comment]
Ok, Thanks
