### ISSUE TITLE
Update Constants to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#59]
Update Constants to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/constants.html):

- [x] #162
- [x] #150
- [x] #570

**Comment by HettyPatel** [comment]
-[ ] #150

**Comment by saeedashrraf** [comment]
- [ ] #162

**Comment by fmilheir** [comment]
- [ ] #308
