### ISSUE TITLE
ivy.serialize

### ISSUE THREAD

**Issue by ItIsUday** [unifyai/ivy#5981]
tf.keras.activations.serialize missing in ivy

**Comment by JoelPendleton** [comment]
Hello, I would suggest you move on to another task for which the relevant Ivy function is implemented. Alternatively, you can try to implement this function as a composition of other functions or implement it yourself on the Ivy functional API or alternatively you can suggest this as an Extend Ivy Functional API task for someone else to do [here](https://github.com/unifyai/ivy/issues/3856).

**Comment by ItIsUday** [comment]
Hey, Thanks for the info. I'll pick another task to work on.
