### ISSUE TITLE
ivy.adjoint

### ISSUE THREAD

**Issue by KareemMAX** [unifyai/ivy#5993]

**Comment by sreegandh804** [comment]
Hey @KareemMAX , You have already created issues related to this function and they have been assigned to you as well, Hence I will be closing these issues.

**Comment by hirwa-nshuti** [comment]
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks!
