### ISSUE TITLE
Update Creation Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#60]
Update Creation Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/creation_functions.html):

- [x] #340
- [x] #255
- [x] #344
- [x] #254
- [x] #258
- [x] #727
- [x] full
- [x] #263
- [x] #316
- [x] #731
- [x] #183
- [x] #270
- [x] #363
- [x] #463 
- [x] #201
- [x] #337

**Comment by zekuixue** [comment]
- [ ] #88

**Comment by alierenak** [comment]
#183

**Comment by alierenak** [comment]
- [ ] #183

**Comment by kirodev** [comment]
- [ ]  #201

**Comment by RickSanchezStoic** [comment]
- [ ] #254

**Comment by MrTooOldDriver** [comment]
- [ ] #255

**Comment by TusharMehra** [comment]
- [ ] #262

**Comment by RitujaPawas** [comment]
- [ ] #263

**Comment by jkeane508** [comment]
- [ ] #270

**Comment by uchennayah** [comment]
#277

**Comment by pantelic-dusan** [comment]
- [ ] #316

**Comment by andy1122** [comment]
- [ ] #337

**Comment by bideeen** [comment]
#340

**Comment by bideeen** [comment]
[arrange] #340

**Comment by bideeen** [comment]
[]#340

**Comment by bideeen** [comment]
[#340 ]

**Comment by bideeen** [comment]
#340

**Comment by rishishounak** [comment]
- [ ] #344

**Comment by hubmiles** [comment]
- [] #362

**Comment by pantelic-dusan** [comment]
- [ ] #363

**Comment by DimitriosSpanos** [comment]
- [ ] #364

**Comment by ebyau** [comment]
- [ ] #377

**Comment by omarjpeg** [comment]
- [] #383

**Comment by rishishounak** [comment]
please see my pr for #344 @djl11 it is pending your review.

**Comment by matthewclso** [comment]
Please direct triu to issue #455 , I implemented triu in order to get qr working

**Comment by djl11** [comment]
> 

We will get this reviewed ASAP! For future reference, please avoid using this comment thread for such requests. These comments should be solely used to claim methods to work on. Thanks!

**Comment by djl11** [comment]
> please see my pr for #344 @djl11 it is pending your review.

We will get this reviewed ASAP! For future reference, please avoid using this comment thread for such requests. These comments should be solely used to claim methods to work on. Thanks!

**Comment by djl11** [comment]
> Please direct triu to issue #455 , I implemented triu in order to get qr working

Please create a new issue for triu, and then comment on this thread with this new issue id. Thanks!

**Comment by matthewclso** [comment]
[ ] #463

**Comment by Darshan-H-E** [comment]
- [ ] #585

**Comment by RashulChutani** [comment]
- [ ] #597

**Comment by tienhoang1094** [comment]
- [ ] #648

**Comment by abdrahmandiab** [comment]
- [ ] #731

**Comment by axelwass** [comment]
- [ ] #900

**Comment by antons4971** [comment]
- [ ] #1006

**Comment by Bobbyorr007** [comment]
- [ ] #1722

**Comment by yudhid** [comment]
- [ ] #316
