### ISSUE TITLE
Update Data Type Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#61]
Update Data Type Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/data_type_functions.html):

- [x] #734
- [x] #704 
- [x] #390
- [x] #797 
- [x] #76
- [x] iinfo
- [x] #599

**Comment by Volthai7us** [comment]
I would like to contribute to this issue. But I doubt about difficulty level. Even though could I try?

**Comment by zekuixue** [comment]
- [ ] #88

**Comment by zekuixue** [comment]
- [ ] #93

**Comment by oryme** [comment]
- [] astype

**Comment by djl11** [comment]
You should create an issue and link that @oryme :)

**Comment by oryme** [comment]
- [] #181

**Comment by oryme** [comment]
> You should create an issue and link that @oryme :)

Thank you, it's done! :)

**Comment by zby-zy** [comment]
- [ ] #246

**Comment by zby-zy** [comment]
- [ ] #264

**Comment by zby-zy** [comment]
- [ ] #265

**Comment by zby-zy** [comment]
- [ ] #266

**Comment by su-hss** [comment]
- [ ] #369

**Comment by goyalrinki** [comment]
- [ ] #374

**Comment by uchennayah** [comment]
- [ ] broadcast-to

**Comment by uchennayah** [comment]
- [ ] broadcast_to

**Comment by uchennayah** [comment]
- [ ] broadcast_to

**Comment by uchennayah** [comment]
- [ ] broadcast_to

**Comment by eking772** [comment]
- [ ] #409

**Comment by 2cai** [comment]
-[ ] result_type

**Comment by 2cai** [comment]
- [ ] #88

**Comment by kevingoing214** [comment]
- [ ] #515

**Comment by 1Doomdie1** [comment]
- [ ] #511

**Comment by RashulChutani** [comment]
- [ ] #599

**Comment by Darshan-H-E** [comment]
- [ ] #604

**Comment by Auxia** [comment]
- [ ] #691

**Comment by samiesaheb** [comment]
- [ ] #704

**Comment by Aarsh2001** [comment]
- [ ] #734

**Comment by sohil-hub** [comment]
- [ ] #797
