### ISSUE TITLE
Update Data Types to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#62]
Update Data Types to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/data_types.html):

**Integer Data Types**

- [x] int8
- [x] int16
- [x] int32
- [x] int64
- [x] uint8
- [x] uint16
- [x] uint32
- [x] uint64

**Floating-point Data Types**

- [x] float32
- [x] float64

**Boolean Data Types**

- [x] bool

**Comment by zekuixue** [comment]
int8 #88

**Comment by zekuixue** [comment]
- [ ] #88

**Comment by zekuixue** [comment]
- [ int8] #88

**Comment by zekuixue** [comment]
[] #88

**Comment by zekuixue** [comment]
- [ ] #88
