### ISSUE TITLE
Update Element-wise Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#63]
Update Element-wise Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html):

- [x] #506 
- [x] #468 
- [x] #464 
- [x] #741
- [x] #262
- [x] #271
- [x] #630
- [x] #674
- [x] #683
- [x] #673 
- [x] #752
- [x] #470 
- [x] #498 
- [x] #370
- [x] #723 
- [x] #86 
- [x] #156
- [x] #239
- [x] #300
- [x] #626
- [x] #739
- [x] #576
- [x] #501 
- [x] #325
- [x] #465 
- [x] #220
- [x] #705
- [x] #146
- [x] #154
- [x] #126
- [x] #272
- [x] #595 
- [x] #333
- [x] #330
- [x] #487 
- [x] #583 
- [x] #530  
- [x] #180
- [x] #491 
- [x] #636
- [x] #667
- [x] #222
- [x] #538 
- [x] #426 
- [x] #799
- [x] #627
- [x] #226
- [x] #742
- [x] #462
- [x] #502 
- [x] #519 
- [x] #221
- [x] #217
- [x] #227
- [x] #242
- [x] #371

**Comment by mattbarrett98** [comment]
[] #86

**Comment by DhruvSondhi** [comment]
- [ ] #95

**Comment by Slijeff** [comment]
-[ ] #120

**Comment by saeedashrraf** [comment]
- [ ]  #126

**Comment by NIkhilbadveli** [comment]
- [ ] #130

**Comment by neerajk** [comment]
- [ ]  #139

**Comment by taltrums** [comment]
[] isinf #146

**Comment by badershafiq** [comment]
- [ ] https://github.com/unifyai/ivy/issues/149

**Comment by HotzingTone** [comment]
- [ ] #154

**Comment by Ishticode** [comment]
- [ ] #156

**Comment by julian-8897** [comment]
- [ ] #159

**Comment by rana-shahroz** [comment]
- [ ] #176

**Comment by mattbarrett98** [comment]
[] #180

**Comment by VirtualSpaceman** [comment]
- [ ] #185

**Comment by shraavanchess2000** [comment]
- [] #198

**Comment by neerajk** [comment]
- [ ] #199

**Comment by avdhootmukhedkar** [comment]
- [ ] #207

**Comment by Abdelrhman-Hosny** [comment]
#211

**Comment by rupsgrover** [comment]
- [ ] #217

**Comment by TudorAndrei** [comment]
- [ ] #218

**Comment by thecoder12** [comment]
- [ ] #220

**Comment by ZeynelAbidin91** [comment]
- [ ] #221

**Comment by UditArora2000** [comment]
- [ ] #222

**Comment by Mizt1c** [comment]
- [ ] #225

**Comment by Mizt1c** [comment]
- [ ] tan

**Comment by Mizt1c** [comment]
- [ ] #227

**Comment by CtrlAltDeleep** [comment]
not_equal #234

**Comment by harshitaseth** [comment]
- [ ] #236

**Comment by Devansh-0** [comment]
- [ ] #237

**Comment by Devansh-0** [comment]
- [ ] #238

**Comment by 1Doomdie1** [comment]
- [ ] #239

**Comment by VictorVenid** [comment]
-[] #241

**Comment by VictorVenid** [comment]
-[ ] bitwise_and #241

**Comment by simonetgordon** [comment]
[] tanh

**Comment by UmairAhmd** [comment]
- [ ] #252

**Comment by TusharMehra** [comment]
- [ ] #262

**Comment by alexwavrant** [comment]
- [ ] #268

**Comment by artu1999** [comment]
- [ ] #269

**Comment by 1Doomdie1** [comment]
- [ ] #271

**Comment by georg-wolflein** [comment]
- [ ] #272

**Comment by MRRH-Codes** [comment]
[]#273

**Comment by MRRH-Codes** [comment]
- [ ] #273

**Comment by alexpondaven** [comment]
- [ ] #278

**Comment by ced-kin** [comment]
- [ ] #281

**Comment by andreas-katsou** [comment]
- [ ]#293

**Comment by PatChizzy** [comment]
- [ ] #300

**Comment by yunus-kalkan** [comment]
- [ ] #306

**Comment by lorenzflow** [comment]
- [ ] #319

**Comment by Hilal-Urun** [comment]
- [ ] #321

**Comment by kevinsu2024** [comment]
- [ ] #325

**Comment by Xoisai** [comment]
- [] #326

**Comment by HD-robotics** [comment]
- [ ]  atan2

**Comment by HD-robotics** [comment]
- [ ] bitwise_invert

**Comment by djl11** [comment]
You need to create an issue and link that @HD-robotics

**Comment by sert121** [comment]
> Update Element-wise Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html):
> 
> * [x]  [abs #120](https://github.com/unifyai/ivy/issues/120)
> * [ ]  [acos #176](https://github.com/unifyai/ivy/issues/176)
> * [ ]  [acosh #269](https://github.com/unifyai/ivy/issues/269)
> * [ ]  [add #139](https://github.com/unifyai/ivy/issues/139)
> * [ ]  [asin #262](https://github.com/unifyai/ivy/issues/262)
> * [x]  [asinh #271](https://github.com/unifyai/ivy/issues/271)
> * [ ]  [atan #252](https://github.com/unifyai/ivy/issues/252)
> * [ ]  [atan2 #326](https://github.com/unifyai/ivy/issues/326)
> * [ ]  [atanh #306](https://github.com/unifyai/ivy/issues/306)
> * [x]  [bitwise_and #241](https://github.com/unifyai/ivy/issues/241)
> * [ ]  [bitwise_left_shift #278](https://github.com/unifyai/ivy/issues/278)
> * [ ]  bitwise_invert
> * [ ]  [bitwise_or #268](https://github.com/unifyai/ivy/issues/268)
> * [ ]  bitwise_right_shift
> * [ ]  bitwise_xor
> * [ ]  [ceil #86](https://github.com/unifyai/ivy/issues/86)
> * [x]  [cos #156](https://github.com/unifyai/ivy/issues/156)
> * [x]  [cosh #239](https://github.com/unifyai/ivy/issues/239)
> * [ ]  [divide #300](https://github.com/unifyai/ivy/issues/300)
> * [ ]  [equal #198](https://github.com/unifyai/ivy/issues/198)
> * [ ]  [exp #185](https://github.com/unifyai/ivy/issues/185)
> * [ ]  [expm1 #321](https://github.com/unifyai/ivy/issues/321)
> * [ ]  [floor #149](https://github.com/unifyai/ivy/issues/149)
> * [ ]  [floor_divide #325](https://github.com/unifyai/ivy/issues/325)
> * [ ]  [greater  #236](https://github.com/unifyai/ivy/issues/236)
> * [ ]  [greater_equal #220](https://github.com/unifyai/ivy/issues/220)
> * [x]  isfinite
> * [x]  [isinf #146](https://github.com/unifyai/ivy/issues/146)
> * [x]  [ isnan #154](https://github.com/unifyai/ivy/issues/154)
> * [x]  [less #126](https://github.com/unifyai/ivy/issues/126)
> * [ ]  [less_equal #272](https://github.com/unifyai/ivy/issues/272)
> * [ ]  [log #218](https://github.com/unifyai/ivy/issues/218)
> * [ ]  log1p
> * [ ]  log2
> * [ ]  [log10 #293](https://github.com/unifyai/ivy/issues/293)
> * [ ]  logaddexp
> * [ ]  [logical_and #281](https://github.com/unifyai/ivy/issues/281)
> * [x]  [logical_not #180](https://github.com/unifyai/ivy/issues/180)
> * [ ]  [logical_or #319](https://github.com/unifyai/ivy/issues/319)
> * [ ]  logical_xor
> * [ ]  [multiply #215](https://github.com/unifyai/ivy/issues/215)
> * [ ]  [negative #222](https://github.com/unifyai/ivy/issues/222)
> * [ ]  [not_equal #234](https://github.com/unifyai/ivy/issues/234)
> * [ ]  [positive #199](https://github.com/unifyai/ivy/issues/199)
> * [ ]  [pow #273](https://github.com/unifyai/ivy/issues/273)
> * [ ]  [remainder #238](https://github.com/unifyai/ivy/issues/238)
> * [ ]  [round #226](https://github.com/unifyai/ivy/issues/226)
> * [ ]  [sign #135](https://github.com/unifyai/ivy/issues/135)
> * [ ]  [ sin #207](https://github.com/unifyai/ivy/issues/207)
> * [ ]  [sinh #159](https://github.com/unifyai/ivy/issues/159)
> * [ ]  [square #130](https://github.com/unifyai/ivy/issues/130)
> * [x]  [sqrt #221](https://github.com/unifyai/ivy/issues/221)
> * [ ]  [subtract #217](https://github.com/unifyai/ivy/issues/217)
> * [x]  [tan #227](https://github.com/unifyai/ivy/issues/227)
> * [ ]  [tanh #242](https://github.com/unifyai/ivy/issues/242)
> * [ ]  trunc
> [ ] [bitwise_xor #329](https://github.com/unifyai/ivy/issues/329)

**Comment by 1Doomdie1** [comment]
- [ ] #330

**Comment by 1Doomdie1** [comment]
- [ ] #333

**Comment by amit828as** [comment]
- [] #354

**Comment by mcRobusta** [comment]
sqrt #221

**Comment by Shoa29** [comment]
- [ ] #368

**Comment by VedPatwardhan** [comment]
- [ ] #370

**Comment by Oluwadurotimi10** [comment]
- [ ] #371

**Comment by sounritesh** [comment]
bitwise_invert #373

**Comment by sounritesh** [comment]
[bitwise_invert] #373

**Comment by sounritesh** [comment]
- [] #373

**Comment by sounritesh** [comment]
- #373

**Comment by sounritesh** [comment]
- [ ] #373

**Comment by AparAhuja** [comment]
-[]#268

**Comment by chie2727** [comment]
- [ ] #199

**Comment by chie2727** [comment]
- [ ] #426

**Comment by matthewclso** [comment]
Please direct triu to issue #455 , I implemented triu in order to get qr working

**Comment by Volthai7us** [comment]
- [ ] #465

**Comment by dmarinere** [comment]
#468

**Comment by ebyau** [comment]
- [ ] #470

**Comment by uchennayah** [comment]
- [ ] add

**Comment by uchennayah** [comment]
- [ ] add

**Comment by rahulr2003** [comment]
#479

**Comment by saurbhc** [comment]
- [ ] #487

**Comment by goyalrinki** [comment]
- [ ] #491

**Comment by chie2727** [comment]
- [ ] pow

**Comment by chie2727** [comment]
- [ ] #273

**Comment by chie2727** [comment]
- [ ] #494

**Comment by bicycleman15** [comment]
- [ ] #498

**Comment by dmarinere** [comment]
#500

**Comment by zby-zy** [comment]
- [ ] #502

**Comment by 2cai** [comment]
- [ ] #501

**Comment by sounritesh** [comment]
- [ ] #506

**Comment by codeboy5** [comment]
* [ ]  [abs #507 ](https://github.com/unifyai/ivy/issues/507)

**Comment by kevinxue1126** [comment]
- [ ] #519

**Comment by Lopamudrac** [comment]
- [ ] #520

**Comment by kevinxue1126** [comment]
- [ ] #522

**Comment by horair** [comment]
#530

**Comment by Bobbyorr007** [comment]
- [ ] #534

**Comment by Christoforos00** [comment]
- [ ] #537

**Comment by tayoshittu** [comment]
- [ ] #576

**Comment by MarShaikh** [comment]
- [ ] #583

**Comment by 1Doomdie1** [comment]
test duplicate issue #472

**Comment by aayushgoyal443** [comment]
- [] #629

**Comment by aayushgoyal443** [comment]
- [ ] #629

**Comment by Darshan-H-E** [comment]
- [ ] #630

**Comment by aayushgoyal443** [comment]
- [ ] #631

**Comment by pankajrajput0312** [comment]
#633

**Comment by sreegandh804** [comment]
- [ ] #636

**Comment by 2cai** [comment]
#644

**Comment by 2cai** [comment]
[ ] #644

**Comment by juaolobo** [comment]
- [ ] #645

**Comment by abhinine4** [comment]
- [ ] #673

**Comment by kirodev** [comment]
[ ] #306

**Comment by kirodev** [comment]
[ ] : #306

**Comment by kirodev** [comment]
[ ] : #683

**Comment by sohil-hub** [comment]
- [ ] #705

**Comment by codeboy5** [comment]
[ ] #706

**Comment by hieultp** [comment]
- [ ] #721

**Comment by sohil-hub** [comment]
- [ ] #722

**Comment by sohil-hub** [comment]
- [ ] #723

**Comment by rush2406** [comment]
- [ ] #739

**Comment by sohil-hub** [comment]
- [ ] #741

**Comment by rush2406** [comment]
- [ ] #742

**Comment by sohil-hub** [comment]
- [ ] 746

**Comment by sohil-hub** [comment]
- [ ] #746

**Comment by YsBsr** [comment]
- [ ] #752

**Comment by JIAHAN-XIE** [comment]
- [ ] #799
