### ISSUE TITLE
Kornia torch frontend functions

### ISSUE THREAD

**Issue by nassimberrada** [unifyai/ivy#6430]
As part of the [ODSC West](https://odsc.com/california/) demo, we would like to show a couple examples of transpiling [kornia](https://kornia.github.io/) functions. Specifically, [kornia.filters.canny](https://github.com/kornia/kornia/blob/696a31ead1f0b8fa706394450d420ace7f010eeb/kornia/filters/canny.py#L15) and [kornia.morphology.dilation](https://github.com/kornia/kornia/blob/696a31ead1f0b8fa706394450d420ace7f010eeb/kornia/morphology/morphology.py#L15).

The task here is to implement each of these `torch` frontend functions, which are used by these two kornia functions as follows.

`kornia.filters.canny`

- [x] #6431
- [x] #6432
- [x] #6433
- [x] #6434
- [x] #6435
- [x] #6436
- [x] #6707
- [x] #6720
- [x] #6721

`kornia.morphology.dilation`

- [x] #6437
- [x] #6438
- [x] #6439
- [x] #6440

Please assign yourself to your issue of interest and ALSO reserve that same function on the corresponding ToDo list issue !

**Comment by CerberusLatrans** [comment]
- [ ] #6706
