### ISSUE TITLE
Update Indexing to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#65]
Update indexing to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/indexing.html)

**Comment by MrTooOldDriver** [comment]
- [ ] #82

**Comment by MrTooOldDriver** [comment]
@djl11 Hi, the indexing test is blocked by asarray function(actually quite a lot of tests depends on asarray) Since I haven't dived too deep just yet, so shall I wait for this function to get implemented or I could go pick something else? :D

**Comment by MrTooOldDriver** [comment]
Depending on function asarray, I will go sort that function out first.
