### ISSUE TITLE
Update Linear Algebra Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#66]
Update Linear Algebra Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/linear_algebra_functions.html):

- [x] #109
- [x] #573
- [x] #346
- [x] #115

**Comment by joseph-adikwu** [comment]
- [ ] #168

**Comment by TomHurford** [comment]
- [] #173

**Comment by BillelBenoudjit** [comment]
- [ ] #205

**Comment by ThehandofgodAI** [comment]
- [ ] #208

**Comment by artu1999** [comment]
- [] #267

**Comment by elias-dzobo** [comment]
-[] #296

**Comment by martinoywa** [comment]
- [ ] #346

**Comment by nebilarega** [comment]
#478

**Comment by juliagsy** [comment]
matrix_transpose #496

**Comment by foobarrymore** [comment]
- [ ] #573
