### ISSUE TITLE
Update Manipulation Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#67]
Update Manipulation Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/manipulation_functions.html):

- [x] #681
- [x] #529 
- [x] #256
- [x] #568
- [x] #788
- [x] #688
- [x] #670
- [x] #496

**Comment by dotserver** [comment]
- [ ] #191

**Comment by ThehandofgodAI** [comment]
- [ ] #209

**Comment by TudorAndrei** [comment]
- [ ] #210

**Comment by MudasserAfzal** [comment]
- [ ] #230

**Comment by konpg7** [comment]
- [ ] #251

**Comment by pantelic-dusan** [comment]
- [ ] #256

**Comment by arxxv** [comment]
- [ ] #288

**Comment by eliasqarmash** [comment]
- [ ] #299

**Comment by Xinran97** [comment]
- [] #525

**Comment by BayerGleb** [comment]
- [ ] #529

**Comment by juliagsy** [comment]
[stack] #496

**Comment by mehtamohit013** [comment]
- [ ] #568

**Comment by HadIhab** [comment]
- [ ] #670

**Comment by nkennebre** [comment]
-[]#688

**Comment by patrickf949** [comment]
- [ ] #813
