### ISSUE TITLE
local_response_normalization

### ISSUE THREAD

**Issue by mohamedehab0999** [unifyai/ivy#6704]
### Description

TensorFlow Frontend

### Task List

- [ ]  local_response_normalization

**Comment by MutugiD** [comment]
Will push PR

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would like to continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues

**Comment by modanesh** [comment]
reopening the issue since the `local_response_normalization` test is failing in the TF frontned
