### ISSUE TITLE
ivy.expm()

### ISSUE THREAD

**Issue by atakanoc** [unifyai/ivy#6737]
This function is available on [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.linalg.expm.html), [PyTorch](https://pytorch.org/docs/stable/generated/torch.linalg.matrix_exp.html#torch.linalg.matrix_exp), [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/expm) and [Numpy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.expm.html). Implementing this mathematical function manually for the frontends would be a lot more complex than simple wrapping with Ivy, I suggest an Ivy function to be implemented for it. ☺️

**Comment by hirwa-nshuti** [comment]
Hi,
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks🙂
