### ISSUE TITLE
ivy.eigvals

### ISSUE THREAD

**Issue by atakanoc** [unifyai/ivy#6741]
Function is present in [PyTorch](https://pytorch.org/docs/stable/generated/torch.linalg.eigvals.html#torch.linalg.eigvals), [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/eigvals), [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvals.html), [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.eigvals.html) and [MXNet](https://mxnet.apache.org/versions/master/api/python/docs/api/np/generated/mxnet.np.linalg.eigvals.html).

**Comment by hirwa-nshuti** [comment]
Hi,
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks🙂
