### ISSUE TITLE
Update Searching Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#68]
Update Searching Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/searching_functions.html):

- [x] #99
- [x] #623 
- [x] #772
- [x] #769

**Comment by 7wikd** [comment]
- [] #99

**Comment by 7wikd** [comment]
Doubt: Do I have to create a new file for searching functions, since I could not find one?

**Comment by djl11** [comment]
I would suggest to just add these to general.py, we can always refactor these into a separate module at a later stage.

**Comment by 7wikd** [comment]
Yet another doubt: the functions for argmax are already present in the respective general.py files in the /ivy/functional/backends. Do I have to conform it to suit the Array API Standard only? Or do I also have to add them to the /ivy/array/general.py file?

**Comment by jakeKonrad** [comment]
- [ ]  #155

**Comment by suyog-pipliwaal** [comment]
- [ ] #189

**Comment by shantam-8** [comment]
- [ ] #216

**Comment by 2cai** [comment]
- [ ] #189

**Comment by 2cai** [comment]
- [ ] #518

**Comment by argoopjmc** [comment]
- [ ] #552

**Comment by zaeemansari70** [comment]
- [ ] #623

**Comment by alizahidraja** [comment]
where #640

**Comment by Chidiblaq** [comment]
#664

**Comment by nkennebre** [comment]
-[]#687

**Comment by sohil-hub** [comment]
- [ ] #689
