### ISSUE TITLE
Add Docstrings to mul & rmul func in array

### ISSUE THREAD

**Issue by nadidebeyza** [unifyai/ivy#6854]
### Description

Docstrings mul & rmul

### Task List

- [ ] ✅ Add Docstrings to mul & rmul functions in reformatting ivy>array>array.py
- [ ] ✅ Add Docstrings Examples to mul & rmul functions in reformatting ivy>array>array.py

**Comment by nadidebeyza** [comment]
add_reformatting_checklist_Docstrings

**Comment by hirwa-nshuti** [comment]
Hi @nadidebeyza 
I see that you wanted to add docstrings to the `ivy.Array` class methods which we are not doing for now.
I would suggest you follow the [contributing guide](https://lets-unify.ai/ivy/contributing.html#) to know the open tasks and guidance to contribute to ivy in general.
I am going to close this issue and meanwhile feel free to allocate yourself with another open task to work on.
Thanks🙂

**Comment by nadidebeyza** [comment]
Hi @hirwa-nshuti 
I was trying to figure out the system and I understood in the last weekend. Sorry for the confusion. Thank you.
