### ISSUE TITLE
ivy.<logit>

### ISSUE THREAD

**Issue by zhengyaogu** [unifyai/ivy#6879]
**Why should this be implemented?**
Because 3+ of the native frameworks have it, and it's a complex function.

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.special.logit.html)
- [PyTorch](https://pytorch.org/docs/stable/special.html#torch.special.logit)
- [TensorFlow] NA
- [NumPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logit.html)
- [MXNet] NA

**Comment by hirwa-nshuti** [comment]
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks!
