### ISSUE TITLE
Update Set Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#69]
Update Set Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/set_functions.html):

- [x] #813
- [x] #145
- [x] #528 
- [x] #584

**Comment by Ferox98** [comment]
- [ ] #106

**Comment by JacksonMHoke** [comment]
- [ ] #161

**Comment by heetshah16** [comment]
- [ ] #163

**Comment by sherry30** [comment]
- [ ] #505

**Comment by maraPislar** [comment]
- [ ] unique-inverse #528

**Comment by olivercromwell0214** [comment]
- [ ] #528

**Comment by Archymade** [comment]
- [ ] #539

**Comment by Aisha-Hagar** [comment]
- [ ] #584

**Comment by patrickf949** [comment]
- [ ] #813

**Comment by patrickf949** [comment]
- [ ] #815
