### ISSUE TITLE
ivy.eigh_tridiagonal

### ISSUE THREAD

**Issue by Aaa2275** [unifyai/ivy#6933]
**Why should this be implemented?**
Because 2 of the native frameworks have it, and it's a complex function.

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.linalg.eigh_tridiagonal.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/eigh_tridiagonal)

**Comment by CheezBallzPi** [comment]
I've added this function to the Extend Ivy Functional API task (#3856). Closing.
