### ISSUE TITLE
Add jax.numpy namespace functions to Jax frontend

### ISSUE THREAD

**Issue by Taciturny** [unifyai/ivy#6994]
### Description

Add jax.numpy namespace functions to Jax frontend

### Task List

- [ ] amax
- [ ] amin

**Comment by sreegandh804** [comment]
Hey There if you would like to pick a sub-task please use the sub-task template, the ToDo list template is meant for members of our team to create lists of functions for open-source contributors to work on. I will be closing this issue now. 🙂
