### ISSUE TITLE
Add Tensor functions to PyTorch Frontend

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#7]
Add [Tensor functions](https://pytorch.org/docs/stable/torch.html#tensors) to PyTorch frontend:

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #2865 
- [x] #9903
- [x] #6830
- [x] #4975
- [x] #4977
- [x] #4976

**Comment by agniiyer** [comment]
#3298

**Comment by AnnaTz** [comment]
- [ ] #4975

**Comment by AnnaTz** [comment]
- [ ] #4976

**Comment by AnnaTz** [comment]
- [ ] #4977

**Comment by AnnaTz** [comment]
- [ ] #4980

**Comment by artykov1511** [comment]
#6830

**Comment by HadeerArafa108** [comment]
- [ ] #9903

**Comment by rumbleFTW** [comment]
Hey can I work on this issue?
Additionally, I'm a newbie contributor here, so might be a dumb question to ask, but-
Where do I implement these functions? There's no directory as pytorch frontend

**Comment by AnnaTz** [comment]
> Hey can I work on this issue? Additionally, I'm a newbie contributor here, so might be a dumb question to ask, but- Where do I implement these functions? There's no directory as pytorch frontend

Hi there! All the functions in this ToDo list are already implemented (they are linked to issues and checked already as you can see above). Feel free to choose a free function from another ToDo list. 
I think you'll find this [guide](https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis) useful. It also explains where to add the functions.

**Comment by rumbleFTW** [comment]
Thank you!
