### ISSUE TITLE
Update Sorting Functions to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#70]
Update Sorting Functions to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/sorting_functions.html):

- [x] #100
- [x] #625

**Comment by pantelic-dusan** [comment]
- [ ] #100

**Comment by evabanegacom** [comment]
- [ ] #128

**Comment by MoAmrYehia** [comment]
**sort** #80

**Comment by alexwavrant** [comment]
- [ ] #512

**Comment by bethelhall** [comment]
- [ ] #625

**Comment by onyekaokonji** [comment]
- [ ] #655
