### ISSUE TITLE
[Bug]: <Wrong type replacement in assert_all_close() function>

### ISSUE THREAD

**Issue by salvo96** [unifyai/ivy#7001]
### Bug Explanation

The function in assertions.py is expected to assert if ret_np and ret_from_gt_np inputs are the same element-by-element. The function checks initially if the two types are equal, expecting a type for the data returned by the backend equal to `int64` and converting the data returned by the groundtruth backend (Tensorflow) to `int64`. The convertion should be done from `int32` to `int64`, while it is done by a substring replacement from `longlong` to `int64` which never matches in the executed tests.
<img width="1093" alt="Screenshot 2022-11-14 alle 12 05 30" src="https://user-images.githubusercontent.com/19409488/201644758-b1f52b22-1ac4-493e-a172-e4f25a9a265a.png">

### Steps to Reproduce Bug

The bug happens when testing the function defined in #6964 

### Environment

Mac OS X using PyCharm and conda virtual environment

### Ivy Version

1.1.9

### Backend

- [X] NumPy
- [X] TensorFlow
- [X] PyTorch
- [X] JAX
- [ ] MXNet

**Comment by Ishticode** [comment]
I see this issue is assigned to @CatB1t. Any leads on this @CatB1t as the PR #7064 depends on this.

**Comment by CatB1t** [comment]
Hello @salvo96 , this does not seem to be a bug, we do string replacement when the backend returns a tensor with `longlong` dtype, which is equivalent to `int64`, and it only happens if the return dtype is `longlong`, in the case of `int64`, we shouldn't replace it by `int32`.
