### ISSUE TITLE
real() in backend functional APIs

### ISSUE THREAD

**Issue by afif-malghani** [unifyai/ivy#7148]
The implementation of this function will assist in the implementation of real() for frontends.

- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.real.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.real.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/math/real)
- [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.real.html)

**Comment by hirwa-nshuti** [comment]
Hi,
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). 
Therefore, this issue will now be closed. Thanks🙂
