### ISSUE TITLE
Update Type Promotion Rules to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#72]
Update Type Promotion Rules to Conform to [Array API Standard](https://data-apis.org/array-api/latest/API_specification/type_promotion.html)

**Comment by Ishticode** [comment]
"Does this mean to implement a new ivy function (like ivy.promote_types) taking arrays and promoting their types according to Array API,  or is this something more fundamental/complex?
Array api website doesnt seem have an exclusive function for it though and neither a test implemented.

**Comment by djl11** [comment]
This is a great point, I will close this issue. The type promotion rules should be implicit in all Array API tests. Thanks for flagging this @Ishticode.
