### ISSUE TITLE
[Bug]: Error on ivy.zeros when using Containers

### ISSUE THREAD

**Issue by Sequeira8** [unifyai/ivy#7213]
### Bug Explanation

After running the code with Containers, the exception tells me I am using 6 positional arguments, which is strange as I only send shape which is equal to `ivy.Container(a=ivy.NativeShape((2, 1)), b=ivy.Shape((2, 1, 2)))`
Not entirely sure it only fails on numpy
`ivy.exceptions.IvyBackendException: numpy: zeros: zeros() takes 1 positional argument but 6 positional arguments (and 2 keyword-only arguments) were given`

### Steps to Reproduce Bug

`shape = ivy.Container(a=ivy.NativeShape((2, 1)), b=ivy.Shape((2, 1, 2)))`
`dtype = ivy.Container(a=ivy.float64, b=ivy.int32)`
`device = ivy.Container(a=ivy.NativeDevice('cpu'), b=ivy.Device('cpu'))`
`x = ivy.zeros(shape, dtype=dtype, device=device)`

### Environment

Windows 11 & PyCharm & Docker

### Ivy Version

v1.1.9

### Backend

- [X] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX
- [ ] MXNet

### Device

CPU: 12th Gen Intel(R) Core(TM) i9-12900

**Comment by Nightcrab** [comment]
Fixed in commit d6b303f47837f8ef09542ee310384d8f601fe401.
