### ISSUE TITLE
ivy.binary_cross_entropy_with_logits

### ISSUE THREAD

**Issue by bipinKrishnan** [unifyai/ivy#7295]
This issue is raised as a result of the discussion [here](https://github.com/unifyai/ivy/pull/7076#issuecomment-1324023470).

**Why should this be implemented?**
Because 2 of the native frameworks have it, and it's a complex function.

**Links to native framework implementations**
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.functional.binary_cross_entropy_with_logits.html#torch.nn.functional.binary_cross_entropy_with_logits)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/nn/weighted_cross_entropy_with_logits)(with positional weights)
- [Tensorflow](https://www.tensorflow.org/api_docs/python/tf/nn/sigmoid_cross_entropy_with_logits)(without positional weights)

**Comment by bipinKrishnan** [comment]
@ogbanugot Just wanted to let you know that I'm already working on an implementation for this as per the discussion [here](https://github.com/unifyai/ivy/pull/7076#issuecomment-1325153443).

**Comment by ogbanugot** [comment]
> @ogbanugot Just wanted to let you know that I'm already working on an implementation for this as discussed [here](https://github.com/unifyai/ivy/pull/7076#issuecomment-1325153443).

Sure no problem, thanks!
