### ISSUE TITLE
clamp

### ISSUE THREAD

**Issue by SaabriinMo** [unifyai/ivy#7343]

**Comment by SaabriinMo** [comment]
#7343

**Comment by SaabriinMo** [comment]
Ive been directed here to ask for help!

I'm getting a really unusual error!

if i use -> https://github.com/unifyai/ivy/blob/b3494be231a951381ec5e95979f72959cdc76ec5/ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py#L41-L50

 i get this error!

`"E AttributeError: 'function' object has no attribute 'test_data'"`

if i use the  i get this error
https://github.com/unifyai/ivy/blob/b3494be231a951381ec5e95979f72959cdc76ec5/ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py#L52-L62

`["E fixture 'as_variable' not found"
]`
im currently trying to solve the problem myself but some insight can help thanks!

ps. you'll see many changes due to me just testing different things to get a better understanding of implementing testing stage

**Comment by nathzi1505** [comment]
@jkeane508 would you like to look into this issue?

**Comment by SaabriinMo** [comment]
i managed to misread the documentation and now i think i got it to work!

Now i got this weird cpu error!
[error_for_clamp.txt](https://github.com/unifyai/ivy/files/10095658/error_for_clamp.txt)
sorry for the spam 😭 

The new edited code for reference:
```@handle_frontend_method(
    method_tree="torch.tensor.clamp",
    dtype_and_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("float"),
        num_arrays=2,
    ),
    as_variable = st.booleans(),
    native_array = st.booleans(),
)
def test_torch_instance_clamp(
    dtype_and_x,
    as_variable,
    native_array,
    class_,
    method_name,
):
    input_dtype, x = dtype_and_x
    helpers.test_frontend_method(
        init_input_dtypes=input_dtype,
        init_as_variable_flags=as_variable,
        init_num_positional_args=1,
        init_all_as_kwargs_np= {
            "data": x[0],
        },
        init_native_array_flags=native_array,
        method_input_dtypes=input_dtype,
        method_as_variable_flags=as_variable,
        method_native_array_flags=native_array,
        method_all_as_kwargs_np={
            "min":-1,
            "max":1,
        },
        method_num_positional_args=1,
        frontend="torch",
        class_= Tensor,
        method_name="clamp",
    )
````
