### ISSUE TITLE
Update Linear Algebra Extension to Conform to Array API Standard

### ISSUE THREAD

**Issue by djl11** [unifyai/ivy#74]
Update Linear Algebra Extension to Conform to [Array API Standard](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html):

- [x] #172
- [x] #661
- [x] #116
- [x] #121
- [x] #615
- [x] #434 
- [x] #433 
- [x] #432 
- [x] #445 
- [x] #343
- [x] #675 
- [x] #90
- [x] #441 
- [x] #660 
- [x] #455 
- [x] #289
- [x] #628
- [x] #124
- [x] #461 
- [x] #346
- [x] #450 
- [x] #617
- [x] #113

**Comment by Ishticode** [comment]
- [ ] #81

**Comment by djl11** [comment]
- [ ] #83

**Comment by swaroop516** [comment]
[ ] #90

**Comment by kushaldev75** [comment]
[] #96

**Comment by ateebkhan96** [comment]
- [ ] #103

**Comment by kene111** [comment]
- [ ]  #113

**Comment by saurav935** [comment]
- [ ] #121

**Comment by nnitiwe-dev** [comment]
[ ] #124

**Comment by berat-ademi** [comment]
- [ ] #141

**Comment by MohammedJassem** [comment]
- [ ] #144

**Comment by Lacutee** [comment]
[] #148

**Comment by Lacutee** [comment]
[ ] #148

**Comment by HotzingTone** [comment]
- [ ] #153

**Comment by heetshah16** [comment]
- [ ] #164

**Comment by JonBenusa** [comment]
#166

**Comment by Eslam-Zaher** [comment]
#170

**Comment by davidry777** [comment]
- [] #184

**Comment by davidry777** [comment]
- [ ] #184

**Comment by shubhbrth** [comment]
-[ ] #200

**Comment by dineshKumb** [comment]
- [ ] #245

**Comment by HotzingTone** [comment]
- [ ] #258

**Comment by HotzingTone** [comment]
- [ ] #258

**Comment by mehroz422** [comment]
- [ ] #261

**Comment by AnimeshGurjar** [comment]
- [ ] #289

**Comment by martinoywa** [comment]
[ ] #343

**Comment by martinoywa** [comment]
- [ ] #346

**Comment by SayanJerr** [comment]
matrix_rank #170

**Comment by andy1122** [comment]
> * [ ]  [matrix_rank #414](https://github.com/unifyai/ivy/issues/414)

Hi, It seems like this function is already assigned to someone(#170) else.

**Comment by SayanJerr** [comment]
- [ ] #414

**Comment by SayanJerr** [comment]
> 

There is literally no task available

**Comment by sherry30** [comment]
[] #432

**Comment by SayanJerr** [comment]
- [ ] #433

**Comment by patrickf949** [comment]
- [ ] #435

**Comment by SayanJerr** [comment]
- [ ] #433

**Comment by andy1122** [comment]
#436

**Comment by MoAmrYehia** [comment]
> * [ ]  matrix_norm

**Comment by 1Doomdie1** [comment]
> * matrix_norm
Hi, thank you for contributing to Ivy!
Can you please first create an issue with the name of the function you want to implement and edit you comment with the issue ID?
see more: https://lets-unify.ai/ivy/contributing.html

**Comment by eking772** [comment]
- [ ] #437

**Comment by Husain-Ayoob** [comment]
- [ ] #441

**Comment by Husain-Ayoob** [comment]
- [ ] #441

**Comment by MoAmrYehia** [comment]
>     * [ ]  [matrix_norm](https://github.com/unifyai/ivy/issues/445)

**Comment by JudeDavis1** [comment]
- [ ] #447

**Comment by JudeDavis1** [comment]
- [ ] #450

**Comment by gopika-syam** [comment]
-[ ] #451

**Comment by gopika-syam** [comment]
- [ ] #451

**Comment by matthewclso** [comment]
- [ ] #455

**Comment by horair** [comment]
[]#459

**Comment by Tyred** [comment]
- [ ] #461

**Comment by 1Doomdie1** [comment]
#170 test for bot

**Comment by 1Doomdie1** [comment]
- [ ] #609

**Comment by 1Doomdie1** [comment]
test to delete

**Comment by 1Doomdie1** [comment]
- [ ] #614

**Comment by arv0804** [comment]
#615

**Comment by odehDanOps** [comment]
- [ ] #616

**Comment by odehDanOps** [comment]
- [ ] #617

**Comment by djl11** [comment]
#619

**Comment by foobarrymore** [comment]
- [ ] #622

**Comment by 1Doomdie1** [comment]
- [ ] #622

**Comment by foobarrymore** [comment]
- [ ] #622

**Comment by Aarsh2001** [comment]
- [ ] #628

**Comment by foobarrymore** [comment]
- [ ] #622

**Comment by 1Doomdie1** [comment]
- [ ] #615

**Comment by 1Doomdie1** [comment]
- [ ] #622

**Comment by capogluuu** [comment]
- [ ] #659

**Comment by capogluuu** [comment]
- [ ] #660

**Comment by Eng-Abdelrahman-M** [comment]
- [ ] #661

**Comment by bethelhall** [comment]
- [ ] 675

**Comment by varsharoshan** [comment]
- [ ] #805
