### ISSUE TITLE
tensorflow.nn.dropout

### ISSUE THREAD

**Issue by fspyridakos** [unifyai/ivy#7502]
The function is generally not implemented properly, the parameters of `tf.dropout` are not there. Please review the function and it's properties as described in the tf docs and handle all the parameters properly, (except seed which is not working properly for this function in tf).

**Comment by AnnaTz** [comment]
solved in https://github.com/unifyai/ivy/commit/a97fceea32a6d63c9ecdb681e4f088d929e7f6e5
