### ISSUE TITLE
[Bug]: Improperly formatted section in the Container Docs

### ISSUE THREAD

**Issue by sagewhocodes** [unifyai/ivy#7549]
### Bug Explanation

The example under the `__pow__` section under `Container ` Docs is improperly formatted 
<img width="745" alt="CleanShot 2022-12-03 at 18 01 56@2x" src="https://user-images.githubusercontent.com/54904272/205441064-26953d72-2b02-414c-991b-d0d17d2ab176.png">

### Steps to Reproduce Bug

Just go to https://lets-unify.ai/ivy/_modules/ivy/container/container.html#Container.__pow__

### Environment

NA

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by AnnaTz** [comment]
I just pushed https://github.com/unifyai/ivy/commit/2b8f21bd2a54075491b10cd6042fe0c2cace4894 for this. Kindly check if it's resolved now.

**Comment by sagewhocodes** [comment]
LGTM
