### ISSUE TITLE
frontend for `torch.Tensor.expand` (incomplete behaviour)

### ISSUE THREAD

**Issue by guillesanbri** [unifyai/ivy#7599]
The `torch.Tensor.expand` method supports `-1` to be passed as arguments. These arguments are passed directly to the `ivy` function, which again passes them to the appropriate backend. As the rest of backends don't support `-1` as a dimension size, the following use of the function fails.

```
import torch
import ivy.functional.frontends.torch as torch_frontend
import ivy

ivy.set_backend("numpy")  # "jax", "tensorflow"

# Torch
# use of -1 as dimension size
x = torch.tensor([[1], [2], [3]])
print(x.shape)  # [3, 1]
x_torch = x.expand(-1, 4)
print(x_torch.shape)  # [3, 4]

# Torch frontend
x = torch_frontend.tensor([[1], [2], [3]])
print(x.size())  # [3, 1]
x_ivy = x.expand(-1, 4)  # only works with torch backend
```

**Comment by agniiyer** [comment]
https://github.com/unifyai/ivy/pull/9935
