### ISSUE TITLE
[Feature Request]: solve_triangular() in backend functional APIs

### ISSUE THREAD

**Issue by sagewhocodes** [unifyai/ivy#7608]
The implementation of this function will assist in the implementation of solve_triangular() for frontends.

[Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.linalg.solve_triangular.html)
[PyTorch](https://pytorch.org/docs/1.11/generated/torch.linalg.solve_triangular.html)
[TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/triangular_solve)
[NumPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html)

**Comment by hirwa-nshuti** [comment]
Hi,
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks🙂
