### ISSUE TITLE
Add the missing frontend functions to compile HuggingFace models

### ISSUE THREAD

**Issue by modanesh** [unifyai/ivy#7684]
In order to be able to compile all the transformer models in the [HuggingFace](https://huggingface.co/docs/transformers/index), there a few missing frontend functions in `torch`, `jax`, and `tensorflow`. Following is the list of these functions. Please feel free to work on any one of these functions. But before starting to work, check if someone is already working on it or not.

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #7784
- [x] #8968
- [x] #7697
- [x] torch.Tensor.clone
- [X] #7609
- [x] `torch.Tensor.\_\_invert\_\_`
- [X] #7500
- [x] torch.Tensor.where
- [X] #7524
- [X] #7505
- [X] #7621
- [X] #7610
- [x] #7839
- [X] #7530 
- [X] #7528
- [X] #7640
- [x] #7840
- [x] #8393
- [X] #7642
- [X] #7644
- [X] #7646
- [x] #7696
- [x] #7846
- [x] #7847
- [X] #7660 
- [X] #7663 
- [X] `torch.Tensor.\_\_ne\_\_`
- [x] #7687
- [x] #8525
- [X] `torch.Tensor.\_\_lt\_\_`
- [X] #7685
- [x] #8939
- [x] #8967
- [x] #7790
- [x] torch.nn.functional.batch_norm
- [x] #10523 
- [x] #9529
- [x] #7703
- [x] #7704
- [x] #7705
- [x] #7706
- [x] #7707
- [x] jax.numpy._rewriting_take
- [x] #7852
- [x] #7853
- [x] #7775
- [x] jax.numpy.amax
- [x] #7792
- [x] #7849
- [x] #7850
- [x] #9447
- [x] #9448
- [x] #7871
- [x] jax.lax.rsqrt
- [x] tensorflow.convert_to_tensor
- [x] #7858
- [x] #8808
- [x] #7872
- [x] #7802
- [x] #7912
- [x] tensorflow.moments
- [x] #9457
- [x] #7789
- [x] #9592
- [x] #7911
- [x] #8522
- [x] tensorflow.stack
- [x] #7873
- [x] #7874

**Comment by modanesh** [comment]
- [ ] #7685

**Comment by modanesh** [comment]
- [ ] #7687

**Comment by div5252** [comment]
- [ ] #7775

**Comment by LucaLumetti** [comment]
- [ ] #7784

**Comment by hmahmood24** [comment]
- [ ] #7788

**Comment by hmahmood24** [comment]
- [ ] #7789

**Comment by hmahmood24** [comment]
- [ ] #7790

**Comment by div5252** [comment]
[] #7792

**Comment by avinashyadav0027** [comment]
- [ ]  #7802

**Comment by hirwa-nshuti** [comment]
- [ ] #7871

**Comment by hirwa-nshuti** [comment]
- [ ] #7872

**Comment by hirwa-nshuti** [comment]
- [ ] #7873

**Comment by hirwa-nshuti** [comment]
- [ ] #7874

**Comment by div5252** [comment]
- [ ] #7911

**Comment by anurag629** [comment]
-[] #8522

**Comment by Ishticode** [comment]
- [ ] #9457
