### ISSUE TITLE
Reformat norms

### ISSUE THREAD

**Issue by saeedashrraf** [unifyai/ivy#778]
Each method in the [norms](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/norms.py) submodule should be modified to use the latest formatting rules, as explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) for the [Ivy API](https://lets-unify.ai/ivy/contributing.html#ivy-api) and [Backend API](https://lets-unify.ai/ivy/contributing.html#backend-api). This includes removing all lambdas and direct bindings for methods in the backend submodules, with each method instead defined using `def method_name`. Full type hints should also be given for each argument in both the ivy module and also each backend module. The docstrings should be updated to use NumPy style rather than Sphinx style, and code examples should be added to **every** method docstring.

- [ ]  #1136

**Comment by cybermind-nick** [comment]
- [ ] #1136
