### ISSUE TITLE
torch.Tensor.masked_fill

### ISSUE THREAD

**Issue by LucaLumetti** [unifyai/ivy#7784]

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would like to continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues

**Comment by AnnaTz** [comment]
Completed in https://github.com/unifyai/ivy/commit/4d09e4d9e3d516074824e67a83528a393067b262
