### ISSUE TITLE
torch.range

### ISSUE THREAD

**Issue by fspyridakos** [unifyai/ivy#7837]
This funciton can be found in the `creation_ops` namespace

The behaviour of `torch.range` does not match the behvaiour outlined in the docs: https://pytorch.org/docs/stable/generated/torch.range.html
Namely, the current implementation in the frontend calls `ivy.arange` which outputs a tensor of shape [(end-start)/step], whereas `torch.range` outputs a tensor of shape [(end-start)/step] + 1. Please fix the frontend implementation to match the torch behaviour.

**Comment by Namangarg110** [comment]
Hey,
I believe `torch.range` and `torch.arange` are two different functions. Torch. range outputs [(end-start)/step] + 1 whereas `torch.arange` outputs [(end-start)/step] . Therefore, I believe the implementation of ` ivy.arange` is correct. Additionally, I have mentioned links to both of the implementations below for your reference.

torch.range : [Link to torch.range](https://pytorch.org/docs/stable/generated/torch.range.html)
torch.arange : [Link to torch.arange](https://pytorch.org/docs/stable/generated/torch.arange.html)

**Comment by fspyridakos** [comment]
Yes `torch.range` and `torch.arange` are two different functions but they're implemented in the same way in our torch frontend. Our implementation of `torch.range` need to be modified to support the output of shape [(end-start)/step] + 1. Right now it outputs a shape of [(end-start)/step] because it simply calls `ivy.arange`.

**Comment by AnnaTz** [comment]
I already fixed that a few weeks ago. @fspyridakos feel free to verify
