### ISSUE TITLE
gelu

### ISSUE THREAD

**Issue by AduGyamfi-David** [unifyai/ivy#784]
- []#754

**Comment by ivy-seed** [comment]
This issue has been labelled as stale. If you would like to continue working on this issue, then please add another comment or create a PR . If a PR has already been created which refers to this issue, then you should explicitly mention this issue in the relevant PR. For more information please refer to this page in our documentation: https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues
