### ISSUE TITLE
ivy.linalg.lu

### ISSUE THREAD

**Issue by somaia02** [unifyai/ivy#7890]
**Why should this be implemented?**
Because 3 of the native frameworks have it, and it's a complex function.

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.linalg.lu.html)
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.linalg.lu.html#torch.linalg.lu)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/linalg/lu)

**Comment by hirwa-nshuti** [comment]
Hi,
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks🙂
