### ISSUE TITLE
Fix tensor.test_tensorflow_instance_add

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8010]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5545615556/jobs/10124792323"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5545615556/jobs/10124792323"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5545615556/jobs/10124792323"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5545615556/jobs/10124792323"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5545615556/jobs/10124792323"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by Jagwar8** [comment]
- [ ] #9127
