### ISSUE TITLE
Reformat compilation 

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#807]
As explained in the function reformatting [open task](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting), each function in the [compilation](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/compilation.py) submodule should be updated to follow the implementation instructions given in the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) section of the docs. The updates should be applied for both the [Ivy API](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#ivy-api) and [Backend API](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#backend-api). The [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) is the best general resource for learning in detail how functions should be implemented. Many of the functions are not implemented as they should be. You will need to make changes to the current implementations, but you do not need to go through all section of the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html). Specifically, you should make the following changes, where appropriate:

1. remove all lambda and direct bindings for backend functions, with each function instead defined using def.
2. update the [function arguments](https://lets-unify.ai/ivy/deep_dive/9_function_arguments.html) and type hints.
3. add the correct [docstrings](https://lets-unify.ai/ivy/deep_dive/10_docstrings.html)
4. add thorough [docstring examples](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html)

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [ ]  compile

**Comment by olubiyiontheweb** [comment]
- [ ] #1330

**Comment by lt77777** [comment]
Hello, can I do this task?

**Comment by olubiyiontheweb** [comment]
Hi @lt77777, you can go ahead. I'm not available for it at the moment.

**Comment by lt77777** [comment]
Great thank you!

**Comment by kundakinte** [comment]
is this task still available to do?

**Comment by huseyinevecen** [comment]
- [ ] #5611

**Comment by shadmeoli** [comment]
Working on:

- remove all lambda and direct bindings for backend functions, with each function instead defined using def.

**Comment by shadmeoli** [comment]
#8511

**Comment by Fayad-Alman** [comment]
#9315

**Comment by diyorbekibragimov** [comment]
#12775

**Comment by diyorbekibragimov** [comment]
- [ ] #12775
