### ISSUE TITLE
Reformat image

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#808]
As explained in the function reformatting [open task](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting), each function in the [image](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/image.py) submodule should be updated to follow the implementation instructions given in the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) section of the docs. The updates should be applied for both the [Ivy API](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#ivy-api) and [Backend API](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#backend-api). The [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) is the best general resource for learning in detail how functions should be implemented. Many of the functions are not implemented as they should be. You will need to make changes to the current implementations, but you do not need to go through all section of the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html). Specifically, you should make the following changes, where appropriate:

1. remove all lambda and direct bindings for backend functions, with each function instead defined using def.
2. update the [function arguments](https://lets-unify.ai/ivy/deep_dive/9_function_arguments.html) and type hints.
3. add the correct [docstrings](https://lets-unify.ai/ivy/deep_dive/10_docstrings.html)
4. add thorough [docstring examples](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html)

- [ ] #1443 
- [ ]  bilinear_resample 
- [ ] gradient_image 
- [ ] #5262 
- [ ] #1339
- [ ] #4270 
- [ ] #2084

**Comment by Allaye** [comment]
861

**Comment by Allaye** [comment]
[ ] #861

**Comment by varsharoshan** [comment]
#867

**Comment by Allaye** [comment]
@varsharoshan  this issue is already been worked on.

**Comment by varsharoshan** [comment]
#889

**Comment by kirodev** [comment]
[ ] : #1034

**Comment by sowmen** [comment]
[]:#1041

**Comment by somesh-raju** [comment]
- [ ] #1164

**Comment by JialWu** [comment]
[ ] #1200

**Comment by JialWu** [comment]
[ ] #1200

**Comment by JialWu** [comment]
- [ ] #1200

**Comment by Allaye** [comment]
- [ ]#1324

**Comment by Allaye** [comment]
#1324

**Comment by Allaye** [comment]
- [ ] #1324

**Comment by Preeti2095** [comment]
#1339

**Comment by dashingzombie** [comment]
stack_images #1443

**Comment by pythonlessons** [comment]
There is no such images.py in the given path:
https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/image.py

**Comment by Guru-mp3** [comment]
random_crop #4270

**Comment by dianyo** [comment]
- [ ] #5262

**Comment by djl11** [comment]
Thanks @pythonlessons, yes this is no longer a module we are supporting.
