### ISSUE TITLE
tanh

### ISSUE THREAD

**Issue by Mia-dev200** [unifyai/ivy#809]
- [ ] #754

**Comment by Mia-dev200** [comment]
#754

**Comment by Mia-dev200** [comment]
[ ] #754

**Comment by Mia-dev200** [comment]
- [ ] #754

**Comment by Mia-dev200** [comment]
#754

**Comment by 1Doomdie1** [comment]
Please leave a comment with your issue id here: #754 
This way the function will be allocated to you automatically!
Thank you!

**Comment by Mia-dev200** [comment]
> Please leave a comment with your issue id here: #754 This way the function will be allocated to you automatically! Thank you!

Heyy , how can i ask for review of my PR ... I'm not understanding where I'm going wrong
