### ISSUE TITLE
Reformat manipulation 

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#810]
As explained in the function reformatting [open task](https://lets-unify.ai/docs/ivy/overview/contributing/open\_tasks.html#function-formatting), each function in the [manipulation](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/manipulation.py) submodule should be updated to follow the implementation instructions given in the [Deep Dive](https://lets-unify.ai/docs/ivy/overview/deep\_dive.html) section of the docs. The updates should be applied for both the [Ivy API](https://lets-unify.ai/docs/ivy/overview/deep\_dive/navigating\_the\_code.html#ivy-api) and [Backend API](https://lets-unify.ai/docs/ivy/overview/deep\_dive/navigating\_the\_code.html#backend-api). The [Deep Dive](https://lets-unify.ai/docs/ivy/overview/deep\_dive.html) is the best general resource for learning in detail how functions should be implemented. Many of the functions are not implemented as they should be. You will need to make changes to the current implementations, but you do not need to go through all section of the [Deep Dive](https://lets-unify.ai/docs/ivy/overview/deep\_dive.html). Specifically, you should make the following changes, where appropriate:

1. remove all lambda and direct bindings for backend functions, with each function instead defined using def.
2. update the [function arguments](https://lets-unify.ai/docs/ivy/overview/deep\_dive/function\_arguments.html) and type hints.
3. add the correct [docstrings](https://lets-unify.ai/docs/ivy/overview/deep\_dive/docstrings.html)
4. add thorough [docstring examples](https://lets-unify.ai/docs/ivy/overview/deep\_dive/docstring\_examples.html)

\_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue\_number" while the issue's title only includes the name of the function you've chosen.

\_

- [x] #1655 
- [x] #5847 
- [x] #2005 
- [x] #1809 
- [x] #6960 
- [x] #942 
- [x] #1806 
- [x] #1095 
- [x] #1178 
- [x] #1879 
- [x] #2078 
- [x] #6448 
- [x] #15888
- [x] #1585 
- [x] #1624

**Comment by kirodev** [comment]
[ ] : #942

**Comment by banditelol** [comment]
- [ ] #973

**Comment by Klins101** [comment]
- [ ] #1049

**Comment by kirodev** [comment]
[] : #1095

**Comment by yoviny** [comment]
- [ ] #1120

**Comment by MaximilianH2024** [comment]
#1153

**Comment by PhyseChan** [comment]
#1160

**Comment by Oxbeefbabe** [comment]
#1178

**Comment by ishishruti** [comment]
[flip] #1185

**Comment by kunwarsaaim** [comment]
#1190

**Comment by sohamtiwari3120** [comment]
[ ] #1221

**Comment by pfdah** [comment]
concatenate #1095

**Comment by suhy-jang** [comment]
#1458

**Comment by Klins101** [comment]
- [ ] #1585

**Comment by zaeemansari70** [comment]
- [ ] #1624

**Comment by suhy-jang** [comment]
- [ ]  #1655

**Comment by Klins101** [comment]
- [ ] #1672

**Comment by OscarEMoreno** [comment]
roll #1806

**Comment by rgoyal10** [comment]
- [ ] #1950

**Comment by danielmunioz** [comment]
#2005

**Comment by imranlala99** [comment]
reshape https://github.com/unifyai/ivy/issues/942

**Comment by imranlala99** [comment]
reshape #942

**Comment by daisy-dotcom** [comment]
- [ ] #2078

**Comment by LuongNguyenSep14** [comment]
zero_pad #3062

**Comment by LuongNguyenSep14** [comment]
- zero_pad #3062

**Comment by LuongNguyenSep14** [comment]
- #3062

**Comment by seppemarotta** [comment]
- [4678] #Issue_num.

**Comment by seppemarotta** [comment]
- [ ] #4678.

**Comment by Girgis98** [comment]
constant_pad #4845

**Comment by hnehme99** [comment]
#5847

**Comment by volkaseezn** [comment]
- [ ] #6448

**Comment by DsJamwal** [comment]
stack #6960

**Comment by malav312** [comment]
- [ ] #7214

**Comment by mnbrshd** [comment]
- [ ] #7867

**Comment by ioannispol** [comment]
zero_pad #9252

**Comment by ashioyajotham** [comment]
Hello, I am a bit confused. Is zero_pad completed because I can see a completed PR but yet the box is unchecked. Please help :)

**Comment by andrewhinh** [comment]
Concatenate is already finished as noted at #1095
