### ISSUE TITLE
Fix ndarray.test_numpy_instance_abs__

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8112]
|   |   |
|---|---|
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5616626394"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5616626394"><img src=https://img.shields.io/badge/-success-success></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5616626394"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5616626394"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5616626394"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by rarisenpai** [comment]
Fix ndarray.test_numpy_instance_abs__ #12453
