### ISSUE TITLE
Reformat statistical 

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#812]
As explained in the function reformatting [open task](https://lets-unify.ai/docs/ivy/overview/contributing/open_tasks.html#function-formatting), each function in the [statistical](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/statistical.py) submodule should be updated to follow the implementation instructions given in the [Deep Dive](https://lets-unify.ai/docs/ivy/overview/deep_dive.html) section of the docs. The updates should be applied for both the [Ivy API](https://lets-unify.ai/docs/ivy/overview/deep_dive/navigating_the_code.html#ivy-api) and [Backend API](https://lets-unify.ai/docs/ivy/overview/deep_dive/navigating_the_code.html#backend-api). The [Deep Dive](https://lets-unify.ai/docs/ivy/overview/deep_dive.html) is the best general resource for learning in detail how functions should be implemented. Many of the functions are not implemented as they should be. You will need to make changes to the current implementations, but you do not need to go through all section of the [Deep Dive](https://lets-unify.ai/docs/ivy/overview/deep_dive.html). Specifically, you should make the following changes, where appropriate:

1. remove all lambda and direct bindings for backend functions, with each function instead defined using def.
2. update the [function arguments](https://lets-unify.ai/docs/ivy/overview/deep_dive/function_arguments.html) and type hints.
3. add the correct [docstrings](https://lets-unify.ai/docs/ivy/overview/deep_dive/docstrings.html)
4. add thorough [docstring examples](https://lets-unify.ai/docs/ivy/overview/deep_dive/docstring_examples.html)

_

>Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

_

- [x] #5595
- [x] #1739 
- [x] #2012 
- [x] #1890 
- [x] #1877 
- [x] #15001 
- [x] #5606 
- [x] #1491

**Comment by mwangggg** [comment]
- [ ] #872

**Comment by yezhengkai** [comment]
- [ ] #883

**Comment by codeboy5** [comment]
* [ ]  [mean #890](https://github.com/unifyai/ivy/issues/890)

**Comment by varsharoshan** [comment]
prod

**Comment by varsharoshan** [comment]
#913

**Comment by ketanchaudhari32** [comment]
#921

**Comment by DhruvaBhardwaj404** [comment]
[]#983

**Comment by lakshmanbathina115** [comment]
max#991

**Comment by lakshmanbathina115** [comment]
max #991

**Comment by kirodev** [comment]
[] : #1140

**Comment by RohitRathore1** [comment]
- [ ] #1167.

**Comment by abubakaralsadiq** [comment]
- [ ] 1210

**Comment by abubakaralsadiq** [comment]
sum #1210

**Comment by DanielJean007** [comment]
- [ ] #1344

**Comment by shysta-sehgal** [comment]
max #1412

**Comment by dubeyakshat07** [comment]
min #1473

**Comment by ctoanadu** [comment]
- [ ] #1491

**Comment by cass9918** [comment]
prod #913

**Comment by AnimeshSinha1309** [comment]
- [ ] #1473

**Comment by Nekorra** [comment]
[std#1344](https://github.com/unifyai/ivy/issues/812)

**Comment by topefolorunso** [comment]
- [ ] #1739

**Comment by patcasrares** [comment]
prod #1877

**Comment by Quickbick** [comment]
mean #1890

**Comment by Hardik7498** [comment]
[ ] #Issue_min.

**Comment by Hardik7498** [comment]
mean #1890

**Comment by Hardik7498** [comment]
@mattbarrett98  can you tell i open issue of mean is successfully open or not open at

**Comment by egg-west** [comment]
- [ ] #2012

**Comment by KaisHasan314** [comment]
- [] #1877

**Comment by nassimberrada** [comment]
#4101

**Comment by Jobsy** [comment]
#5595

**Comment by nickan2c** [comment]
std #5606

**Comment by Ayush200423** [comment]
- [ ] #15001
