### ISSUE TITLE
Fix averages_and_variances.test_numpy_mean

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8167]
|   |   |
|---|---|
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6408093971"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6408093971"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6408093971"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6408093971"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6408093971"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by AbhishekRP2002** [comment]
Can you assign this issue to me ?

**Comment by abdulasiraj** [comment]
start working

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
