### ISSUE TITLE
ivy.interpolate

### ISSUE THREAD

**Issue by AnnaTz** [unifyai/ivy#8392]
**Why should this be implemented?**
Because both pytorch and tensorflow have it, and it's a complex function. 
The functionality is not exactly the same for the two frameworks but there are some common interpolation modes.

**Links to native framework implementations**
- [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html)
- [TensorFlow](https://www.tensorflow.org/graphics/api_docs/python/tfg/math/interpolation)

**Comment by hirwa-nshuti** [comment]
Hi,
This function is also going to be added to the extension ToDo list.
Thanks🙂
