### ISSUE TITLE
Error from 'collections' module

### ISSUE THREAD

**Issue by mattbarrett98** [unifyai/ivy#84]
I'm getting the following error when I run any test:

ivy/framework_handler.py:119: in set_framework
    if isinstance(specific_v, collections.Hashable):
E   AttributeError: module 'collections' has no attribute 'Hashable'

I'm using Python 3.10.2. Replacing 'collections.hashable' with 'collections.abc.hashable' lets me run the tests.

**Comment by djl11** [comment]
Thanks for the clarification @kvignesh1420. Currently the unit tests use the default python that comes with ubuntu:20.04, which is python 3.8. When I update the dockerfile to ubuntu 22:04 at some point then I'll update this. In the meantime, it's advised to use python 3.8 when running the tests. I'll close this issue with that clarification, thanks for raising! 🙂
