### ISSUE TITLE
Fix tensor.test_torch_instance_permute

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8541]
|   |   |
|---|---|
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5740357384"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5740357384"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5740357384"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5740357384"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5740357384"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by mobley-trent** [comment]
@AnnaTz  I'm getting this error when trying to run the test:

```
hypothesis.errors.InvalidArgument: test_torch_instance_permute() got an unexpected keyword argument 'unpack_dims', from `unpack_dims=booleans()` in @given
```

Why is the error being raised in the first place ? There doesn't seem to be any outstanding issue with the test

**Comment by AnnaTz** [comment]
> @AnnaTz I'm getting this error for all backends when trying to run the test:
> 
> ```
> hypothesis.errors.InvalidArgument: test_torch_instance_permute() got an unexpected keyword argument 'unpack_dims', from `unpack_dims=booleans()` in @given
> ```
> 
> Why is the error being raised in the first place ? There doesn't seem to be any outstanding issue with the test

That was simply because `unpack_dims` was generated in `handle_frontend_method` but not used in `test_torch_instance_permute`. I removed it and now the test is passing.
