### ISSUE TITLE
Fix jax_nn_activations.test_jax_nn_celu

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8687]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5585393361"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5585393361"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5585393361"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5585393361"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5585393361"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by Puriva** [comment]
hey i am interested to take this as assignment
