### ISSUE TITLE
Fix nest.test_tensorflow_flatten

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8868]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6412665013/job/17410336937"><img src=https://img.shields.io/badge/-failure-red></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6412665013/job/17410336937"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6364847344/job/17281409619"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6364847344/job/17281409619"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6364847344/job/17281409619"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by jonotassia** [comment]
Hi all,

I'm working on restructuring the associated Tensorflow Frontend function in #15090, so I'll give this one a go at the same time.

**Comment by jonotassia** [comment]
Did some debugging with this one as part of the frontent `tf.flatten` function restructuring and wanted to update with my findings. 

It appears the main issue here is that the `frontend_ret` is being returned as a Python list, which is not being handled in `test_frontent_function` (see details [here](https://github.com/unifyai/ivy/pull/15090#issuecomment-15498747808)), so @sherry30 is going to raise this with the testing team.

**Comment by ivy-leaves** [comment]
Hi there,

Just to let you know, this issue has been depreciated. However, new issues related to any failing tests will be created very soon, marked distinctly with the `Failing Test` label.

Kindly stay tuned for the relevant announcements on our [Discord server](https://discord.com/channels/799879767196958751/983684937712558080) in the coming week.

Thank you for your understanding and cooperation.
