### ISSUE TITLE
Fix sums_products_differences.test_numpy_nancumprod

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#8934]
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6360591445/job/17274454459"><img src=https://img.shields.io/badge/-success-success></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6360591445/job/17274454459"><img src=https://img.shields.io/badge/-success-success></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6360591445/job/17274454459"><img src=https://img.shields.io/badge/-success-success></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6360591445/job/17274454459"><img src=https://img.shields.io/badge/-success-success></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6360591445/job/17274454459"><img src=https://img.shields.io/badge/-success-success></a>

**Comment by moriisaac** [comment]
#9886
