### ISSUE TITLE
ivy.func_name() - add percentile/quantile

### ISSUE THREAD

**Issue by Tiago-B-C-Reis** [unifyai/ivy#8954]
Hello Ivy team,

This function `percentile` needs to be created on [Ivy API functions](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/statistical.py) in order to allow it to be called on the [frontend Ivy API](https://github.com/unifyai/ivy/tree/master/ivy/functional/frontends/numpy/statistics)

**Links to native framework implementations**
- [NumPy](<https://numpy.org/doc/stable/reference/generated/numpy.percentile.html#numpy-percentile>)

This will allow the resolution of this issue: https://github.com/unifyai/ivy/issues/8952

**Comment by hirwa-nshuti** [comment]
Hi @Tiago-B-C-Reis 
The link you shared isn't matching the function you stated in the issue could you explain further about the function you're suggesting and also if it exists in other frameworks as well
Thanks🙂

**Comment by Tiago-B-C-Reis** [comment]
Hello @hirwa-nshuti, thanks for the reply.

I'm trying to add an Ivy frontend function for Numpy statistical, pull request #9176, the percentile one that is open in this to-do list #1529.
The percentile function uses the quantile function with a little change, and there is an existing `quantile ` function on the [ivy functional ivy experimental statistical ](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/experimental/statistical.py) but is deprecated since version 1.22.0 and the new one has an argument called `method`.

Can you please help here?

**Comment by Tiago-B-C-Reis** [comment]
Hello [hirwa-nshuti](https://github.com/hirwa-nshuti),

I'm referring [here ](https://github.com/unifyai/ivy/pull/9176#issuecomment-1375233932) to the answer from [sherry30](https://github.com/sherry30) related to this issue.
Please give it a check in order to complete this task.
Thank you in advance.

**Comment by hirwa-nshuti** [comment]
Hi @Tiago-B-C-Reis
Thanks for suggesting the function and referring to the response you got from our team member we can add this function to an ongoing task of extending our functional API here [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856).

Meanwhile, I am going to close this issue and we thank you for contributing to Ivy😊
