### ISSUE TITLE
ivy.asmatrix

### ISSUE THREAD

**Issue by degagawolde** [unifyai/ivy#8988]
**Why should this be implemented?**
Because NumPy has it, and it's a complex function.

**Links to native framework implementations**
- [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.asmatrix.html)

**Comment by hirwa-nshuti** [comment]
Hi,
As the function is only implemented in NumPy only we can't go ahead and add it to the functional API, it can be possible if there is at least one other framework that supports it with this we will try to implement its composition in the numpy frontend. Therefore, this issue will now be closed. Thanks🙂
