### ISSUE TITLE
Amazing project！But how to unify data pipe, training loop and optimizer?

### ISSUE THREAD

**Issue by hanjr92** [unifyai/ivy#920]
At first, it's a amzing project! it can save a lot of time on switch project to different frameworks. Models and operators are  easy to convert.  But the data pipeline and training loop  are completely different between tensorflow and pytorch. it's a big hassle. In fact, I also encountered the same dilemma. I'm looking forward to your ability to solve this problem of automatic conversion.

**Comment by jkeane508** [comment]
Hi,

You can refer to our FAQ which talks about how Ivy will handle these [here](https://lets-unify.ai/ivy/faq.html) 🚀

Thanks!
