### ISSUE TITLE
ivy.multi_dot

### ISSUE THREAD

**Issue by danielmunioz** [unifyai/ivy#9231]
implementing ivy.multi_dot would help closing #9057
currently working on it

**Comment by danielmunioz** [comment]
this implementation would help closing #9057
currently working on it

**Comment by hirwa-nshuti** [comment]
Hi,
We have accepted that this function should be added to Ivy's functional API. This item has been added to our ongoing [Ivy Extension issue](https://github.com/unifyai/ivy/issues/3856). Therefore, this issue will now be closed. Thanks🙂
