### ISSUE TITLE
ivy.random_geometric

### ISSUE THREAD

**Issue by AbhirKarande** [unifyai/ivy#9311]
**Why should this be implemented?**
For #9277 the frontend implementation for normal, uniform, and dirichlet, each call upon ivy.<respective function>

**Links to native framework implementations**
- [NumPy]((https://numpy.org/doc/stable/reference/random/generated/numpy.random.geometric.html))

**Comment by hirwa-nshuti** [comment]
Hi @AbhirKarande 
Thanks for suggesting this function but as you've seen we are aiming at unifying ML libraries, we are extending our functional API with functions that exist in at least either two frameworks, given that the function you suggested is only in Numpy I think we can't go ahead and implement this function on our backends as it might cause overhead during the compositional implementation of the function  in backends🙂

If the function is complex to implement using ivy existing functions we can put it on hold and decide later whether to add it or not. For now, we can't add this function to the functional API.

I hope these explanations make sense and feel free to state your thoughts on this😊
Thanks.

**Comment by AbhirKarande** [comment]
I understand. Thanks for the response! I do have a working frontend function for geometric regardless so I suppose it isn't a problem.

**Comment by hirwa-nshuti** [comment]
Okay great thanks for that😊
I am going to close this issue then🙂
