### ISSUE TITLE
Update README code sample 

### ISSUE THREAD

**Issue by dom-inic** [unifyai/ivy#9443]
The code sample provided on the readme seems outdated. should be updated with the new functions; 

set_backend('torch') to set_framework('torch')

ivy.mean((out - target)**2) to ivy.reduce_mean((out - target)**2)

**Comment by jaketae** [comment]
Hey @dom-inic, I think it's the other way around: the README functions are the up-to-date versions. If you've installed Ivy via `pip install ivy-core`, it will install the version that was released in [June 2022](https://pypi.org/project/ivy-core/#history). You can install Ivy from source via

```
pip install .
```

in the root-level directory if you want to try to most up-to-date version.

**Comment by dom-inic** [comment]
okay @jaketae i guess that's what i should have done. Though the documentation and code sample on [https://pypi.org/project/ivy-core/](url) is updated whereas the code sample on the readme, or have the functions been reverted?

**Comment by jaketae** [comment]
The GitHub README/code are up-to-date, whereas PyPI one's aren't. I'm not a core maintainer, but this is probably because the PyPI versions were published last year. I'd assume at some point, the core devs will "cut" master for a new release with a version bump.

**Comment by hirwa-nshuti** [comment]
> okay @jaketae i guess that's what i should have done. Though the documentation and code sample on [https://pypi.org/project/ivy-core/](url) is updated whereas the code sample on the readme isn't, or have the functions been reverted?

Yea you're right the pypi documentation is not up to date I would recommend you to use the current documentation on our master branch [Documentation](https://lets-unify.ai/ivy/index.html)
