### ISSUE TITLE
[RFC] Clean up the root directory by moving executables

### ISSUE THREAD

**Issue by jaketae** [unifyai/ivy#9446]
## Context

While this may be a matter of subjective opinion, for reasons of organization and maintainability, it could be preferable to have executable scripts in a separate directory of their own. Currently, the `.sh` and `.py` files are exposed in the root level directory.

## Proposed Solution

Create a new `bin` directory to hold all shell/Python scripts. See [this](https://unix.stackexchange.com/questions/372245/is-the-bin-directory-for-storing-binary-files) and [this](https://softwareengineering.stackexchange.com/questions/274721/should-a-bin-directory-be-full-of-shell-scripts) SE post for the reasoning behind naming the directory `bin`. 

Before:

```
$ ls
automation_tools  determine_test_coverage.py  ivy                MANIFEST.in             requirements     setup.cfg
build             determine_tests.py          ivy_core.egg-info  merge_with_upstream.sh  run_tests_CLI    setup.py
clone_mapping.sh  docker                      ivy_tests          project.toml            run_tests_pr.py  setup_tests.py
deploy_pypi.sh    docs                        LIC
```

After:

```
$ ls
automation_tools  build   docs  ivy_core.egg-info  LICENSE      project.toml  requirements   setup.cfg
bin               docker  ivy   ivy_tests          MANIFEST.in  README.rst    run_tests_CLI  setup.py
```

## Blockers

One issue with the proposed solution is that it is a breaking change that could affect the CI, among others. For instance, `clone_mapping.sh` is referenced in `intelligent-tests.yml`:

```yaml
run: |
  source ./ivy/clone_mapping.sh master1
```

We would have to `grep` all instances of such executables and adjust their path.

Another potential issue is that the executables may not work as intended after they are moved if they rely on some relative import or path resolution. We would have to spend some time to verify their correctness after the reorganization.

**Comment by niranjandasMM** [comment]
I didn't Grasped much but here's my conclusion , hope this may help
One issue is that this chage could break the CI (Continuous Integration) process, as some of the scripts are referenced in other files (such as "intelligent-tests.yml"). You would need to find all the references to the scripts and adjust their paths accordingly.

Another issue is that moving the scripts to a different directory could cause them to break if you rely on relative imports or path resolution. You would need to verify that the scripts are still functioning correctly after they are moved.

**Comment by jaketae** [comment]
Hey @niranjandasMM, thanks for the comment! Those are exactly the issues I mentioned under "Blockers," and I agree with your points. I'm curious to hear what the core devs think given that they have more insight into how the project is organized and how/where the executables are invoked.
