### ISSUE TITLE
tensorflow.keras.metrics.binary_crossentropy

### ISSUE THREAD

**Issue by fspyridakos** [unifyai/ivy#9640]
The line `return ivy.mean(ivy.binary_cross_entropy(y_true, y_pred, label_smoothing))` passes `label_smoothing` as a positional argument but this argument is not supported by `ivy.binary_cross_entropy` thus it must be handled compositionally in the function. TF's native function could help here: https://github.com/keras-team/keras/blob/e6784e4302c7b8cd116b74a784f4b78d60e83c26/keras/losses.py#L2136

**Comment by Kranium2002** [comment]
I would like to work on this issue. Is it possible for you to assign it to me as to avoid double work?

**Comment by fspyridakos** [comment]
> I would like to work on this issue. Is it possible for you to assign it to me as to avoid double work?

Sorry but it seems @mohamedehab0999 started a PR for this already

**Comment by AnnaTz** [comment]
completed in https://github.com/unifyai/ivy/commit/49e54d051d4aeb8ee241bba73ac2d3ee5347de78
