### ISSUE TITLE
frontend for `torch.Tensor.view` (incomplete behaviour)

### ISSUE THREAD

**Issue by guillesanbri** [unifyai/ivy#9665]
The `view` method of `torch.Tensor` allows the use of both a tuple and various `int`s as arguments. The frontend function does not support the expanded alternative as shown below. On top of that, it seems like the keyword argument is `size` and not `shape`.

```
import torch

x = torch.arange(8)
x_torch = x.view(size=(2, 2, 2))  # works
x_torch = x.view(shape=(2, 2, 2))  # fails
```

```
import torch
import ivy.functional.frontends.torch as torch_frontend
import ivy

ivy.set_backend("torch")  # "numpy", "jax", "tensorflow"

# Torch
x = torch.arange(8)
x_torch = x.view(2, 2, 2)  # works

# Torch frontend
x = torch_frontend.arange(8)
x_ivy = x.view(2, 2, 2)  # fails
```

**Comment by mattiagaggi** [comment]
tackling this issue, should make a pull request by monday evening
