### ISSUE TITLE
Fix MaskedArray.test_numpy_maskedarray_property_fill_value

### ISSUE THREAD

**Issue by ivy-leaves** [unifyai/ivy#9696]
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5642712797"><img src=https://img.shields.io/badge/-failure-red></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5642712797"><img src=https://img.shields.io/badge/-failure-red></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5642712797"><img src=https://img.shields.io/badge/-failure-red></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5642712797"><img src=https://img.shields.io/badge/-failure-red></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5642712797"><img src=https://img.shields.io/badge/-failure-red></a>

**Comment by kunal266** [comment]
seems like the error  we are getting are for large number being not correctly casted to its particular framework, here the datatype for 9223372036854775808 was give as int32 but the number is too large to be casted as int32. 
Most probably it should be unint64 
the dtype is given by the helper function  ```get_dtypes()```
so this is where the original error occures from.
Can someone explain how this ```[draw(st.shared(st.sampled_from(valid_dtypes[index:]), key=key))]```  from ```get_dtypes()``` works
