### ISSUE TITLE
ivy.compress

### ISSUE THREAD

**Issue by onedeeper** [unifyai/ivy#9851]
**Why should this be implemented?**
Because 3+ of the native frameworks have it, and it's a complex function.

**Links to native framework implementations**
- [Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.compress.html)
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/boolean_mask)
- [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.compress.html#numpy-compress)

**Comment by AnnaTz** [comment]
[`ivy.gather`](https://lets-unify.ai/ivy/functional/ivy/general/gather.html?highlight=gather) already offers a very similar functionality, so I don't think we need an `ivy.compress`. Feel free to further discuss this if you've got any doubts.
